import { ImageSourcePropType } from "react-native";

// "_" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_OTHER: Record<string, ImageSourcePropType> = {
  あなた: require("../../../assets/words/_/あなた.png"),
  人: require("../../../assets/words/_/人.png"),
  今: require("../../../assets/words/_/今.png"),
  今日: require("../../../assets/words/_/今日.png"),
  会社員: require("../../../assets/words/_/会社員.png"),
  兄: require("../../../assets/words/_/兄.png"),
  先生: require("../../../assets/words/_/先生.png"),
  冬: require("../../../assets/words/_/冬.png"),
  医者: require("../../../assets/words/_/医者.png"),
  午後: require("../../../assets/words/_/午後.png"),
  名前: require("../../../assets/words/_/名前.png"),
  夏: require("../../../assets/words/_/夏.png"),
  夜: require("../../../assets/words/_/夜.png"),
  女: require("../../../assets/words/_/女.png"),
  妹: require("../../../assets/words/_/妹.png"),
  姉: require("../../../assets/words/_/姉.png"),
  子供: require("../../../assets/words/_/子供.png"),
  学生: require("../../../assets/words/_/学生.png"),
  家: require("../../../assets/words/_/家.png"),
  家族: require("../../../assets/words/_/家族.png"),
  弟: require("../../../assets/words/_/弟.png"),
  明日: require("../../../assets/words/_/明日.png"),
  春: require("../../../assets/words/_/春.png"),
  昨日: require("../../../assets/words/_/昨日.png"),
  昼: require("../../../assets/words/_/昼.png"),
  時間: require("../../../assets/words/_/時間.png"),
  朝: require("../../../assets/words/_/朝.png"),
  来年: require("../../../assets/words/_/来年.png"),
  来週: require("../../../assets/words/_/来週.png"),
  母: require("../../../assets/words/_/母.png"),
  毎日: require("../../../assets/words/_/毎日.png"),
  父: require("../../../assets/words/_/父.png"),
  男: require("../../../assets/words/_/男.png"),
  私: require("../../../assets/words/_/私.png"),
  秋: require("../../../assets/words/_/秋.png"),
  覚える: require("../../../assets/words/_/覚える.png"),
  誕生日: require("../../../assets/words/_/誕生日.png"),
};
