import { ImageSourcePropType } from "react-native";

// "a" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_A: Record<string, ImageSourcePropType> = {
  "a great deal": require("../../../assets/words/a/a-great-deal.png"),
  "a host of": require("../../../assets/words/a/a-host-of.png"),
  "a quarter": require("../../../assets/words/a/a-quarter.png"),
  "a variety of": require("../../../assets/words/a/a-variety-of.png"),
  "a wide range of": require("../../../assets/words/a/a-wide-range-of.png"),
  abandon: require("../../../assets/words/a/abandon.png"),
  able: require("../../../assets/words/a/able.png"),
  abnormal: require("../../../assets/words/a/abnormal.png"),
  abnormally: require("../../../assets/words/a/abnormally.png"),
  aboard: require("../../../assets/words/a/aboard.png"),
  abolish: require("../../../assets/words/a/abolish.png"),
  aboriginal: require("../../../assets/words/a/aboriginal.png"),
  "abound in": require("../../../assets/words/a/abound-in.png"),
  abroad: require("../../../assets/words/a/abroad.png"),
  abrupt: require("../../../assets/words/a/abrupt.png"),
  absence: require("../../../assets/words/a/absence.png"),
  absent: require("../../../assets/words/a/absent.png"),
  absolute: require("../../../assets/words/a/absolute.png"),
  absorb: require("../../../assets/words/a/absorb.png"),
  abstract: require("../../../assets/words/a/abstract.png"),
  abundance: require("../../../assets/words/a/abundance.png"),
  abundant: require("../../../assets/words/a/abundant.png"),
  abuse: require("../../../assets/words/a/abuse.png"),
  academic: require("../../../assets/words/a/academic.png"),
  "accede with": require("../../../assets/words/a/accede-with.png"),
  accelerate: require("../../../assets/words/a/accelerate.png"),
  accent: require("../../../assets/words/a/accent.png"),
  accept: require("../../../assets/words/a/accept.png"),
  access: require("../../../assets/words/a/access.png"),
  accessible: require("../../../assets/words/a/accessible.png"),
  accident: require("../../../assets/words/a/accident.png"),
  accidentally: require("../../../assets/words/a/accidentally.png"),
  accommodate: require("../../../assets/words/a/accommodate.png"),
  accommodation: require("../../../assets/words/a/accommodation.png"),
  "accompanied by": require("../../../assets/words/a/accompanied-by.png"),
  accompany: require("../../../assets/words/a/accompany.png"),
  accomplish: require("../../../assets/words/a/accomplish.png"),
  accomplished: require("../../../assets/words/a/accomplished.png"),
  accord: require("../../../assets/words/a/accord.png"),
  "according to": require("../../../assets/words/a/according-to.png"),
  account: require("../../../assets/words/a/account.png"),
  "account for": require("../../../assets/words/a/account-for.png"),
  accountable: require("../../../assets/words/a/accountable.png"),
  accumulate: require("../../../assets/words/a/accumulate.png"),
  accuracy: require("../../../assets/words/a/accuracy.png"),
  accurate: require("../../../assets/words/a/accurate.png"),
  accuse: require("../../../assets/words/a/accuse.png"),
  "accustomed to": require("../../../assets/words/a/accustomed-to.png"),
  ache: require("../../../assets/words/a/ache.png"),
  achieve: require("../../../assets/words/a/achieve.png"),
  acid: require("../../../assets/words/a/acid.png"),
  acknowledge: require("../../../assets/words/a/acknowledge.png"),
  acoustic: require("../../../assets/words/a/acoustic.png"),
  acquire: require("../../../assets/words/a/acquire.png"),
  acquisition: require("../../../assets/words/a/acquisition.png"),
  active: require("../../../assets/words/a/active.png"),
  activity: require("../../../assets/words/a/activity.png"),
  actual: require("../../../assets/words/a/actual.png"),
  actually: require("../../../assets/words/a/actually.png"),
  adapt: require("../../../assets/words/a/adapt.png"),
  adaptability: require("../../../assets/words/a/adaptability.png"),
  adaptable: require("../../../assets/words/a/adaptable.png"),
  adaptation: require("../../../assets/words/a/adaptation.png"),
  add: require("../../../assets/words/a/add.png"),
  addict: require("../../../assets/words/a/addict.png"),
  additive: require("../../../assets/words/a/additive.png"),
  address: require("../../../assets/words/a/address.png"),
  adequate: require("../../../assets/words/a/adequate.png"),
  adhere: require("../../../assets/words/a/adhere.png"),
  adjust: require("../../../assets/words/a/adjust.png"),
  adjustment: require("../../../assets/words/a/adjustment.png"),
  administer: require("../../../assets/words/a/administer.png"),
  administered: require("../../../assets/words/a/administered.png"),
  administration: require("../../../assets/words/a/administration.png"),
  admiral: require("../../../assets/words/a/admiral.png"),
  admire: require("../../../assets/words/a/admire.png"),
  admit: require("../../../assets/words/a/admit.png"),
  adopt: require("../../../assets/words/a/adopt.png"),
  adult: require("../../../assets/words/a/adult.png"),
  advance: require("../../../assets/words/a/advance.png"),
  advancement: require("../../../assets/words/a/advancement.png"),
  advantage: require("../../../assets/words/a/advantage.png"),
  advent: require("../../../assets/words/a/advent.png"),
  adventure: require("../../../assets/words/a/adventure.png"),
  adventurous: require("../../../assets/words/a/adventurous.png"),
  adversary: require("../../../assets/words/a/adversary.png"),
  adversity: require("../../../assets/words/a/adversity.png"),
  advertise: require("../../../assets/words/a/advertise.png"),
  advice: require("../../../assets/words/a/advice.png"),
  advisor: require("../../../assets/words/a/advisor.png"),
  advocate: require("../../../assets/words/a/advocate.png"),
  affair: require("../../../assets/words/a/affair.png"),
  affect: require("../../../assets/words/a/affect.png"),
  affection: require("../../../assets/words/a/affection.png"),
  affluence: require("../../../assets/words/a/affluence.png"),
  affluent: require("../../../assets/words/a/affluent.png"),
  afford: require("../../../assets/words/a/afford.png"),
  affordable: require("../../../assets/words/a/affordable.png"),
  afraid: require("../../../assets/words/a/afraid.png"),
  "after all": require("../../../assets/words/a/after-all.png"),
  afterward: require("../../../assets/words/a/afterward.png"),
  "again and again": require("../../../assets/words/a/again-and-again.png"),
  agency: require("../../../assets/words/a/agency.png"),
  agenda: require("../../../assets/words/a/agenda.png"),
  agent: require("../../../assets/words/a/agent.png"),
  aggression: require("../../../assets/words/a/aggression.png"),
  aggressive: require("../../../assets/words/a/aggressive.png"),
  agree: require("../../../assets/words/a/agree.png"),
  agriculture: require("../../../assets/words/a/agriculture.png"),
  ahead: require("../../../assets/words/a/ahead.png"),
  aid: require("../../../assets/words/a/aid.png"),
  aim: require("../../../assets/words/a/aim.png"),
  aircraft: require("../../../assets/words/a/aircraft.png"),
  airport: require("../../../assets/words/a/airport.png"),
  aisle: require("../../../assets/words/a/aisle.png"),
  alarm: require("../../../assets/words/a/alarm.png"),
  alarming: require("../../../assets/words/a/alarming.png"),
  alert: require("../../../assets/words/a/alert.png"),
  alike: require("../../../assets/words/a/alike.png"),
  alive: require("../../../assets/words/a/alive.png"),
  alleviate: require("../../../assets/words/a/alleviate.png"),
  allocate: require("../../../assets/words/a/allocate.png"),
  allow: require("../../../assets/words/a/allow.png"),
  allowance: require("../../../assets/words/a/allowance.png"),
  ally: require("../../../assets/words/a/ally.png"),
  almost: require("../../../assets/words/a/almost.png"),
  alone: require("../../../assets/words/a/alone.png"),
  along: require("../../../assets/words/a/along.png"),
  "along with": require("../../../assets/words/a/along-with.png"),
  alphabet: require("../../../assets/words/a/alphabet.png"),
  alter: require("../../../assets/words/a/alter.png"),
  alteration: require("../../../assets/words/a/alteration.png"),
  alternate: require("../../../assets/words/a/alternate.png"),
  alternative: require("../../../assets/words/a/alternative.png"),
  although: require("../../../assets/words/a/although.png"),
  altogether: require("../../../assets/words/a/altogether.png"),
  amateur: require("../../../assets/words/a/amateur.png"),
  amazed: require("../../../assets/words/a/amazed.png"),
  amazing: require("../../../assets/words/a/amazing.png"),
  ambiguity: require("../../../assets/words/a/ambiguity.png"),
  ambiguous: require("../../../assets/words/a/ambiguous.png"),
  ambition: require("../../../assets/words/a/ambition.png"),
  ambitious: require("../../../assets/words/a/ambitious.png"),
  amenities: require("../../../assets/words/a/amenities.png"),
  amount: require("../../../assets/words/a/amount.png"),
  ample: require("../../../assets/words/a/ample.png"),
  amplify: require("../../../assets/words/a/amplify.png"),
  amuse: require("../../../assets/words/a/amuse.png"),
  "an array of": require("../../../assets/words/a/an-array-of.png"),
  analogy: require("../../../assets/words/a/analogy.png"),
  analyze: require("../../../assets/words/a/analyze.png"),
  ancestor: require("../../../assets/words/a/ancestor.png"),
  ancient: require("../../../assets/words/a/ancient.png"),
  angle: require("../../../assets/words/a/angle.png"),
  angry: require("../../../assets/words/a/angry.png"),
  ankle: require("../../../assets/words/a/ankle.png"),
  anniversary: require("../../../assets/words/a/anniversary.png"),
  announce: require("../../../assets/words/a/announce.png"),
  annoy: require("../../../assets/words/a/annoy.png"),
  annoying: require("../../../assets/words/a/annoying.png"),
  annual: require("../../../assets/words/a/annual.png"),
  answer: require("../../../assets/words/a/answer.png"),
  antecedent: require("../../../assets/words/a/antecedent.png"),
  anthropologist: require("../../../assets/words/a/anthropologist.png"),
  antibiotic: require("../../../assets/words/a/antibiotic.png"),
  anticipate: require("../../../assets/words/a/anticipate.png"),
  antique: require("../../../assets/words/a/antique.png"),
  antiquity: require("../../../assets/words/a/antiquity.png"),
  anxious: require("../../../assets/words/a/anxious.png"),
  anyway: require("../../../assets/words/a/anyway.png"),
  apart: require("../../../assets/words/a/apart.png"),
  "apart from": require("../../../assets/words/a/apart-from.png"),
  apologize: require("../../../assets/words/a/apologize.png"),
  apparent: require("../../../assets/words/a/apparent.png"),
  apparently: require("../../../assets/words/a/apparently.png"),
  appeal: require("../../../assets/words/a/appeal.png"),
  appealing: require("../../../assets/words/a/appealing.png"),
  appear: require("../../../assets/words/a/appear.png"),
  appearance: require("../../../assets/words/a/appearance.png"),
  appetite: require("../../../assets/words/a/appetite.png"),
  applaud: require("../../../assets/words/a/applaud.png"),
  appliance: require("../../../assets/words/a/appliance.png"),
  "applicable to": require("../../../assets/words/a/applicable-to.png"),
  application: require("../../../assets/words/a/application.png"),
  apply: require("../../../assets/words/a/apply.png"),
  appoint: require("../../../assets/words/a/appoint.png"),
  appointment: require("../../../assets/words/a/appointment.png"),
  appraisal: require("../../../assets/words/a/appraisal.png"),
  appreciable: require("../../../assets/words/a/appreciable.png"),
  appreciate: require("../../../assets/words/a/appreciate.png"),
  apprehend: require("../../../assets/words/a/apprehend.png"),
  approach: require("../../../assets/words/a/approach.png"),
  appropriate: require("../../../assets/words/a/appropriate.png"),
  approve: require("../../../assets/words/a/approve.png"),
  approximately: require("../../../assets/words/a/approximately.png"),
  apt: require("../../../assets/words/a/apt.png"),
  aptly: require("../../../assets/words/a/aptly.png"),
  aquarium: require("../../../assets/words/a/aquarium.png"),
  archaeologist: require("../../../assets/words/a/archaeologist.png"),
  architect: require("../../../assets/words/a/architect.png"),
  architecture: require("../../../assets/words/a/architecture.png"),
  arctic: require("../../../assets/words/a/arctic.png"),
  area: require("../../../assets/words/a/area.png"),
  argue: require("../../../assets/words/a/argue.png"),
  arise: require("../../../assets/words/a/arise.png"),
  arm: require("../../../assets/words/a/arm.png"),
  army: require("../../../assets/words/a/army.png"),
  aromatic: require("../../../assets/words/a/aromatic.png"),
  arouse: require("../../../assets/words/a/arouse.png"),
  arrange: require("../../../assets/words/a/arrange.png"),
  array: require("../../../assets/words/a/array.png"),
  arrest: require("../../../assets/words/a/arrest.png"),
  arrival: require("../../../assets/words/a/arrival.png"),
  arrive: require("../../../assets/words/a/arrive.png"),
  arrogant: require("../../../assets/words/a/arrogant.png"),
  arrow: require("../../../assets/words/a/arrow.png"),
  art: require("../../../assets/words/a/art.png"),
  artery: require("../../../assets/words/a/artery.png"),
  article: require("../../../assets/words/a/article.png"),
  artifact: require("../../../assets/words/a/artifact.png"),
  artificial: require("../../../assets/words/a/artificial.png"),
  artisan: require("../../../assets/words/a/artisan.png"),
  artwork: require("../../../assets/words/a/artwork.png"),
  "as a result": require("../../../assets/words/a/as-a-result.png"),
  "as long as": require("../../../assets/words/a/as-long-as.png"),
  "as well": require("../../../assets/words/a/as-well.png"),
  "as well as": require("../../../assets/words/a/as-well-as.png"),
  "as ~ as possible": require("../../../assets/words/a/as-~-as-possible.png"),
  ascending: require("../../../assets/words/a/ascending.png"),
  ascertain: require("../../../assets/words/a/ascertain.png"),
  "ascribe A to B": require("../../../assets/words/a/ascribe-A-to-B.png"),
  ash: require("../../../assets/words/a/ash.png"),
  ashamed: require("../../../assets/words/a/ashamed.png"),
  aside: require("../../../assets/words/a/aside.png"),
  "ask for": require("../../../assets/words/a/ask-for.png"),
  aspect: require("../../../assets/words/a/aspect.png"),
  aspiration: require("../../../assets/words/a/aspiration.png"),
  aspire: require("../../../assets/words/a/aspire.png"),
  assemble: require("../../../assets/words/a/assemble.png"),
  assembly: require("../../../assets/words/a/assembly.png"),
  assert: require("../../../assets/words/a/assert.png"),
  assertion: require("../../../assets/words/a/assertion.png"),
  assign: require("../../../assets/words/a/assign.png"),
  assignment: require("../../../assets/words/a/assignment.png"),
  assist: require("../../../assets/words/a/assist.png"),
  associate: require("../../../assets/words/a/associate.png"),
  associated: require("../../../assets/words/a/associated.png"),
  assortment: require("../../../assets/words/a/assortment.png"),
  assume: require("../../../assets/words/a/assume.png"),
  assumption: require("../../../assets/words/a/assumption.png"),
  assure: require("../../../assets/words/a/assure.png"),
  assuredly: require("../../../assets/words/a/assuredly.png"),
  asthma: require("../../../assets/words/a/asthma.png"),
  astonish: require("../../../assets/words/a/astonish.png"),
  astonishing: require("../../../assets/words/a/astonishing.png"),
  astronaut: require("../../../assets/words/a/astronaut.png"),
  "at hand": require("../../../assets/words/a/at-hand.png"),
  "at last": require("../../../assets/words/a/at-last.png"),
  "at least": require("../../../assets/words/a/at-least.png"),
  "at once": require("../../../assets/words/a/at-once.png"),
  "at the expense of": require("../../../assets/words/a/at-the-expense-of.png"),
  "at the same time": require("../../../assets/words/a/at-the-same-time.png"),
  athlete: require("../../../assets/words/a/athlete.png"),
  atmosphere: require("../../../assets/words/a/atmosphere.png"),
  atom: require("../../../assets/words/a/atom.png"),
  attach: require("../../../assets/words/a/attach.png"),
  "attachment to": require("../../../assets/words/a/attachment-to.png"),
  attain: require("../../../assets/words/a/attain.png"),
  attempt: require("../../../assets/words/a/attempt.png"),
  attend: require("../../../assets/words/a/attend.png"),
  attendant: require("../../../assets/words/a/attendant.png"),
  attention: require("../../../assets/words/a/attention.png"),
  attentive: require("../../../assets/words/a/attentive.png"),
  attire: require("../../../assets/words/a/attire.png"),
  attitude: require("../../../assets/words/a/attitude.png"),
  attract: require("../../../assets/words/a/attract.png"),
  attractive: require("../../../assets/words/a/attractive.png"),
  attribute: require("../../../assets/words/a/attribute.png"),
  auction: require("../../../assets/words/a/auction.png"),
  audience: require("../../../assets/words/a/audience.png"),
  auditorium: require("../../../assets/words/a/auditorium.png"),
  authenticity: require("../../../assets/words/a/authenticity.png"),
  author: require("../../../assets/words/a/author.png"),
  authority: require("../../../assets/words/a/authority.png"),
  authorize: require("../../../assets/words/a/authorize.png"),
  autograph: require("../../../assets/words/a/autograph.png"),
  automatic: require("../../../assets/words/a/automatic.png"),
  automatically: require("../../../assets/words/a/automatically.png"),
  automobile: require("../../../assets/words/a/automobile.png"),
  available: require("../../../assets/words/a/available.png"),
  avenue: require("../../../assets/words/a/avenue.png"),
  average: require("../../../assets/words/a/average.png"),
  avoid: require("../../../assets/words/a/avoid.png"),
  awake: require("../../../assets/words/a/awake.png"),
  awaken: require("../../../assets/words/a/awaken.png"),
  award: require("../../../assets/words/a/award.png"),
  aware: require("../../../assets/words/a/aware.png"),
  awareness: require("../../../assets/words/a/awareness.png"),
  awkward: require("../../../assets/words/a/awkward.png"),
};
