import { ImageSourcePropType } from "react-native";

// "a" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_A: Record<string, ImageSourcePropType> = {
  "a great deal": require("../../../assets/words/a/a-great-deal.png"),
  "a host of": require("../../../assets/words/a/a-host-of.png"),
  "a quarter": require("../../../assets/words/a/a-quarter.png"),
  "a wide range of": require("../../../assets/words/a/a-wide-range-of.png"),
  abandon: require("../../../assets/words/a/abandon.png"),
  able: require("../../../assets/words/a/able.png"),
  abnormally: require("../../../assets/words/a/abnormally.png"),
  abolish: require("../../../assets/words/a/abolish.png"),
  "abound in": require("../../../assets/words/a/abound-in.png"),
  abroad: require("../../../assets/words/a/abroad.png"),
  abrupt: require("../../../assets/words/a/abrupt.png"),
  absent: require("../../../assets/words/a/absent.png"),
  absolute: require("../../../assets/words/a/absolute.png"),
  absorb: require("../../../assets/words/a/absorb.png"),
  abstract: require("../../../assets/words/a/abstract.png"),
  abundance: require("../../../assets/words/a/abundance.png"),
  abundant: require("../../../assets/words/a/abundant.png"),
  abuse: require("../../../assets/words/a/abuse.png"),
  academic: require("../../../assets/words/a/academic.png"),
  "accede with": require("../../../assets/words/a/accede-with.png"),
  accelerate: require("../../../assets/words/a/accelerate.png"),
  accept: require("../../../assets/words/a/accept.png"),
  accessible: require("../../../assets/words/a/accessible.png"),
  accident: require("../../../assets/words/a/accident.png"),
  accidentally: require("../../../assets/words/a/accidentally.png"),
  accommodate: require("../../../assets/words/a/accommodate.png"),
  accommodation: require("../../../assets/words/a/accommodation.png"),
  "accompanied by": require("../../../assets/words/a/accompanied-by.png"),
  accompany: require("../../../assets/words/a/accompany.png"),
  accomplish: require("../../../assets/words/a/accomplish.png"),
  accomplished: require("../../../assets/words/a/accomplished.png"),
  accord: require("../../../assets/words/a/accord.png"),
  "according to": require("../../../assets/words/a/according-to.png"),
  account: require("../../../assets/words/a/account.png"),
  "account for": require("../../../assets/words/a/account-for.png"),
  accumulate: require("../../../assets/words/a/accumulate.png"),
  accuracy: require("../../../assets/words/a/accuracy.png"),
  accurate: require("../../../assets/words/a/accurate.png"),
  "accustomed to": require("../../../assets/words/a/accustomed-to.png"),
  ache: require("../../../assets/words/a/ache.png"),
  achieve: require("../../../assets/words/a/achieve.png"),
  acquire: require("../../../assets/words/a/acquire.png"),
  acquisition: require("../../../assets/words/a/acquisition.png"),
  active: require("../../../assets/words/a/active.png"),
  activity: require("../../../assets/words/a/activity.png"),
  actually: require("../../../assets/words/a/actually.png"),
  adapt: require("../../../assets/words/a/adapt.png"),
  adaptability: require("../../../assets/words/a/adaptability.png"),
  adaptation: require("../../../assets/words/a/adaptation.png"),
  add: require("../../../assets/words/a/add.png"),
  additive: require("../../../assets/words/a/additive.png"),
  address: require("../../../assets/words/a/address.png"),
  adequate: require("../../../assets/words/a/adequate.png"),
  adjust: require("../../../assets/words/a/adjust.png"),
  administered: require("../../../assets/words/a/administered.png"),
  admiral: require("../../../assets/words/a/admiral.png"),
  admire: require("../../../assets/words/a/admire.png"),
  admit: require("../../../assets/words/a/admit.png"),
  adopt: require("../../../assets/words/a/adopt.png"),
  adult: require("../../../assets/words/a/adult.png"),
  advance: require("../../../assets/words/a/advance.png"),
  advancement: require("../../../assets/words/a/advancement.png"),
  advent: require("../../../assets/words/a/advent.png"),
  adventure: require("../../../assets/words/a/adventure.png"),
  adversary: require("../../../assets/words/a/adversary.png"),
  advice: require("../../../assets/words/a/advice.png"),
  advisor: require("../../../assets/words/a/advisor.png"),
  advocate: require("../../../assets/words/a/advocate.png"),
  affair: require("../../../assets/words/a/affair.png"),
  affection: require("../../../assets/words/a/affection.png"),
  affluence: require("../../../assets/words/a/affluence.png"),
  affluent: require("../../../assets/words/a/affluent.png"),
  afford: require("../../../assets/words/a/afford.png"),
  afraid: require("../../../assets/words/a/afraid.png"),
  afterward: require("../../../assets/words/a/afterward.png"),
  agent: require("../../../assets/words/a/agent.png"),
  aggression: require("../../../assets/words/a/aggression.png"),
  agree: require("../../../assets/words/a/agree.png"),
  agriculture: require("../../../assets/words/a/agriculture.png"),
  ahead: require("../../../assets/words/a/ahead.png"),
  aid: require("../../../assets/words/a/aid.png"),
  aim: require("../../../assets/words/a/aim.png"),
  airport: require("../../../assets/words/a/airport.png"),
  alarm: require("../../../assets/words/a/alarm.png"),
  alarming: require("../../../assets/words/a/alarming.png"),
  alive: require("../../../assets/words/a/alive.png"),
  allocate: require("../../../assets/words/a/allocate.png"),
  allow: require("../../../assets/words/a/allow.png"),
  almost: require("../../../assets/words/a/almost.png"),
  alone: require("../../../assets/words/a/alone.png"),
  along: require("../../../assets/words/a/along.png"),
  alphabet: require("../../../assets/words/a/alphabet.png"),
  alter: require("../../../assets/words/a/alter.png"),
  alteration: require("../../../assets/words/a/alteration.png"),
  alternate: require("../../../assets/words/a/alternate.png"),
  alternative: require("../../../assets/words/a/alternative.png"),
  although: require("../../../assets/words/a/although.png"),
  altogether: require("../../../assets/words/a/altogether.png"),
  amateur: require("../../../assets/words/a/amateur.png"),
  amazing: require("../../../assets/words/a/amazing.png"),
  ambiguous: require("../../../assets/words/a/ambiguous.png"),
  ambition: require("../../../assets/words/a/ambition.png"),
  amount: require("../../../assets/words/a/amount.png"),
  ample: require("../../../assets/words/a/ample.png"),
  amplify: require("../../../assets/words/a/amplify.png"),
  amuse: require("../../../assets/words/a/amuse.png"),
  "an array of": require("../../../assets/words/a/an-array-of.png"),
  ancestor: require("../../../assets/words/a/ancestor.png"),
  ancient: require("../../../assets/words/a/ancient.png"),
  angle: require("../../../assets/words/a/angle.png"),
  angry: require("../../../assets/words/a/angry.png"),
  annoying: require("../../../assets/words/a/annoying.png"),
  annual: require("../../../assets/words/a/annual.png"),
  answer: require("../../../assets/words/a/answer.png"),
  antecedent: require("../../../assets/words/a/antecedent.png"),
  anthropologist: require("../../../assets/words/a/anthropologist.png"),
  anticipate: require("../../../assets/words/a/anticipate.png"),
  antique: require("../../../assets/words/a/antique.png"),
  antiquity: require("../../../assets/words/a/antiquity.png"),
  anxious: require("../../../assets/words/a/anxious.png"),
  anyway: require("../../../assets/words/a/anyway.png"),
  apart: require("../../../assets/words/a/apart.png"),
  "apart from": require("../../../assets/words/a/apart-from.png"),
  apparent: require("../../../assets/words/a/apparent.png"),
  apparently: require("../../../assets/words/a/apparently.png"),
  appeal: require("../../../assets/words/a/appeal.png"),
  appealing: require("../../../assets/words/a/appealing.png"),
  appear: require("../../../assets/words/a/appear.png"),
  appetite: require("../../../assets/words/a/appetite.png"),
  "applicable to": require("../../../assets/words/a/applicable-to.png"),
  application: require("../../../assets/words/a/application.png"),
  appointment: require("../../../assets/words/a/appointment.png"),
  appreciable: require("../../../assets/words/a/appreciable.png"),
  appreciate: require("../../../assets/words/a/appreciate.png"),
  apprehend: require("../../../assets/words/a/apprehend.png"),
  approach: require("../../../assets/words/a/approach.png"),
  appropriate: require("../../../assets/words/a/appropriate.png"),
  approximately: require("../../../assets/words/a/approximately.png"),
  apt: require("../../../assets/words/a/apt.png"),
  aptly: require("../../../assets/words/a/aptly.png"),
  archaeologist: require("../../../assets/words/a/archaeologist.png"),
  area: require("../../../assets/words/a/area.png"),
  argue: require("../../../assets/words/a/argue.png"),
  arise: require("../../../assets/words/a/arise.png"),
  army: require("../../../assets/words/a/army.png"),
  aromatic: require("../../../assets/words/a/aromatic.png"),
  arouse: require("../../../assets/words/a/arouse.png"),
  arrange: require("../../../assets/words/a/arrange.png"),
  array: require("../../../assets/words/a/array.png"),
  arrest: require("../../../assets/words/a/arrest.png"),
  arrive: require("../../../assets/words/a/arrive.png"),
  arrogant: require("../../../assets/words/a/arrogant.png"),
  art: require("../../../assets/words/a/art.png"),
  article: require("../../../assets/words/a/article.png"),
  artifact: require("../../../assets/words/a/artifact.png"),
  artificial: require("../../../assets/words/a/artificial.png"),
  artisan: require("../../../assets/words/a/artisan.png"),
  artwork: require("../../../assets/words/a/artwork.png"),
  "as a result": require("../../../assets/words/a/as-a-result.png"),
  "as well": require("../../../assets/words/a/as-well.png"),
  "as well as": require("../../../assets/words/a/as-well-as.png"),
  ascending: require("../../../assets/words/a/ascending.png"),
  ascertain: require("../../../assets/words/a/ascertain.png"),
  "ascribe A to B": require("../../../assets/words/a/ascribe-A-to-B.png"),
  aspect: require("../../../assets/words/a/aspect.png"),
  aspiration: require("../../../assets/words/a/aspiration.png"),
  assemble: require("../../../assets/words/a/assemble.png"),
  assert: require("../../../assets/words/a/assert.png"),
  assertion: require("../../../assets/words/a/assertion.png"),
  assign: require("../../../assets/words/a/assign.png"),
  assist: require("../../../assets/words/a/assist.png"),
  associate: require("../../../assets/words/a/associate.png"),
  associated: require("../../../assets/words/a/associated.png"),
  assortment: require("../../../assets/words/a/assortment.png"),
  assume: require("../../../assets/words/a/assume.png"),
  assumption: require("../../../assets/words/a/assumption.png"),
  assuredly: require("../../../assets/words/a/assuredly.png"),
  astonish: require("../../../assets/words/a/astonish.png"),
  astonishing: require("../../../assets/words/a/astonishing.png"),
  "at hand": require("../../../assets/words/a/at-hand.png"),
  "at least": require("../../../assets/words/a/at-least.png"),
  "at once": require("../../../assets/words/a/at-once.png"),
  "at the expense of": require("../../../assets/words/a/at-the-expense-of.png"),
  "at the same time": require("../../../assets/words/a/at-the-same-time.png"),
  athlete: require("../../../assets/words/a/athlete.png"),
  atmosphere: require("../../../assets/words/a/atmosphere.png"),
  atom: require("../../../assets/words/a/atom.png"),
  attach: require("../../../assets/words/a/attach.png"),
  "attachment to": require("../../../assets/words/a/attachment-to.png"),
  attain: require("../../../assets/words/a/attain.png"),
  attempt: require("../../../assets/words/a/attempt.png"),
  attend: require("../../../assets/words/a/attend.png"),
  attendant: require("../../../assets/words/a/attendant.png"),
  attract: require("../../../assets/words/a/attract.png"),
  attribute: require("../../../assets/words/a/attribute.png"),
  authenticity: require("../../../assets/words/a/authenticity.png"),
  authorize: require("../../../assets/words/a/authorize.png"),
  available: require("../../../assets/words/a/available.png"),
  avoid: require("../../../assets/words/a/avoid.png"),
  award: require("../../../assets/words/a/award.png"),
};
