import { ImageSourcePropType } from "react-native";

// "b" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_B: Record<string, ImageSourcePropType> = {
  "B as well as A": require("../../../assets/words/b/B-as-well-as-A.png"),
  "back and forth": require("../../../assets/words/b/back-and-forth.png"),
  backbone: require("../../../assets/words/b/backbone.png"),
  backfire: require("../../../assets/words/b/backfire.png"),
  background: require("../../../assets/words/b/background.png"),
  badly: require("../../../assets/words/b/badly.png"),
  bag: require("../../../assets/words/b/bag.png"),
  baggage: require("../../../assets/words/b/baggage.png"),
  balance: require("../../../assets/words/b/balance.png"),
  bald: require("../../../assets/words/b/bald.png"),
  balloon: require("../../../assets/words/b/balloon.png"),
  ballroom: require("../../../assets/words/b/ballroom.png"),
  ban: require("../../../assets/words/b/ban.png"),
  band: require("../../../assets/words/b/band.png"),
  bank: require("../../../assets/words/b/bank.png"),
  bankrupt: require("../../../assets/words/b/bankrupt.png"),
  banquet: require("../../../assets/words/b/banquet.png"),
  bar: require("../../../assets/words/b/bar.png"),
  barbarous: require("../../../assets/words/b/barbarous.png"),
  barbershop: require("../../../assets/words/b/barbershop.png"),
  bare: require("../../../assets/words/b/bare.png"),
  barely: require("../../../assets/words/b/barely.png"),
  bargain: require("../../../assets/words/b/bargain.png"),
  bark: require("../../../assets/words/b/bark.png"),
  barren: require("../../../assets/words/b/barren.png"),
  barrier: require("../../../assets/words/b/barrier.png"),
  barter: require("../../../assets/words/b/barter.png"),
  base: require("../../../assets/words/b/base.png"),
  basement: require("../../../assets/words/b/basement.png"),
  basis: require("../../../assets/words/b/basis.png"),
  bass: require("../../../assets/words/b/bass.png"),
  bath: require("../../../assets/words/b/bath.png"),
  bathroom: require("../../../assets/words/b/bathroom.png"),
  batter: require("../../../assets/words/b/batter.png"),
  battle: require("../../../assets/words/b/battle.png"),
  bay: require("../../../assets/words/b/bay.png"),
  "be about to": require("../../../assets/words/b/be-about-to.png"),
  "be accustomed to": require("../../../assets/words/b/be-accustomed-to.png"),
  "be afraid of": require("../../../assets/words/b/be-afraid-of.png"),
  "be based on": require("../../../assets/words/b/be-based-on.png"),
  "be born": require("../../../assets/words/b/be-born.png"),
  "be bound to": require("../../../assets/words/b/be-bound-to.png"),
  "be capable of": require("../../../assets/words/b/be-capable-of.png"),
  "be characterized by": require("../../../assets/words/b/be-characterized-by.png"),
  "be considered": require("../../../assets/words/b/be-considered.png"),
  "be derived from": require("../../../assets/words/b/be-derived-from.png"),
  "be fond of": require("../../../assets/words/b/be-fond-of.png"),
  "be known as": require("../../../assets/words/b/be-known-as.png"),
  "be late": require("../../../assets/words/b/be-late.png"),
  "be likely to": require("../../../assets/words/b/be-likely-to.png"),
  "be marked": require("../../../assets/words/b/be-marked.png"),
  "be supposed to": require("../../../assets/words/b/be-supposed-to.png"),
  "be used to": require("../../../assets/words/b/be-used-to.png"),
  "be worthy of": require("../../../assets/words/b/be-worthy-of.png"),
  beach: require("../../../assets/words/b/beach.png"),
  beam: require("../../../assets/words/b/beam.png"),
  bean: require("../../../assets/words/b/bean.png"),
  bear: require("../../../assets/words/b/bear.png"),
  "bear in mind": require("../../../assets/words/b/bear-in-mind.png"),
  beard: require("../../../assets/words/b/beard.png"),
  bearer: require("../../../assets/words/b/bearer.png"),
  beast: require("../../../assets/words/b/beast.png"),
  beat: require("../../../assets/words/b/beat.png"),
  beauty: require("../../../assets/words/b/beauty.png"),
  become: require("../../../assets/words/b/become.png"),
  bed: require("../../../assets/words/b/bed.png"),
  bedside: require("../../../assets/words/b/bedside.png"),
  beef: require("../../../assets/words/b/beef.png"),
  beer: require("../../../assets/words/b/beer.png"),
  "before long": require("../../../assets/words/b/before-long.png"),
  beforehand: require("../../../assets/words/b/beforehand.png"),
  beg: require("../../../assets/words/b/beg.png"),
  beggar: require("../../../assets/words/b/beggar.png"),
  begin: require("../../../assets/words/b/begin.png"),
  behalf: require("../../../assets/words/b/behalf.png"),
  behave: require("../../../assets/words/b/behave.png"),
  behavior: require("../../../assets/words/b/behavior.png"),
  behind: require("../../../assets/words/b/behind.png"),
  behold: require("../../../assets/words/b/behold.png"),
  beings: require("../../../assets/words/b/beings.png"),
  belief: require("../../../assets/words/b/belief.png"),
  believe: require("../../../assets/words/b/believe.png"),
  belly: require("../../../assets/words/b/belly.png"),
  belong: require("../../../assets/words/b/belong.png"),
  "belong to": require("../../../assets/words/b/belong-to.png"),
  below: require("../../../assets/words/b/below.png"),
  belt: require("../../../assets/words/b/belt.png"),
  bend: require("../../../assets/words/b/bend.png"),
  beneath: require("../../../assets/words/b/beneath.png"),
  benediction: require("../../../assets/words/b/benediction.png"),
  beneficial: require("../../../assets/words/b/beneficial.png"),
  benefit: require("../../../assets/words/b/benefit.png"),
  benevolent: require("../../../assets/words/b/benevolent.png"),
  beside: require("../../../assets/words/b/beside.png"),
  besides: require("../../../assets/words/b/besides.png"),
  "best fit": require("../../../assets/words/b/best-fit.png"),
  bet: require("../../../assets/words/b/bet.png"),
  beverage: require("../../../assets/words/b/beverage.png"),
  bewilder: require("../../../assets/words/b/bewilder.png"),
  beyond: require("../../../assets/words/b/beyond.png"),
  bias: require("../../../assets/words/b/bias.png"),
  bicycle: require("../../../assets/words/b/bicycle.png"),
  bid: require("../../../assets/words/b/bid.png"),
  big: require("../../../assets/words/b/big.png"),
  bike: require("../../../assets/words/b/bike.png"),
  bilateral: require("../../../assets/words/b/bilateral.png"),
  bilingual: require("../../../assets/words/b/bilingual.png"),
  bill: require("../../../assets/words/b/bill.png"),
  billion: require("../../../assets/words/b/billion.png"),
  bin: require("../../../assets/words/b/bin.png"),
  bind: require("../../../assets/words/b/bind.png"),
  biodiversity: require("../../../assets/words/b/biodiversity.png"),
  biography: require("../../../assets/words/b/biography.png"),
  biological: require("../../../assets/words/b/biological.png"),
  biology: require("../../../assets/words/b/biology.png"),
  bird: require("../../../assets/words/b/bird.png"),
  birth: require("../../../assets/words/b/birth.png"),
  birthday: require("../../../assets/words/b/birthday.png"),
  bit: require("../../../assets/words/b/bit.png"),
  bite: require("../../../assets/words/b/bite.png"),
  bitter: require("../../../assets/words/b/bitter.png"),
  "black color": require("../../../assets/words/b/black-color.png"),
  "black tea": require("../../../assets/words/b/black-tea.png"),
  blame: require("../../../assets/words/b/blame.png"),
  blank: require("../../../assets/words/b/blank.png"),
  blanket: require("../../../assets/words/b/blanket.png"),
  blast: require("../../../assets/words/b/blast.png"),
  bleed: require("../../../assets/words/b/bleed.png"),
  blend: require("../../../assets/words/b/blend.png"),
  bless: require("../../../assets/words/b/bless.png"),
  blimp: require("../../../assets/words/b/blimp.png"),
  blind: require("../../../assets/words/b/blind.png"),
  blink: require("../../../assets/words/b/blink.png"),
  block: require("../../../assets/words/b/block.png"),
  blood: require("../../../assets/words/b/blood.png"),
  bloom: require("../../../assets/words/b/bloom.png"),
  blossom: require("../../../assets/words/b/blossom.png"),
  blow: require("../../../assets/words/b/blow.png"),
  "blue color": require("../../../assets/words/b/blue-color.png"),
  "blue-chip": require("../../../assets/words/b/blue-chip.png"),
  blueprint: require("../../../assets/words/b/blueprint.png"),
  blur: require("../../../assets/words/b/blur.png"),
  board: require("../../../assets/words/b/board.png"),
  boardroom: require("../../../assets/words/b/boardroom.png"),
  boast: require("../../../assets/words/b/boast.png"),
  body: require("../../../assets/words/b/body.png"),
  bold: require("../../../assets/words/b/bold.png"),
  bomb: require("../../../assets/words/b/bomb.png"),
  bonanza: require("../../../assets/words/b/bonanza.png"),
  bond: require("../../../assets/words/b/bond.png"),
  bone: require("../../../assets/words/b/bone.png"),
  book: require("../../../assets/words/b/book.png"),
  bookstore: require("../../../assets/words/b/bookstore.png"),
  boom: require("../../../assets/words/b/boom.png"),
  boost: require("../../../assets/words/b/boost.png"),
  booth: require("../../../assets/words/b/booth.png"),
  border: require("../../../assets/words/b/border.png"),
  boring: require("../../../assets/words/b/boring.png"),
  borrow: require("../../../assets/words/b/borrow.png"),
  botanical: require("../../../assets/words/b/botanical.png"),
  bother: require("../../../assets/words/b/bother.png"),
  bothersome: require("../../../assets/words/b/bothersome.png"),
  bottle: require("../../../assets/words/b/bottle.png"),
  bottom: require("../../../assets/words/b/bottom.png"),
  bounce: require("../../../assets/words/b/bounce.png"),
  bound: require("../../../assets/words/b/bound.png"),
  boundary: require("../../../assets/words/b/boundary.png"),
  bow: require("../../../assets/words/b/bow.png"),
  bowl: require("../../../assets/words/b/bowl.png"),
  box: require("../../../assets/words/b/box.png"),
  brag: require("../../../assets/words/b/brag.png"),
  brain: require("../../../assets/words/b/brain.png"),
  brake: require("../../../assets/words/b/brake.png"),
  branch: require("../../../assets/words/b/branch.png"),
  bread: require("../../../assets/words/b/bread.png"),
  break: require("../../../assets/words/b/break.png"),
  "break down": require("../../../assets/words/b/break-down.png"),
  "break out": require("../../../assets/words/b/break-out.png"),
  "break with": require("../../../assets/words/b/break-with.png"),
  breakable: require("../../../assets/words/b/breakable.png"),
  breakdown: require("../../../assets/words/b/breakdown.png"),
  breakthrough: require("../../../assets/words/b/breakthrough.png"),
  breathe: require("../../../assets/words/b/breathe.png"),
  breathing: require("../../../assets/words/b/breathing.png"),
  breathtaking: require("../../../assets/words/b/breathtaking.png"),
  breathtakingly: require("../../../assets/words/b/breathtakingly.png"),
  breed: require("../../../assets/words/b/breed.png"),
  brevity: require("../../../assets/words/b/brevity.png"),
  bribe: require("../../../assets/words/b/bribe.png"),
  bribery: require("../../../assets/words/b/bribery.png"),
  bridge: require("../../../assets/words/b/bridge.png"),
  brief: require("../../../assets/words/b/brief.png"),
  briefcase: require("../../../assets/words/b/briefcase.png"),
  briefly: require("../../../assets/words/b/briefly.png"),
  bright: require("../../../assets/words/b/bright.png"),
  brightness: require("../../../assets/words/b/brightness.png"),
  brilliance: require("../../../assets/words/b/brilliance.png"),
  brilliant: require("../../../assets/words/b/brilliant.png"),
  brilliantly: require("../../../assets/words/b/brilliantly.png"),
  bring: require("../../../assets/words/b/bring.png"),
  "bring about": require("../../../assets/words/b/bring-about.png"),
  "bring back": require("../../../assets/words/b/bring-back.png"),
  british: require("../../../assets/words/b/british.png"),
  broad: require("../../../assets/words/b/broad.png"),
  broadband: require("../../../assets/words/b/broadband.png"),
  broadcast: require("../../../assets/words/b/broadcast.png"),
  broadcasting: require("../../../assets/words/b/broadcasting.png"),
  broaden: require("../../../assets/words/b/broaden.png"),
  brochure: require("../../../assets/words/b/brochure.png"),
  broom: require("../../../assets/words/b/broom.png"),
  brown: require("../../../assets/words/b/brown.png"),
  browse: require("../../../assets/words/b/browse.png"),
  bruise: require("../../../assets/words/b/bruise.png"),
  brutal: require("../../../assets/words/b/brutal.png"),
  brutality: require("../../../assets/words/b/brutality.png"),
  bubble: require("../../../assets/words/b/bubble.png"),
  buckle: require("../../../assets/words/b/buckle.png"),
  bud: require("../../../assets/words/b/bud.png"),
  budget: require("../../../assets/words/b/budget.png"),
  build: require("../../../assets/words/b/build.png"),
  "built-in": require("../../../assets/words/b/built-in.png"),
  bulk: require("../../../assets/words/b/bulk.png"),
  bullet: require("../../../assets/words/b/bullet.png"),
  bully: require("../../../assets/words/b/bully.png"),
  bump: require("../../../assets/words/b/bump.png"),
  bumpy: require("../../../assets/words/b/bumpy.png"),
  bunch: require("../../../assets/words/b/bunch.png"),
  burden: require("../../../assets/words/b/burden.png"),
  bureau: require("../../../assets/words/b/bureau.png"),
  burglar: require("../../../assets/words/b/burglar.png"),
  burn: require("../../../assets/words/b/burn.png"),
  burrow: require("../../../assets/words/b/burrow.png"),
  burst: require("../../../assets/words/b/burst.png"),
  bury: require("../../../assets/words/b/bury.png"),
  bush: require("../../../assets/words/b/bush.png"),
  business: require("../../../assets/words/b/business.png"),
  busy: require("../../../assets/words/b/busy.png"),
  butterfly: require("../../../assets/words/b/butterfly.png"),
  buy: require("../../../assets/words/b/buy.png"),
  buyout: require("../../../assets/words/b/buyout.png"),
  "by chance": require("../../../assets/words/b/by-chance.png"),
  "by oneself": require("../../../assets/words/b/by-oneself.png"),
  bystander: require("../../../assets/words/b/bystander.png"),
};
