import { ImageSourcePropType } from "react-native";

// "d" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_D: Record<string, ImageSourcePropType> = {
  damage: require("../../../assets/words/d/damage.png"),
  danger: require("../../../assets/words/d/danger.png"),
  dark: require("../../../assets/words/d/dark.png"),
  data: require("../../../assets/words/d/data.png"),
  date: require("../../../assets/words/d/date.png"),
  daughter: require("../../../assets/words/d/daughter.png"),
  dawn: require("../../../assets/words/d/dawn.png"),
  deadly: require("../../../assets/words/d/deadly.png"),
  deal: require("../../../assets/words/d/deal.png"),
  dear: require("../../../assets/words/d/dear.png"),
  death: require("../../../assets/words/d/death.png"),
  debt: require("../../../assets/words/d/debt.png"),
  deceive: require("../../../assets/words/d/deceive.png"),
  decide: require("../../../assets/words/d/decide.png"),
  deck: require("../../../assets/words/d/deck.png"),
  declare: require("../../../assets/words/d/declare.png"),
  decline: require("../../../assets/words/d/decline.png"),
  decorate: require("../../../assets/words/d/decorate.png"),
  decrease: require("../../../assets/words/d/decrease.png"),
  deep: require("../../../assets/words/d/deep.png"),
  deer: require("../../../assets/words/d/deer.png"),
  defeat: require("../../../assets/words/d/defeat.png"),
  definitely: require("../../../assets/words/d/definitely.png"),
  degrade: require("../../../assets/words/d/degrade.png"),
  degree: require("../../../assets/words/d/degree.png"),
  delicious: require("../../../assets/words/d/delicious.png"),
  delight: require("../../../assets/words/d/delight.png"),
  delighted: require("../../../assets/words/d/delighted.png"),
  deliver: require("../../../assets/words/d/deliver.png"),
  demand: require("../../../assets/words/d/demand.png"),
  democracy: require("../../../assets/words/d/democracy.png"),
  department: require("../../../assets/words/d/department.png"),
  depend: require("../../../assets/words/d/depend.png"),
  depressed: require("../../../assets/words/d/depressed.png"),
  deprived: require("../../../assets/words/d/deprived.png"),
  describe: require("../../../assets/words/d/describe.png"),
  desert: require("../../../assets/words/d/desert.png"),
  deserve: require("../../../assets/words/d/deserve.png"),
  design: require("../../../assets/words/d/design.png"),
  destroy: require("../../../assets/words/d/destroy.png"),
  detective: require("../../../assets/words/d/detective.png"),
  develop: require("../../../assets/words/d/develop.png"),
  devil: require("../../../assets/words/d/devil.png"),
  diagnose: require("../../../assets/words/d/diagnose.png"),
  dialogue: require("../../../assets/words/d/dialogue.png"),
  "dialogue between north and south": require("../../../assets/words/d/dialogue-between-north-and-south.png"),
  diary: require("../../../assets/words/d/diary.png"),
  dictionary: require("../../../assets/words/d/dictionary.png"),
  "die of": require("../../../assets/words/d/die-of.png"),
  different: require("../../../assets/words/d/different.png"),
  difficult: require("../../../assets/words/d/difficult.png"),
  dig: require("../../../assets/words/d/dig.png"),
  diligent: require("../../../assets/words/d/diligent.png"),
  "dining room": require("../../../assets/words/d/dining-room.png"),
  "dinning room": require("../../../assets/words/d/dinning-room.png"),
  direction: require("../../../assets/words/d/direction.png"),
  dirty: require("../../../assets/words/d/dirty.png"),
  disappear: require("../../../assets/words/d/disappear.png"),
  disappoint: require("../../../assets/words/d/disappoint.png"),
  disappointed: require("../../../assets/words/d/disappointed.png"),
  discuss: require("../../../assets/words/d/discuss.png"),
  dish: require("../../../assets/words/d/dish.png"),
  dispose: require("../../../assets/words/d/dispose.png"),
  distribute: require("../../../assets/words/d/distribute.png"),
  ditch: require("../../../assets/words/d/ditch.png"),
  dive: require("../../../assets/words/d/dive.png"),
  document: require("../../../assets/words/d/document.png"),
  doll: require("../../../assets/words/d/doll.png"),
  dollar: require("../../../assets/words/d/dollar.png"),
  domestic: require("../../../assets/words/d/domestic.png"),
  dominate: require("../../../assets/words/d/dominate.png"),
  downtown: require("../../../assets/words/d/downtown.png"),
  drag: require("../../../assets/words/d/drag.png"),
  draw: require("../../../assets/words/d/draw.png"),
  dream: require("../../../assets/words/d/dream.png"),
  drop: require("../../../assets/words/d/drop.png"),
  "drop out": require("../../../assets/words/d/drop-out.png"),
  drown: require("../../../assets/words/d/drown.png"),
  drugstore: require("../../../assets/words/d/drugstore.png"),
  drum: require("../../../assets/words/d/drum.png"),
  dry: require("../../../assets/words/d/dry.png"),
  dull: require("../../../assets/words/d/dull.png"),
  dumb: require("../../../assets/words/d/dumb.png"),
  dye: require("../../../assets/words/d/dye.png"),
  dynasty: require("../../../assets/words/d/dynasty.png"),
};
