import { ImageSourcePropType } from "react-native";

// "f" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_F: Record<string, ImageSourcePropType> = {
  fable: require("../../../assets/words/f/fable.png"),
  fabric: require("../../../assets/words/f/fabric.png"),
  face: require("../../../assets/words/f/face.png"),
  facial: require("../../../assets/words/f/facial.png"),
  facility: require("../../../assets/words/f/facility.png"),
  fact: require("../../../assets/words/f/fact.png"),
  factor: require("../../../assets/words/f/factor.png"),
  factory: require("../../../assets/words/f/factory.png"),
  fade: require("../../../assets/words/f/fade.png"),
  "fade away": require("../../../assets/words/f/fade-away.png"),
  fail: require("../../../assets/words/f/fail.png"),
  faint: require("../../../assets/words/f/faint.png"),
  fair: require("../../../assets/words/f/fair.png"),
  fairly: require("../../../assets/words/f/fairly.png"),
  fairy: require("../../../assets/words/f/fairy.png"),
  faith: require("../../../assets/words/f/faith.png"),
  faithful: require("../../../assets/words/f/faithful.png"),
  fake: require("../../../assets/words/f/fake.png"),
  "fall off": require("../../../assets/words/f/fall-off.png"),
  false: require("../../../assets/words/f/false.png"),
  fame: require("../../../assets/words/f/fame.png"),
  familiar: require("../../../assets/words/f/familiar.png"),
  famine: require("../../../assets/words/f/famine.png"),
  famous: require("../../../assets/words/f/famous.png"),
  fancy: require("../../../assets/words/f/fancy.png"),
  fantastic: require("../../../assets/words/f/fantastic.png"),
  far: require("../../../assets/words/f/far.png"),
  "far-reaching": require("../../../assets/words/f/far-reaching.png"),
  fare: require("../../../assets/words/f/fare.png"),
  fascinate: require("../../../assets/words/f/fascinate.png"),
  fashion: require("../../../assets/words/f/fashion.png"),
  fashionable: require("../../../assets/words/f/fashionable.png"),
  fasten: require("../../../assets/words/f/fasten.png"),
  fat: require("../../../assets/words/f/fat.png"),
  fatal: require("../../../assets/words/f/fatal.png"),
  fate: require("../../../assets/words/f/fate.png"),
  fatigue: require("../../../assets/words/f/fatigue.png"),
  faucet: require("../../../assets/words/f/faucet.png"),
  fault: require("../../../assets/words/f/fault.png"),
  favor: require("../../../assets/words/f/favor.png"),
  favorite: require("../../../assets/words/f/favorite.png"),
  fear: require("../../../assets/words/f/fear.png"),
  feast: require("../../../assets/words/f/feast.png"),
  feather: require("../../../assets/words/f/feather.png"),
  feature: require("../../../assets/words/f/feature.png"),
  federal: require("../../../assets/words/f/federal.png"),
  fee: require("../../../assets/words/f/fee.png"),
  feed: require("../../../assets/words/f/feed.png"),
  fence: require("../../../assets/words/f/fence.png"),
  fever: require("../../../assets/words/f/fever.png"),
  fiber: require("../../../assets/words/f/fiber.png"),
  fiction: require("../../../assets/words/f/fiction.png"),
  fierce: require("../../../assets/words/f/fierce.png"),
  fight: require("../../../assets/words/f/fight.png"),
  figure: require("../../../assets/words/f/figure.png"),
  "figure out": require("../../../assets/words/f/figure-out.png"),
  fill: require("../../../assets/words/f/fill.png"),
  "fill out": require("../../../assets/words/f/fill-out.png"),
  filter: require("../../../assets/words/f/filter.png"),
  finally: require("../../../assets/words/f/finally.png"),
  finance: require("../../../assets/words/f/finance.png"),
  fine: require("../../../assets/words/f/fine.png"),
  finely: require("../../../assets/words/f/finely.png"),
  finish: require("../../../assets/words/f/finish.png"),
  firm: require("../../../assets/words/f/firm.png"),
  fit: require("../../../assets/words/f/fit.png"),
  fix: require("../../../assets/words/f/fix.png"),
  flag: require("../../../assets/words/f/flag.png"),
  flame: require("../../../assets/words/f/flame.png"),
  flash: require("../../../assets/words/f/flash.png"),
  flashlight: require("../../../assets/words/f/flashlight.png"),
  flat: require("../../../assets/words/f/flat.png"),
  flavor: require("../../../assets/words/f/flavor.png"),
  flaw: require("../../../assets/words/f/flaw.png"),
  flawless: require("../../../assets/words/f/flawless.png"),
  flexible: require("../../../assets/words/f/flexible.png"),
  flight: require("../../../assets/words/f/flight.png"),
  float: require("../../../assets/words/f/float.png"),
  flood: require("../../../assets/words/f/flood.png"),
  flourish: require("../../../assets/words/f/flourish.png"),
  flow: require("../../../assets/words/f/flow.png"),
  fluent: require("../../../assets/words/f/fluent.png"),
  flute: require("../../../assets/words/f/flute.png"),
  focus: require("../../../assets/words/f/focus.png"),
  "focus on": require("../../../assets/words/f/focus-on.png"),
  fog: require("../../../assets/words/f/fog.png"),
  folk: require("../../../assets/words/f/folk.png"),
  follow: require("../../../assets/words/f/follow.png"),
  following: require("../../../assets/words/f/following.png"),
  foolish: require("../../../assets/words/f/foolish.png"),
  "for a while": require("../../../assets/words/f/for-a-while.png"),
  "for instance": require("../../../assets/words/f/for-instance.png"),
  "for oneself": require("../../../assets/words/f/for-oneself.png"),
  forage: require("../../../assets/words/f/forage.png"),
  forbid: require("../../../assets/words/f/forbid.png"),
  force: require("../../../assets/words/f/force.png"),
  forcible: require("../../../assets/words/f/forcible.png"),
  forecast: require("../../../assets/words/f/forecast.png"),
  forehead: require("../../../assets/words/f/forehead.png"),
  foreign: require("../../../assets/words/f/foreign.png"),
  foreigner: require("../../../assets/words/f/foreigner.png"),
  foremost: require("../../../assets/words/f/foremost.png"),
  foresee: require("../../../assets/words/f/foresee.png"),
  forest: require("../../../assets/words/f/forest.png"),
  forgive: require("../../../assets/words/f/forgive.png"),
  form: require("../../../assets/words/f/form.png"),
  formal: require("../../../assets/words/f/formal.png"),
  former: require("../../../assets/words/f/former.png"),
  fortify: require("../../../assets/words/f/fortify.png"),
  fortunately: require("../../../assets/words/f/fortunately.png"),
  fortune: require("../../../assets/words/f/fortune.png"),
  forward: require("../../../assets/words/f/forward.png"),
  foster: require("../../../assets/words/f/foster.png"),
  foul: require("../../../assets/words/f/foul.png"),
  found: require("../../../assets/words/f/found.png"),
  foundation: require("../../../assets/words/f/foundation.png"),
  founding: require("../../../assets/words/f/founding.png"),
  "fountain-pen": require("../../../assets/words/f/fountain-pen.png"),
  fragile: require("../../../assets/words/f/fragile.png"),
  fragment: require("../../../assets/words/f/fragment.png"),
  fragmentary: require("../../../assets/words/f/fragmentary.png"),
  frankly: require("../../../assets/words/f/frankly.png"),
  "free from": require("../../../assets/words/f/free-from.png"),
  freeze: require("../../../assets/words/f/freeze.png"),
  french: require("../../../assets/words/f/french.png"),
  frequent: require("../../../assets/words/f/frequent.png"),
  frequently: require("../../../assets/words/f/frequently.png"),
  fresh: require("../../../assets/words/f/fresh.png"),
  frighten: require("../../../assets/words/f/frighten.png"),
  frog: require("../../../assets/words/f/frog.png"),
  "from time to time": require("../../../assets/words/f/from-time-to-time.png"),
  front: require("../../../assets/words/f/front.png"),
  fruit: require("../../../assets/words/f/fruit.png"),
  fruitlessly: require("../../../assets/words/f/fruitlessly.png"),
  frustrated: require("../../../assets/words/f/frustrated.png"),
  fuel: require("../../../assets/words/f/fuel.png"),
  fulfill: require("../../../assets/words/f/fulfill.png"),
  fun: require("../../../assets/words/f/fun.png"),
  function: require("../../../assets/words/f/function.png"),
  "function as": require("../../../assets/words/f/function-as.png"),
  fund: require("../../../assets/words/f/fund.png"),
  fundamental: require("../../../assets/words/f/fundamental.png"),
  funeral: require("../../../assets/words/f/funeral.png"),
  fur: require("../../../assets/words/f/fur.png"),
  furious: require("../../../assets/words/f/furious.png"),
  furnish: require("../../../assets/words/f/furnish.png"),
  furniture: require("../../../assets/words/f/furniture.png"),
  further: require("../../../assets/words/f/further.png"),
  furthermore: require("../../../assets/words/f/furthermore.png"),
  future: require("../../../assets/words/f/future.png"),
};
