import { ImageSourcePropType } from "react-native";

// "f" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_F: Record<string, ImageSourcePropType> = {
  facial: require("../../../assets/words/f/facial.png"),
  fact: require("../../../assets/words/f/fact.png"),
  factory: require("../../../assets/words/f/factory.png"),
  fail: require("../../../assets/words/f/fail.png"),
  fair: require("../../../assets/words/f/fair.png"),
  fame: require("../../../assets/words/f/fame.png"),
  famous: require("../../../assets/words/f/famous.png"),
  fare: require("../../../assets/words/f/fare.png"),
  fasten: require("../../../assets/words/f/fasten.png"),
  fat: require("../../../assets/words/f/fat.png"),
  fault: require("../../../assets/words/f/fault.png"),
  favorite: require("../../../assets/words/f/favorite.png"),
  fear: require("../../../assets/words/f/fear.png"),
  feast: require("../../../assets/words/f/feast.png"),
  feather: require("../../../assets/words/f/feather.png"),
  feature: require("../../../assets/words/f/feature.png"),
  feed: require("../../../assets/words/f/feed.png"),
  fence: require("../../../assets/words/f/fence.png"),
  fever: require("../../../assets/words/f/fever.png"),
  fierce: require("../../../assets/words/f/fierce.png"),
  fight: require("../../../assets/words/f/fight.png"),
  figure: require("../../../assets/words/f/figure.png"),
  fill: require("../../../assets/words/f/fill.png"),
  finally: require("../../../assets/words/f/finally.png"),
  firm: require("../../../assets/words/f/firm.png"),
  fit: require("../../../assets/words/f/fit.png"),
  flame: require("../../../assets/words/f/flame.png"),
  flashlight: require("../../../assets/words/f/flashlight.png"),
  flat: require("../../../assets/words/f/flat.png"),
  flight: require("../../../assets/words/f/flight.png"),
  float: require("../../../assets/words/f/float.png"),
  flood: require("../../../assets/words/f/flood.png"),
  flow: require("../../../assets/words/f/flow.png"),
  flute: require("../../../assets/words/f/flute.png"),
  fog: require("../../../assets/words/f/fog.png"),
  folk: require("../../../assets/words/f/folk.png"),
  follow: require("../../../assets/words/f/follow.png"),
  foolish: require("../../../assets/words/f/foolish.png"),
  "for a while": require("../../../assets/words/f/for-a-while.png"),
  force: require("../../../assets/words/f/force.png"),
  foreign: require("../../../assets/words/f/foreign.png"),
  foreigner: require("../../../assets/words/f/foreigner.png"),
  forest: require("../../../assets/words/f/forest.png"),
  fortunately: require("../../../assets/words/f/fortunately.png"),
  forward: require("../../../assets/words/f/forward.png"),
  foster: require("../../../assets/words/f/foster.png"),
  foundation: require("../../../assets/words/f/foundation.png"),
  "fountain-pen": require("../../../assets/words/f/fountain-pen.png"),
  frankly: require("../../../assets/words/f/frankly.png"),
  freeze: require("../../../assets/words/f/freeze.png"),
  french: require("../../../assets/words/f/french.png"),
  fresh: require("../../../assets/words/f/fresh.png"),
  frighten: require("../../../assets/words/f/frighten.png"),
  frog: require("../../../assets/words/f/frog.png"),
  front: require("../../../assets/words/f/front.png"),
  fruit: require("../../../assets/words/f/fruit.png"),
  frustrated: require("../../../assets/words/f/frustrated.png"),
  fun: require("../../../assets/words/f/fun.png"),
  funeral: require("../../../assets/words/f/funeral.png"),
  fur: require("../../../assets/words/f/fur.png"),
  furniture: require("../../../assets/words/f/furniture.png"),
  further: require("../../../assets/words/f/further.png"),
  future: require("../../../assets/words/f/future.png"),
};
