import { ImageSourcePropType } from "react-native";

// "g" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_G: Record<string, ImageSourcePropType> = {
  gain: require("../../../assets/words/g/gain.png"),
  gainful: require("../../../assets/words/g/gainful.png"),
  gala: require("../../../assets/words/g/gala.png"),
  galaxy: require("../../../assets/words/g/galaxy.png"),
  gallery: require("../../../assets/words/g/gallery.png"),
  gap: require("../../../assets/words/g/gap.png"),
  garage: require("../../../assets/words/g/garage.png"),
  garbage: require("../../../assets/words/g/garbage.png"),
  garment: require("../../../assets/words/g/garment.png"),
  gas: require("../../../assets/words/g/gas.png"),
  gather: require("../../../assets/words/g/gather.png"),
  gauge: require("../../../assets/words/g/gauge.png"),
  gay: require("../../../assets/words/g/gay.png"),
  gaze: require("../../../assets/words/g/gaze.png"),
  gear: require("../../../assets/words/g/gear.png"),
  gender: require("../../../assets/words/g/gender.png"),
  gene: require("../../../assets/words/g/gene.png"),
  general: require("../../../assets/words/g/general.png"),
  generalize: require("../../../assets/words/g/generalize.png"),
  generally: require("../../../assets/words/g/generally.png"),
  generate: require("../../../assets/words/g/generate.png"),
  generation: require("../../../assets/words/g/generation.png"),
  generator: require("../../../assets/words/g/generator.png"),
  generous: require("../../../assets/words/g/generous.png"),
  generously: require("../../../assets/words/g/generously.png"),
  genetic: require("../../../assets/words/g/genetic.png"),
  genius: require("../../../assets/words/g/genius.png"),
  genre: require("../../../assets/words/g/genre.png"),
  genuine: require("../../../assets/words/g/genuine.png"),
  genuinely: require("../../../assets/words/g/genuinely.png"),
  geography: require("../../../assets/words/g/geography.png"),
  geologist: require("../../../assets/words/g/geologist.png"),
  geology: require("../../../assets/words/g/geology.png"),
  geometry: require("../../../assets/words/g/geometry.png"),
  geothermal: require("../../../assets/words/g/geothermal.png"),
  germ: require("../../../assets/words/g/germ.png"),
  german: require("../../../assets/words/g/german.png"),
  germinate: require("../../../assets/words/g/germinate.png"),
  gesture: require("../../../assets/words/g/gesture.png"),
  "get along": require("../../../assets/words/g/get-along.png"),
  "get in the way of": require("../../../assets/words/g/get-in-the-way-of.png"),
  "get rid of": require("../../../assets/words/g/get-rid-of.png"),
  "get together": require("../../../assets/words/g/get-together.png"),
  "get used to": require("../../../assets/words/g/get-used-to.png"),
  ghost: require("../../../assets/words/g/ghost.png"),
  giant: require("../../../assets/words/g/giant.png"),
  gift: require("../../../assets/words/g/gift.png"),
  gifted: require("../../../assets/words/g/gifted.png"),
  gigantic: require("../../../assets/words/g/gigantic.png"),
  giraffe: require("../../../assets/words/g/giraffe.png"),
  "give off": require("../../../assets/words/g/give-off.png"),
  "give up": require("../../../assets/words/g/give-up.png"),
  given: require("../../../assets/words/g/given.png"),
  glacier: require("../../../assets/words/g/glacier.png"),
  glance: require("../../../assets/words/g/glance.png"),
  glare: require("../../../assets/words/g/glare.png"),
  gleaming: require("../../../assets/words/g/gleaming.png"),
  glide: require("../../../assets/words/g/glide.png"),
  glimpse: require("../../../assets/words/g/glimpse.png"),
  gloomy: require("../../../assets/words/g/gloomy.png"),
  glorify: require("../../../assets/words/g/glorify.png"),
  glory: require("../../../assets/words/g/glory.png"),
  glow: require("../../../assets/words/g/glow.png"),
  glue: require("../../../assets/words/g/glue.png"),
  "go by": require("../../../assets/words/g/go-by.png"),
  "go into": require("../../../assets/words/g/go-into.png"),
  "go out with": require("../../../assets/words/g/go-out-with.png"),
  "go over": require("../../../assets/words/g/go-over.png"),
  goal: require("../../../assets/words/g/goal.png"),
  god: require("../../../assets/words/g/god.png"),
  "golden age": require("../../../assets/words/g/golden-age.png"),
  goods: require("../../../assets/words/g/goods.png"),
  gorgeous: require("../../../assets/words/g/gorgeous.png"),
  govern: require("../../../assets/words/g/govern.png"),
  governing: require("../../../assets/words/g/governing.png"),
  government: require("../../../assets/words/g/government.png"),
  grab: require("../../../assets/words/g/grab.png"),
  grade: require("../../../assets/words/g/grade.png"),
  gradual: require("../../../assets/words/g/gradual.png"),
  gradually: require("../../../assets/words/g/gradually.png"),
  graduate: require("../../../assets/words/g/graduate.png"),
  grain: require("../../../assets/words/g/grain.png"),
  grammar: require("../../../assets/words/g/grammar.png"),
  grand: require("../../../assets/words/g/grand.png"),
  grant: require("../../../assets/words/g/grant.png"),
  grasp: require("../../../assets/words/g/grasp.png"),
  grass: require("../../../assets/words/g/grass.png"),
  grateful: require("../../../assets/words/g/grateful.png"),
  gratify: require("../../../assets/words/g/gratify.png"),
  gratitude: require("../../../assets/words/g/gratitude.png"),
  gratuity: require("../../../assets/words/g/gratuity.png"),
  grave: require("../../../assets/words/g/grave.png"),
  gravity: require("../../../assets/words/g/gravity.png"),
  gray: require("../../../assets/words/g/gray.png"),
  graze: require("../../../assets/words/g/graze.png"),
  greed: require("../../../assets/words/g/greed.png"),
  greedy: require("../../../assets/words/g/greedy.png"),
  greenhouse: require("../../../assets/words/g/greenhouse.png"),
  greet: require("../../../assets/words/g/greet.png"),
  greeting: require("../../../assets/words/g/greeting.png"),
  grip: require("../../../assets/words/g/grip.png"),
  grocery: require("../../../assets/words/g/grocery.png"),
  gross: require("../../../assets/words/g/gross.png"),
  grossly: require("../../../assets/words/g/grossly.png"),
  ground: require("../../../assets/words/g/ground.png"),
  groundless: require("../../../assets/words/g/groundless.png"),
  group: require("../../../assets/words/g/group.png"),
  "grown-up": require("../../../assets/words/g/grown-up.png"),
  growth: require("../../../assets/words/g/growth.png"),
  guarantee: require("../../../assets/words/g/guarantee.png"),
  guard: require("../../../assets/words/g/guard.png"),
  guardian: require("../../../assets/words/g/guardian.png"),
  guess: require("../../../assets/words/g/guess.png"),
  guest: require("../../../assets/words/g/guest.png"),
  guide: require("../../../assets/words/g/guide.png"),
  guilt: require("../../../assets/words/g/guilt.png"),
  guilty: require("../../../assets/words/g/guilty.png"),
  gun: require("../../../assets/words/g/gun.png"),
};
