import { ImageSourcePropType } from "react-native";

// "g" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_G: Record<string, ImageSourcePropType> = {
  gain: require("../../../assets/words/g/gain.png"),
  gallery: require("../../../assets/words/g/gallery.png"),
  gap: require("../../../assets/words/g/gap.png"),
  garage: require("../../../assets/words/g/garage.png"),
  gather: require("../../../assets/words/g/gather.png"),
  gay: require("../../../assets/words/g/gay.png"),
  gaze: require("../../../assets/words/g/gaze.png"),
  general: require("../../../assets/words/g/general.png"),
  generation: require("../../../assets/words/g/generation.png"),
  genius: require("../../../assets/words/g/genius.png"),
  geography: require("../../../assets/words/g/geography.png"),
  german: require("../../../assets/words/g/german.png"),
  gesture: require("../../../assets/words/g/gesture.png"),
  giant: require("../../../assets/words/g/giant.png"),
  gift: require("../../../assets/words/g/gift.png"),
  giraffe: require("../../../assets/words/g/giraffe.png"),
  "give off": require("../../../assets/words/g/give-off.png"),
  glory: require("../../../assets/words/g/glory.png"),
  "go out with": require("../../../assets/words/g/go-out-with.png"),
  goal: require("../../../assets/words/g/goal.png"),
  god: require("../../../assets/words/g/god.png"),
  govern: require("../../../assets/words/g/govern.png"),
  government: require("../../../assets/words/g/government.png"),
  grab: require("../../../assets/words/g/grab.png"),
  grade: require("../../../assets/words/g/grade.png"),
  gradually: require("../../../assets/words/g/gradually.png"),
  graduate: require("../../../assets/words/g/graduate.png"),
  grain: require("../../../assets/words/g/grain.png"),
  grammar: require("../../../assets/words/g/grammar.png"),
  grand: require("../../../assets/words/g/grand.png"),
  grant: require("../../../assets/words/g/grant.png"),
  grass: require("../../../assets/words/g/grass.png"),
  gratitude: require("../../../assets/words/g/gratitude.png"),
  grave: require("../../../assets/words/g/grave.png"),
  gravity: require("../../../assets/words/g/gravity.png"),
  gray: require("../../../assets/words/g/gray.png"),
  greedy: require("../../../assets/words/g/greedy.png"),
  greeting: require("../../../assets/words/g/greeting.png"),
  grocery: require("../../../assets/words/g/grocery.png"),
  ground: require("../../../assets/words/g/ground.png"),
  group: require("../../../assets/words/g/group.png"),
  guard: require("../../../assets/words/g/guard.png"),
  guess: require("../../../assets/words/g/guess.png"),
  guest: require("../../../assets/words/g/guest.png"),
  guide: require("../../../assets/words/g/guide.png"),
  guilty: require("../../../assets/words/g/guilty.png"),
  gun: require("../../../assets/words/g/gun.png"),
};
