import { ImageSourcePropType } from "react-native";

// "g" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_G: Record<string, ImageSourcePropType> = {
  gain: require("../../../assets/words/g/gain.png"),
  gainful: require("../../../assets/words/g/gainful.png"),
  galaxy: require("../../../assets/words/g/galaxy.png"),
  gallery: require("../../../assets/words/g/gallery.png"),
  gap: require("../../../assets/words/g/gap.png"),
  garage: require("../../../assets/words/g/garage.png"),
  gather: require("../../../assets/words/g/gather.png"),
  gay: require("../../../assets/words/g/gay.png"),
  gaze: require("../../../assets/words/g/gaze.png"),
  gender: require("../../../assets/words/g/gender.png"),
  gene: require("../../../assets/words/g/gene.png"),
  general: require("../../../assets/words/g/general.png"),
  generally: require("../../../assets/words/g/generally.png"),
  generate: require("../../../assets/words/g/generate.png"),
  generation: require("../../../assets/words/g/generation.png"),
  generous: require("../../../assets/words/g/generous.png"),
  genetic: require("../../../assets/words/g/genetic.png"),
  genius: require("../../../assets/words/g/genius.png"),
  genuinely: require("../../../assets/words/g/genuinely.png"),
  geography: require("../../../assets/words/g/geography.png"),
  german: require("../../../assets/words/g/german.png"),
  gesture: require("../../../assets/words/g/gesture.png"),
  "get along": require("../../../assets/words/g/get-along.png"),
  "get in the way of": require("../../../assets/words/g/get-in-the-way-of.png"),
  "get together": require("../../../assets/words/g/get-together.png"),
  "get used to": require("../../../assets/words/g/get-used-to.png"),
  ghost: require("../../../assets/words/g/ghost.png"),
  giant: require("../../../assets/words/g/giant.png"),
  gift: require("../../../assets/words/g/gift.png"),
  giraffe: require("../../../assets/words/g/giraffe.png"),
  "give off": require("../../../assets/words/g/give-off.png"),
  "give up": require("../../../assets/words/g/give-up.png"),
  glory: require("../../../assets/words/g/glory.png"),
  "go by": require("../../../assets/words/g/go-by.png"),
  "go out with": require("../../../assets/words/g/go-out-with.png"),
  "go over": require("../../../assets/words/g/go-over.png"),
  goal: require("../../../assets/words/g/goal.png"),
  god: require("../../../assets/words/g/god.png"),
  govern: require("../../../assets/words/g/govern.png"),
  government: require("../../../assets/words/g/government.png"),
  grab: require("../../../assets/words/g/grab.png"),
  grade: require("../../../assets/words/g/grade.png"),
  gradual: require("../../../assets/words/g/gradual.png"),
  gradually: require("../../../assets/words/g/gradually.png"),
  graduate: require("../../../assets/words/g/graduate.png"),
  grain: require("../../../assets/words/g/grain.png"),
  grammar: require("../../../assets/words/g/grammar.png"),
  grand: require("../../../assets/words/g/grand.png"),
  grant: require("../../../assets/words/g/grant.png"),
  grass: require("../../../assets/words/g/grass.png"),
  grateful: require("../../../assets/words/g/grateful.png"),
  gratitude: require("../../../assets/words/g/gratitude.png"),
  grave: require("../../../assets/words/g/grave.png"),
  gravity: require("../../../assets/words/g/gravity.png"),
  gray: require("../../../assets/words/g/gray.png"),
  greedy: require("../../../assets/words/g/greedy.png"),
  greenhouse: require("../../../assets/words/g/greenhouse.png"),
  greet: require("../../../assets/words/g/greet.png"),
  greeting: require("../../../assets/words/g/greeting.png"),
  grip: require("../../../assets/words/g/grip.png"),
  grocery: require("../../../assets/words/g/grocery.png"),
  ground: require("../../../assets/words/g/ground.png"),
  group: require("../../../assets/words/g/group.png"),
  guarantee: require("../../../assets/words/g/guarantee.png"),
  guard: require("../../../assets/words/g/guard.png"),
  guess: require("../../../assets/words/g/guess.png"),
  guest: require("../../../assets/words/g/guest.png"),
  guide: require("../../../assets/words/g/guide.png"),
  guilty: require("../../../assets/words/g/guilty.png"),
  gun: require("../../../assets/words/g/gun.png"),
};
