import { ImageSourcePropType } from "react-native";

// "h" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_H: Record<string, ImageSourcePropType> = {
  habit: require("../../../assets/words/h/habit.png"),
  habitat: require("../../../assets/words/h/habitat.png"),
  habitation: require("../../../assets/words/h/habitation.png"),
  half: require("../../../assets/words/h/half.png"),
  halt: require("../../../assets/words/h/halt.png"),
  hand: require("../../../assets/words/h/hand.png"),
  handle: require("../../../assets/words/h/handle.png"),
  handshake: require("../../../assets/words/h/handshake.png"),
  handsome: require("../../../assets/words/h/handsome.png"),
  hang: require("../../../assets/words/h/hang.png"),
  "hang out": require("../../../assets/words/h/hang-out.png"),
  happen: require("../../../assets/words/h/happen.png"),
  harbor: require("../../../assets/words/h/harbor.png"),
  hardly: require("../../../assets/words/h/hardly.png"),
  hardship: require("../../../assets/words/h/hardship.png"),
  harm: require("../../../assets/words/h/harm.png"),
  harmful: require("../../../assets/words/h/harmful.png"),
  harsh: require("../../../assets/words/h/harsh.png"),
  harvest: require("../../../assets/words/h/harvest.png"),
  haste: require("../../../assets/words/h/haste.png"),
  hastily: require("../../../assets/words/h/hastily.png"),
  hatch: require("../../../assets/words/h/hatch.png"),
  hate: require("../../../assets/words/h/hate.png"),
  "have ~ in common": require("../../../assets/words/h/have-~-in-common.png"),
  hawk: require("../../../assets/words/h/hawk.png"),
  hay: require("../../../assets/words/h/hay.png"),
  hazard: require("../../../assets/words/h/hazard.png"),
  hazardous: require("../../../assets/words/h/hazardous.png"),
  headquarters: require("../../../assets/words/h/headquarters.png"),
  heal: require("../../../assets/words/h/heal.png"),
  health: require("../../../assets/words/h/health.png"),
  heart: require("../../../assets/words/h/heart.png"),
  heat: require("../../../assets/words/h/heat.png"),
  heaven: require("../../../assets/words/h/heaven.png"),
  heavy: require("../../../assets/words/h/heavy.png"),
  height: require("../../../assets/words/h/height.png"),
  heighten: require("../../../assets/words/h/heighten.png"),
  hence: require("../../../assets/words/h/hence.png"),
  herd: require("../../../assets/words/h/herd.png"),
  heritage: require("../../../assets/words/h/heritage.png"),
  hero: require("../../../assets/words/h/hero.png"),
  hesitancy: require("../../../assets/words/h/hesitancy.png"),
  hesitantly: require("../../../assets/words/h/hesitantly.png"),
  hesitate: require("../../../assets/words/h/hesitate.png"),
  hidden: require("../../../assets/words/h/hidden.png"),
  hide: require("../../../assets/words/h/hide.png"),
  high: require("../../../assets/words/h/high.png"),
  "high priority": require("../../../assets/words/h/high-priority.png"),
  highlight: require("../../../assets/words/h/highlight.png"),
  highway: require("../../../assets/words/h/highway.png"),
  hike: require("../../../assets/words/h/hike.png"),
  hind: require("../../../assets/words/h/hind.png"),
  hinder: require("../../../assets/words/h/hinder.png"),
  hire: require("../../../assets/words/h/hire.png"),
  hiring: require("../../../assets/words/h/hiring.png"),
  historian: require("../../../assets/words/h/historian.png"),
  historical: require("../../../assets/words/h/historical.png"),
  history: require("../../../assets/words/h/history.png"),
  hit: require("../../../assets/words/h/hit.png"),
  hobby: require("../../../assets/words/h/hobby.png"),
  hold: require("../../../assets/words/h/hold.png"),
  "hold on (to)": require("../../../assets/words/h/hold-on-(to).png"),
  "hold up": require("../../../assets/words/h/hold-up.png"),
  hole: require("../../../assets/words/h/hole.png"),
  holiday: require("../../../assets/words/h/holiday.png"),
  hollow: require("../../../assets/words/h/hollow.png"),
  holy: require("../../../assets/words/h/holy.png"),
  homeless: require("../../../assets/words/h/homeless.png"),
  homesick: require("../../../assets/words/h/homesick.png"),
  hometown: require("../../../assets/words/h/hometown.png"),
  honest: require("../../../assets/words/h/honest.png"),
  honor: require("../../../assets/words/h/honor.png"),
  honour: require("../../../assets/words/h/honour.png"),
  hop: require("../../../assets/words/h/hop.png"),
  horizon: require("../../../assets/words/h/horizon.png"),
  horn: require("../../../assets/words/h/horn.png"),
  hospital: require("../../../assets/words/h/hospital.png"),
  hospitality: require("../../../assets/words/h/hospitality.png"),
  host: require("../../../assets/words/h/host.png"),
  hostile: require("../../../assets/words/h/hostile.png"),
  house: require("../../../assets/words/h/house.png"),
  household: require("../../../assets/words/h/household.png"),
  however: require("../../../assets/words/h/however.png"),
  howl: require("../../../assets/words/h/howl.png"),
  hue: require("../../../assets/words/h/hue.png"),
  hug: require("../../../assets/words/h/hug.png"),
  huge: require("../../../assets/words/h/huge.png"),
  humanity: require("../../../assets/words/h/humanity.png"),
  humble: require("../../../assets/words/h/humble.png"),
  humor: require("../../../assets/words/h/humor.png"),
  humorous: require("../../../assets/words/h/humorous.png"),
  hunger: require("../../../assets/words/h/hunger.png"),
  hunter: require("../../../assets/words/h/hunter.png"),
  hurray: require("../../../assets/words/h/hurray.png"),
  hurry: require("../../../assets/words/h/hurry.png"),
  hurt: require("../../../assets/words/h/hurt.png"),
  husband: require("../../../assets/words/h/husband.png"),
  hut: require("../../../assets/words/h/hut.png"),
  hybrid: require("../../../assets/words/h/hybrid.png"),
  hydrogen: require("../../../assets/words/h/hydrogen.png"),
};
