import { ImageSourcePropType } from "react-native";

// "i" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_I: Record<string, ImageSourcePropType> = {
  iceberg: require("../../../assets/words/i/iceberg.png"),
  idea: require("../../../assets/words/i/idea.png"),
  ideal: require("../../../assets/words/i/ideal.png"),
  identical: require("../../../assets/words/i/identical.png"),
  identify: require("../../../assets/words/i/identify.png"),
  identity: require("../../../assets/words/i/identity.png"),
  ignorant: require("../../../assets/words/i/ignorant.png"),
  ignore: require("../../../assets/words/i/ignore.png"),
  illegal: require("../../../assets/words/i/illegal.png"),
  illness: require("../../../assets/words/i/illness.png"),
  illuminate: require("../../../assets/words/i/illuminate.png"),
  illumination: require("../../../assets/words/i/illumination.png"),
  illusion: require("../../../assets/words/i/illusion.png"),
  illustrate: require("../../../assets/words/i/illustrate.png"),
  imaginable: require("../../../assets/words/i/imaginable.png"),
  imaginary: require("../../../assets/words/i/imaginary.png"),
  imagination: require("../../../assets/words/i/imagination.png"),
  imaginative: require("../../../assets/words/i/imaginative.png"),
  imagine: require("../../../assets/words/i/imagine.png"),
  imitate: require("../../../assets/words/i/imitate.png"),
  immediate: require("../../../assets/words/i/immediate.png"),
  immediately: require("../../../assets/words/i/immediately.png"),
  immense: require("../../../assets/words/i/immense.png"),
  immigrant: require("../../../assets/words/i/immigrant.png"),
  immigrate: require("../../../assets/words/i/immigrate.png"),
  immoral: require("../../../assets/words/i/immoral.png"),
  immune: require("../../../assets/words/i/immune.png"),
  impact: require("../../../assets/words/i/impact.png"),
  impartial: require("../../../assets/words/i/impartial.png"),
  impartially: require("../../../assets/words/i/impartially.png"),
  impede: require("../../../assets/words/i/impede.png"),
  impediment: require("../../../assets/words/i/impediment.png"),
  imperative: require("../../../assets/words/i/imperative.png"),
  imperceptibly: require("../../../assets/words/i/imperceptibly.png"),
  implausible: require("../../../assets/words/i/implausible.png"),
  implement: require("../../../assets/words/i/implement.png"),
  imply: require("../../../assets/words/i/imply.png"),
  import: require("../../../assets/words/i/import.png"),
  importance: require("../../../assets/words/i/importance.png"),
  important: require("../../../assets/words/i/important.png"),
  impose: require("../../../assets/words/i/impose.png"),
  imposing: require("../../../assets/words/i/imposing.png"),
  impossible: require("../../../assets/words/i/impossible.png"),
  impractical: require("../../../assets/words/i/impractical.png"),
  imprecise: require("../../../assets/words/i/imprecise.png"),
  impress: require("../../../assets/words/i/impress.png"),
  impressed: require("../../../assets/words/i/impressed.png"),
  impression: require("../../../assets/words/i/impression.png"),
  impressive: require("../../../assets/words/i/impressive.png"),
  imprint: require("../../../assets/words/i/imprint.png"),
  imprison: require("../../../assets/words/i/imprison.png"),
  improve: require("../../../assets/words/i/improve.png"),
  improvise: require("../../../assets/words/i/improvise.png"),
  impulse: require("../../../assets/words/i/impulse.png"),
  "in a respect": require("../../../assets/words/i/in-a-respect.png"),
  "in addition to": require("../../../assets/words/i/in-addition-to.png"),
  "in advance": require("../../../assets/words/i/in-advance.png"),
  "in any case": require("../../../assets/words/i/in-any-case.png"),
  "in balance": require("../../../assets/words/i/in-balance.png"),
  "in charge of": require("../../../assets/words/i/in-charge-of.png"),
  "in detail": require("../../../assets/words/i/in-detail.png"),
  "in due time": require("../../../assets/words/i/in-due-time.png"),
  "in earnest": require("../../../assets/words/i/in-earnest.png"),
  "in effect": require("../../../assets/words/i/in-effect.png"),
  "in essence": require("../../../assets/words/i/in-essence.png"),
  "in fact": require("../../../assets/words/i/in-fact.png"),
  "in general": require("../../../assets/words/i/in-general.png"),
  "in keeping with": require("../../../assets/words/i/in-keeping-with.png"),
  "in operation": require("../../../assets/words/i/in-operation.png"),
  "in opposition to": require("../../../assets/words/i/in-opposition-to.png"),
  "in order to": require("../../../assets/words/i/in-order-to.png"),
  "in place": require("../../../assets/words/i/in-place.png"),
  "in place of": require("../../../assets/words/i/in-place-of.png"),
  "in progress": require("../../../assets/words/i/in-progress.png"),
  "in response to": require("../../../assets/words/i/in-response-to.png"),
  "in spite of": require("../../../assets/words/i/in-spite-of.png"),
  "in terms of": require("../../../assets/words/i/in-terms-of.png"),
  "in the course of": require("../../../assets/words/i/in-the-course-of.png"),
  "in time": require("../../../assets/words/i/in-time.png"),
  inaccessible: require("../../../assets/words/i/inaccessible.png"),
  inactive: require("../../../assets/words/i/inactive.png"),
  inadequate: require("../../../assets/words/i/inadequate.png"),
  inappropriate: require("../../../assets/words/i/inappropriate.png"),
  inborn: require("../../../assets/words/i/inborn.png"),
  incentive: require("../../../assets/words/i/incentive.png"),
  incessant: require("../../../assets/words/i/incessant.png"),
  incessantly: require("../../../assets/words/i/incessantly.png"),
  incident: require("../../../assets/words/i/incident.png"),
  incidental: require("../../../assets/words/i/incidental.png"),
  incite: require("../../../assets/words/i/incite.png"),
  inclement: require("../../../assets/words/i/inclement.png"),
  inclination: require("../../../assets/words/i/inclination.png"),
  incline: require("../../../assets/words/i/incline.png"),
  inclined: require("../../../assets/words/i/inclined.png"),
  include: require("../../../assets/words/i/include.png"),
  income: require("../../../assets/words/i/income.png"),
  incompletely: require("../../../assets/words/i/incompletely.png"),
  inconceivable: require("../../../assets/words/i/inconceivable.png"),
  inconsequential: require("../../../assets/words/i/inconsequential.png"),
  inconvenience: require("../../../assets/words/i/inconvenience.png"),
  incorporate: require("../../../assets/words/i/incorporate.png"),
  increase: require("../../../assets/words/i/increase.png"),
  increasing: require("../../../assets/words/i/increasing.png"),
  incredible: require("../../../assets/words/i/incredible.png"),
  indeed: require("../../../assets/words/i/indeed.png"),
  indefinitely: require("../../../assets/words/i/indefinitely.png"),
  independence: require("../../../assets/words/i/independence.png"),
  independent: require("../../../assets/words/i/independent.png"),
  index: require("../../../assets/words/i/index.png"),
  indicate: require("../../../assets/words/i/indicate.png"),
  indication: require("../../../assets/words/i/indication.png"),
  indifferent: require("../../../assets/words/i/indifferent.png"),
  indispensable: require("../../../assets/words/i/indispensable.png"),
  individual: require("../../../assets/words/i/individual.png"),
  induce: require("../../../assets/words/i/induce.png"),
  industrial: require("../../../assets/words/i/industrial.png"),
  industry: require("../../../assets/words/i/industry.png"),
  ineffective: require("../../../assets/words/i/ineffective.png"),
  inequality: require("../../../assets/words/i/inequality.png"),
  inevitable: require("../../../assets/words/i/inevitable.png"),
  inevitably: require("../../../assets/words/i/inevitably.png"),
  inexpertly: require("../../../assets/words/i/inexpertly.png"),
  infamous: require("../../../assets/words/i/infamous.png"),
  infection: require("../../../assets/words/i/infection.png"),
  infectious: require("../../../assets/words/i/infectious.png"),
  inferior: require("../../../assets/words/i/inferior.png"),
  infinite: require("../../../assets/words/i/infinite.png"),
  infirm: require("../../../assets/words/i/infirm.png"),
  inflation: require("../../../assets/words/i/inflation.png"),
  influence: require("../../../assets/words/i/influence.png"),
  influential: require("../../../assets/words/i/influential.png"),
  inform: require("../../../assets/words/i/inform.png"),
  informally: require("../../../assets/words/i/informally.png"),
  information: require("../../../assets/words/i/information.png"),
  informed: require("../../../assets/words/i/informed.png"),
  infrastructure: require("../../../assets/words/i/infrastructure.png"),
  infrequent: require("../../../assets/words/i/infrequent.png"),
  ingenious: require("../../../assets/words/i/ingenious.png"),
  ingenuity: require("../../../assets/words/i/ingenuity.png"),
  ingredient: require("../../../assets/words/i/ingredient.png"),
  inhabit: require("../../../assets/words/i/inhabit.png"),
  inhabitant: require("../../../assets/words/i/inhabitant.png"),
  inherent: require("../../../assets/words/i/inherent.png"),
  inherently: require("../../../assets/words/i/inherently.png"),
  inherit: require("../../../assets/words/i/inherit.png"),
  inhibit: require("../../../assets/words/i/inhibit.png"),
  initial: require("../../../assets/words/i/initial.png"),
  initially: require("../../../assets/words/i/initially.png"),
  initiate: require("../../../assets/words/i/initiate.png"),
  initiative: require("../../../assets/words/i/initiative.png"),
  injure: require("../../../assets/words/i/injure.png"),
  injurious: require("../../../assets/words/i/injurious.png"),
  innate: require("../../../assets/words/i/innate.png"),
  inner: require("../../../assets/words/i/inner.png"),
  inning: require("../../../assets/words/i/inning.png"),
  innocent: require("../../../assets/words/i/innocent.png"),
  innovation: require("../../../assets/words/i/innovation.png"),
  innovative: require("../../../assets/words/i/innovative.png"),
  innumerable: require("../../../assets/words/i/innumerable.png"),
  inquire: require("../../../assets/words/i/inquire.png"),
  insect: require("../../../assets/words/i/insect.png"),
  insecure: require("../../../assets/words/i/insecure.png"),
  insight: require("../../../assets/words/i/insight.png"),
  insignificant: require("../../../assets/words/i/insignificant.png"),
  insist: require("../../../assets/words/i/insist.png"),
  inspect: require("../../../assets/words/i/inspect.png"),
  inspiration: require("../../../assets/words/i/inspiration.png"),
  inspire: require("../../../assets/words/i/inspire.png"),
  install: require("../../../assets/words/i/install.png"),
  instance: require("../../../assets/words/i/instance.png"),
  instant: require("../../../assets/words/i/instant.png"),
  instantaneous: require("../../../assets/words/i/instantaneous.png"),
  instantly: require("../../../assets/words/i/instantly.png"),
  instead: require("../../../assets/words/i/instead.png"),
  "instead of": require("../../../assets/words/i/instead-of.png"),
  instinct: require("../../../assets/words/i/instinct.png"),
  institute: require("../../../assets/words/i/institute.png"),
  institution: require("../../../assets/words/i/institution.png"),
  instruct: require("../../../assets/words/i/instruct.png"),
  instruction: require("../../../assets/words/i/instruction.png"),
  instructor: require("../../../assets/words/i/instructor.png"),
  instrument: require("../../../assets/words/i/instrument.png"),
  insufficient: require("../../../assets/words/i/insufficient.png"),
  insult: require("../../../assets/words/i/insult.png"),
  insurance: require("../../../assets/words/i/insurance.png"),
  insure: require("../../../assets/words/i/insure.png"),
  intact: require("../../../assets/words/i/intact.png"),
  intake: require("../../../assets/words/i/intake.png"),
  integral: require("../../../assets/words/i/integral.png"),
  integrate: require("../../../assets/words/i/integrate.png"),
  intellectual: require("../../../assets/words/i/intellectual.png"),
  intelligence: require("../../../assets/words/i/intelligence.png"),
  intelligent: require("../../../assets/words/i/intelligent.png"),
  intend: require("../../../assets/words/i/intend.png"),
  intense: require("../../../assets/words/i/intense.png"),
  intensify: require("../../../assets/words/i/intensify.png"),
  intent: require("../../../assets/words/i/intent.png"),
  "intent on": require("../../../assets/words/i/intent-on.png"),
  intention: require("../../../assets/words/i/intention.png"),
  intentionally: require("../../../assets/words/i/intentionally.png"),
  interact: require("../../../assets/words/i/interact.png"),
  interaction: require("../../../assets/words/i/interaction.png"),
  interest: require("../../../assets/words/i/interest.png"),
  interesting: require("../../../assets/words/i/interesting.png"),
  interfere: require("../../../assets/words/i/interfere.png"),
  interior: require("../../../assets/words/i/interior.png"),
  internal: require("../../../assets/words/i/internal.png"),
  international: require("../../../assets/words/i/international.png"),
  interpret: require("../../../assets/words/i/interpret.png"),
  interrupt: require("../../../assets/words/i/interrupt.png"),
  intersect: require("../../../assets/words/i/intersect.png"),
  intersection: require("../../../assets/words/i/intersection.png"),
  interval: require("../../../assets/words/i/interval.png"),
  intervene: require("../../../assets/words/i/intervene.png"),
  intimate: require("../../../assets/words/i/intimate.png"),
  intimately: require("../../../assets/words/i/intimately.png"),
  intimation: require("../../../assets/words/i/intimation.png"),
  intricate: require("../../../assets/words/i/intricate.png"),
  intrigue: require("../../../assets/words/i/intrigue.png"),
  intrinsic: require("../../../assets/words/i/intrinsic.png"),
  introduce: require("../../../assets/words/i/introduce.png"),
  introduction: require("../../../assets/words/i/introduction.png"),
  introvert: require("../../../assets/words/i/introvert.png"),
  intuition: require("../../../assets/words/i/intuition.png"),
  invade: require("../../../assets/words/i/invade.png"),
  invader: require("../../../assets/words/i/invader.png"),
  invaluable: require("../../../assets/words/i/invaluable.png"),
  invariably: require("../../../assets/words/i/invariably.png"),
  invent: require("../../../assets/words/i/invent.png"),
  invention: require("../../../assets/words/i/invention.png"),
  inventory: require("../../../assets/words/i/inventory.png"),
  invest: require("../../../assets/words/i/invest.png"),
  investigate: require("../../../assets/words/i/investigate.png"),
  investment: require("../../../assets/words/i/investment.png"),
  invisible: require("../../../assets/words/i/invisible.png"),
  invitation: require("../../../assets/words/i/invitation.png"),
  invite: require("../../../assets/words/i/invite.png"),
  invoice: require("../../../assets/words/i/invoice.png"),
  involve: require("../../../assets/words/i/involve.png"),
  iron: require("../../../assets/words/i/iron.png"),
  irreparable: require("../../../assets/words/i/irreparable.png"),
  irresistible: require("../../../assets/words/i/irresistible.png"),
  irreversible: require("../../../assets/words/i/irreversible.png"),
  irrigation: require("../../../assets/words/i/irrigation.png"),
  irritate: require("../../../assets/words/i/irritate.png"),
  island: require("../../../assets/words/i/island.png"),
  isolate: require("../../../assets/words/i/isolate.png"),
  isolated: require("../../../assets/words/i/isolated.png"),
  isolation: require("../../../assets/words/i/isolation.png"),
  issue: require("../../../assets/words/i/issue.png"),
  ivy: require("../../../assets/words/i/ivy.png"),
};
