import { ImageSourcePropType } from "react-native";

// "i" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_I: Record<string, ImageSourcePropType> = {
  iceberg: require("../../../assets/words/i/iceberg.png"),
  idea: require("../../../assets/words/i/idea.png"),
  identical: require("../../../assets/words/i/identical.png"),
  identify: require("../../../assets/words/i/identify.png"),
  ignorant: require("../../../assets/words/i/ignorant.png"),
  ignore: require("../../../assets/words/i/ignore.png"),
  illegal: require("../../../assets/words/i/illegal.png"),
  illness: require("../../../assets/words/i/illness.png"),
  illustrate: require("../../../assets/words/i/illustrate.png"),
  imagine: require("../../../assets/words/i/imagine.png"),
  imitate: require("../../../assets/words/i/imitate.png"),
  immediately: require("../../../assets/words/i/immediately.png"),
  immigrant: require("../../../assets/words/i/immigrant.png"),
  immigrate: require("../../../assets/words/i/immigrate.png"),
  immune: require("../../../assets/words/i/immune.png"),
  impact: require("../../../assets/words/i/impact.png"),
  import: require("../../../assets/words/i/import.png"),
  importance: require("../../../assets/words/i/importance.png"),
  important: require("../../../assets/words/i/important.png"),
  impossible: require("../../../assets/words/i/impossible.png"),
  impress: require("../../../assets/words/i/impress.png"),
  impression: require("../../../assets/words/i/impression.png"),
  improve: require("../../../assets/words/i/improve.png"),
  "in advance": require("../../../assets/words/i/in-advance.png"),
  "in balance": require("../../../assets/words/i/in-balance.png"),
  "in detail": require("../../../assets/words/i/in-detail.png"),
  "in fact": require("../../../assets/words/i/in-fact.png"),
  "in order to": require("../../../assets/words/i/in-order-to.png"),
  "in place": require("../../../assets/words/i/in-place.png"),
  "in response to": require("../../../assets/words/i/in-response-to.png"),
  incentive: require("../../../assets/words/i/incentive.png"),
  incident: require("../../../assets/words/i/incident.png"),
  include: require("../../../assets/words/i/include.png"),
  increase: require("../../../assets/words/i/increase.png"),
  incredible: require("../../../assets/words/i/incredible.png"),
  indeed: require("../../../assets/words/i/indeed.png"),
  independence: require("../../../assets/words/i/independence.png"),
  independent: require("../../../assets/words/i/independent.png"),
  indicate: require("../../../assets/words/i/indicate.png"),
  indifferent: require("../../../assets/words/i/indifferent.png"),
  individual: require("../../../assets/words/i/individual.png"),
  industrial: require("../../../assets/words/i/industrial.png"),
  industry: require("../../../assets/words/i/industry.png"),
  infection: require("../../../assets/words/i/infection.png"),
  influence: require("../../../assets/words/i/influence.png"),
  inform: require("../../../assets/words/i/inform.png"),
  information: require("../../../assets/words/i/information.png"),
  infrastructure: require("../../../assets/words/i/infrastructure.png"),
  ingredient: require("../../../assets/words/i/ingredient.png"),
  initial: require("../../../assets/words/i/initial.png"),
  injure: require("../../../assets/words/i/injure.png"),
  inner: require("../../../assets/words/i/inner.png"),
  inning: require("../../../assets/words/i/inning.png"),
  innocent: require("../../../assets/words/i/innocent.png"),
  innovation: require("../../../assets/words/i/innovation.png"),
  inquire: require("../../../assets/words/i/inquire.png"),
  insect: require("../../../assets/words/i/insect.png"),
  insight: require("../../../assets/words/i/insight.png"),
  insist: require("../../../assets/words/i/insist.png"),
  inspire: require("../../../assets/words/i/inspire.png"),
  install: require("../../../assets/words/i/install.png"),
  instance: require("../../../assets/words/i/instance.png"),
  instant: require("../../../assets/words/i/instant.png"),
  instantly: require("../../../assets/words/i/instantly.png"),
  instead: require("../../../assets/words/i/instead.png"),
  "instead of": require("../../../assets/words/i/instead-of.png"),
  institution: require("../../../assets/words/i/institution.png"),
  instruct: require("../../../assets/words/i/instruct.png"),
  instruction: require("../../../assets/words/i/instruction.png"),
  instrument: require("../../../assets/words/i/instrument.png"),
  insurance: require("../../../assets/words/i/insurance.png"),
  intake: require("../../../assets/words/i/intake.png"),
  intellectual: require("../../../assets/words/i/intellectual.png"),
  intelligence: require("../../../assets/words/i/intelligence.png"),
  intelligent: require("../../../assets/words/i/intelligent.png"),
  intend: require("../../../assets/words/i/intend.png"),
  intention: require("../../../assets/words/i/intention.png"),
  interact: require("../../../assets/words/i/interact.png"),
  interest: require("../../../assets/words/i/interest.png"),
  interesting: require("../../../assets/words/i/interesting.png"),
  interfere: require("../../../assets/words/i/interfere.png"),
  interior: require("../../../assets/words/i/interior.png"),
  internal: require("../../../assets/words/i/internal.png"),
  international: require("../../../assets/words/i/international.png"),
  interpret: require("../../../assets/words/i/interpret.png"),
  interrupt: require("../../../assets/words/i/interrupt.png"),
  intersection: require("../../../assets/words/i/intersection.png"),
  intimate: require("../../../assets/words/i/intimate.png"),
  introduce: require("../../../assets/words/i/introduce.png"),
  intuition: require("../../../assets/words/i/intuition.png"),
  invade: require("../../../assets/words/i/invade.png"),
  invader: require("../../../assets/words/i/invader.png"),
  invent: require("../../../assets/words/i/invent.png"),
  invest: require("../../../assets/words/i/invest.png"),
  investigate: require("../../../assets/words/i/investigate.png"),
  invisible: require("../../../assets/words/i/invisible.png"),
  invitation: require("../../../assets/words/i/invitation.png"),
  invite: require("../../../assets/words/i/invite.png"),
  involve: require("../../../assets/words/i/involve.png"),
  iron: require("../../../assets/words/i/iron.png"),
  island: require("../../../assets/words/i/island.png"),
  isolate: require("../../../assets/words/i/isolate.png"),
  issue: require("../../../assets/words/i/issue.png"),
  ivy: require("../../../assets/words/i/ivy.png"),
};
