import { ImageSourcePropType } from "react-native";

// "l" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_L: Record<string, ImageSourcePropType> = {
  label: require("../../../assets/words/l/label.png"),
  labor: require("../../../assets/words/l/labor.png"),
  laboratory: require("../../../assets/words/l/laboratory.png"),
  lack: require("../../../assets/words/l/lack.png"),
  lacking: require("../../../assets/words/l/lacking.png"),
  lamb: require("../../../assets/words/l/lamb.png"),
  lament: require("../../../assets/words/l/lament.png"),
  landfill: require("../../../assets/words/l/landfill.png"),
  landscape: require("../../../assets/words/l/landscape.png"),
  language: require("../../../assets/words/l/language.png"),
  lantern: require("../../../assets/words/l/lantern.png"),
  largely: require("../../../assets/words/l/largely.png"),
  last: require("../../../assets/words/l/last.png"),
  later: require("../../../assets/words/l/later.png"),
  latitude: require("../../../assets/words/l/latitude.png"),
  launch: require("../../../assets/words/l/launch.png"),
  laundry: require("../../../assets/words/l/laundry.png"),
  law: require("../../../assets/words/l/law.png"),
  lay: require("../../../assets/words/l/lay.png"),
  "lay down": require("../../../assets/words/l/lay-down.png"),
  layer: require("../../../assets/words/l/layer.png"),
  lead: require("../../../assets/words/l/lead.png"),
  "lead to": require("../../../assets/words/l/lead-to.png"),
  leading: require("../../../assets/words/l/leading.png"),
  league: require("../../../assets/words/l/league.png"),
  leak: require("../../../assets/words/l/leak.png"),
  lean: require("../../../assets/words/l/lean.png"),
  leap: require("../../../assets/words/l/leap.png"),
  lease: require("../../../assets/words/l/lease.png"),
  least: require("../../../assets/words/l/least.png"),
  lecture: require("../../../assets/words/l/lecture.png"),
  leftover: require("../../../assets/words/l/leftover.png"),
  legal: require("../../../assets/words/l/legal.png"),
  legally: require("../../../assets/words/l/legally.png"),
  legend: require("../../../assets/words/l/legend.png"),
  legislation: require("../../../assets/words/l/legislation.png"),
  legitimacy: require("../../../assets/words/l/legitimacy.png"),
  legitimate: require("../../../assets/words/l/legitimate.png"),
  leisure: require("../../../assets/words/l/leisure.png"),
  leisurely: require("../../../assets/words/l/leisurely.png"),
  lend: require("../../../assets/words/l/lend.png"),
  lessen: require("../../../assets/words/l/lessen.png"),
  lesson: require("../../../assets/words/l/lesson.png"),
  letter: require("../../../assets/words/l/letter.png"),
  level: require("../../../assets/words/l/level.png"),
  liberate: require("../../../assets/words/l/liberate.png"),
  liberty: require("../../../assets/words/l/liberty.png"),
  library: require("../../../assets/words/l/library.png"),
  license: require("../../../assets/words/l/license.png"),
  lie: require("../../../assets/words/l/lie.png"),
  life: require("../../../assets/words/l/life.png"),
  lift: require("../../../assets/words/l/lift.png"),
  lighthouse: require("../../../assets/words/l/lighthouse.png"),
  likelihood: require("../../../assets/words/l/likelihood.png"),
  likely: require("../../../assets/words/l/likely.png"),
  likeness: require("../../../assets/words/l/likeness.png"),
  likewise: require("../../../assets/words/l/likewise.png"),
  limit: require("../../../assets/words/l/limit.png"),
  link: require("../../../assets/words/l/link.png"),
  liquid: require("../../../assets/words/l/liquid.png"),
  list: require("../../../assets/words/l/list.png"),
  literature: require("../../../assets/words/l/literature.png"),
  "little by little": require("../../../assets/words/l/little-by-little.png"),
  lively: require("../../../assets/words/l/lively.png"),
  livestock: require("../../../assets/words/l/livestock.png"),
  "living room": require("../../../assets/words/l/living-room.png"),
  load: require("../../../assets/words/l/load.png"),
  loaf: require("../../../assets/words/l/loaf.png"),
  loan: require("../../../assets/words/l/loan.png"),
  local: require("../../../assets/words/l/local.png"),
  locale: require("../../../assets/words/l/locale.png"),
  locality: require("../../../assets/words/l/locality.png"),
  locally: require("../../../assets/words/l/locally.png"),
  locate: require("../../../assets/words/l/locate.png"),
  location: require("../../../assets/words/l/location.png"),
  lock: require("../../../assets/words/l/lock.png"),
  log: require("../../../assets/words/l/log.png"),
  logic: require("../../../assets/words/l/logic.png"),
  logical: require("../../../assets/words/l/logical.png"),
  lonely: require("../../../assets/words/l/lonely.png"),
  long: require("../../../assets/words/l/long.png"),
  look: require("../../../assets/words/l/look.png"),
  "look after": require("../../../assets/words/l/look-after.png"),
  "look back on": require("../../../assets/words/l/look-back-on.png"),
  "look for": require("../../../assets/words/l/look-for.png"),
  "look forward to": require("../../../assets/words/l/look-forward-to.png"),
  "look into": require("../../../assets/words/l/look-into.png"),
  "look up": require("../../../assets/words/l/look-up.png"),
  loom: require("../../../assets/words/l/loom.png"),
  loose: require("../../../assets/words/l/loose.png"),
  loosen: require("../../../assets/words/l/loosen.png"),
  lose: require("../../../assets/words/l/lose.png"),
  "lose sight of": require("../../../assets/words/l/lose-sight-of.png"),
  loss: require("../../../assets/words/l/loss.png"),
  loud: require("../../../assets/words/l/loud.png"),
  low: require("../../../assets/words/l/low.png"),
  lower: require("../../../assets/words/l/lower.png"),
  loyal: require("../../../assets/words/l/loyal.png"),
  luck: require("../../../assets/words/l/luck.png"),
  luxury: require("../../../assets/words/l/luxury.png"),
  lyric: require("../../../assets/words/l/lyric.png"),
};
