import { ImageSourcePropType } from "react-native";

// "l" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_L: Record<string, ImageSourcePropType> = {
  label: require("../../../assets/words/l/label.png"),
  labor: require("../../../assets/words/l/labor.png"),
  laboratory: require("../../../assets/words/l/laboratory.png"),
  lack: require("../../../assets/words/l/lack.png"),
  lacking: require("../../../assets/words/l/lacking.png"),
  lamb: require("../../../assets/words/l/lamb.png"),
  landscape: require("../../../assets/words/l/landscape.png"),
  language: require("../../../assets/words/l/language.png"),
  lantern: require("../../../assets/words/l/lantern.png"),
  later: require("../../../assets/words/l/later.png"),
  launch: require("../../../assets/words/l/launch.png"),
  laundry: require("../../../assets/words/l/laundry.png"),
  law: require("../../../assets/words/l/law.png"),
  lay: require("../../../assets/words/l/lay.png"),
  layer: require("../../../assets/words/l/layer.png"),
  lead: require("../../../assets/words/l/lead.png"),
  "lead to": require("../../../assets/words/l/lead-to.png"),
  league: require("../../../assets/words/l/league.png"),
  leak: require("../../../assets/words/l/leak.png"),
  lean: require("../../../assets/words/l/lean.png"),
  leap: require("../../../assets/words/l/leap.png"),
  least: require("../../../assets/words/l/least.png"),
  lecture: require("../../../assets/words/l/lecture.png"),
  leftover: require("../../../assets/words/l/leftover.png"),
  legal: require("../../../assets/words/l/legal.png"),
  legend: require("../../../assets/words/l/legend.png"),
  legislation: require("../../../assets/words/l/legislation.png"),
  leisure: require("../../../assets/words/l/leisure.png"),
  lend: require("../../../assets/words/l/lend.png"),
  lesson: require("../../../assets/words/l/lesson.png"),
  letter: require("../../../assets/words/l/letter.png"),
  level: require("../../../assets/words/l/level.png"),
  liberty: require("../../../assets/words/l/liberty.png"),
  library: require("../../../assets/words/l/library.png"),
  license: require("../../../assets/words/l/license.png"),
  lie: require("../../../assets/words/l/lie.png"),
  life: require("../../../assets/words/l/life.png"),
  lift: require("../../../assets/words/l/lift.png"),
  lighthouse: require("../../../assets/words/l/lighthouse.png"),
  likely: require("../../../assets/words/l/likely.png"),
  likewise: require("../../../assets/words/l/likewise.png"),
  limit: require("../../../assets/words/l/limit.png"),
  liquid: require("../../../assets/words/l/liquid.png"),
  list: require("../../../assets/words/l/list.png"),
  literature: require("../../../assets/words/l/literature.png"),
  "little by little": require("../../../assets/words/l/little-by-little.png"),
  "living room": require("../../../assets/words/l/living-room.png"),
  load: require("../../../assets/words/l/load.png"),
  loaf: require("../../../assets/words/l/loaf.png"),
  local: require("../../../assets/words/l/local.png"),
  locate: require("../../../assets/words/l/locate.png"),
  location: require("../../../assets/words/l/location.png"),
  lock: require("../../../assets/words/l/lock.png"),
  log: require("../../../assets/words/l/log.png"),
  logic: require("../../../assets/words/l/logic.png"),
  logical: require("../../../assets/words/l/logical.png"),
  lonely: require("../../../assets/words/l/lonely.png"),
  "look after": require("../../../assets/words/l/look-after.png"),
  "look back on": require("../../../assets/words/l/look-back-on.png"),
  "look for": require("../../../assets/words/l/look-for.png"),
  "look forward to": require("../../../assets/words/l/look-forward-to.png"),
  "look into": require("../../../assets/words/l/look-into.png"),
  "look up": require("../../../assets/words/l/look-up.png"),
  loose: require("../../../assets/words/l/loose.png"),
  lose: require("../../../assets/words/l/lose.png"),
  loss: require("../../../assets/words/l/loss.png"),
  loud: require("../../../assets/words/l/loud.png"),
  low: require("../../../assets/words/l/low.png"),
  lower: require("../../../assets/words/l/lower.png"),
  loyal: require("../../../assets/words/l/loyal.png"),
  luck: require("../../../assets/words/l/luck.png"),
  luxury: require("../../../assets/words/l/luxury.png"),
  lyric: require("../../../assets/words/l/lyric.png"),
};
