import { ImageSourcePropType } from "react-native";

// "m" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_M: Record<string, ImageSourcePropType> = {
  machine: require("../../../assets/words/m/machine.png"),
  machinery: require("../../../assets/words/m/machinery.png"),
  "made up of": require("../../../assets/words/m/made-up-of.png"),
  magazine: require("../../../assets/words/m/magazine.png"),
  magnet: require("../../../assets/words/m/magnet.png"),
  magnificence: require("../../../assets/words/m/magnificence.png"),
  magnificent: require("../../../assets/words/m/magnificent.png"),
  magnify: require("../../../assets/words/m/magnify.png"),
  magnitude: require("../../../assets/words/m/magnitude.png"),
  mail: require("../../../assets/words/m/mail.png"),
  main: require("../../../assets/words/m/main.png"),
  mainly: require("../../../assets/words/m/mainly.png"),
  maintain: require("../../../assets/words/m/maintain.png"),
  major: require("../../../assets/words/m/major.png"),
  "make a decision": require("../../../assets/words/m/make-a-decision.png"),
  "make sense": require("../../../assets/words/m/make-sense.png"),
  "make sure": require("../../../assets/words/m/make-sure.png"),
  "make up": require("../../../assets/words/m/make-up.png"),
  "make up for": require("../../../assets/words/m/make-up-for.png"),
  male: require("../../../assets/words/m/male.png"),
  mammal: require("../../../assets/words/m/mammal.png"),
  manage: require("../../../assets/words/m/manage.png"),
  manageable: require("../../../assets/words/m/manageable.png"),
  manipulate: require("../../../assets/words/m/manipulate.png"),
  manipulation: require("../../../assets/words/m/manipulation.png"),
  mankind: require("../../../assets/words/m/mankind.png"),
  manner: require("../../../assets/words/m/manner.png"),
  manual: require("../../../assets/words/m/manual.png"),
  manufacture: require("../../../assets/words/m/manufacture.png"),
  manufactured: require("../../../assets/words/m/manufactured.png"),
  marble: require("../../../assets/words/m/marble.png"),
  march: require("../../../assets/words/m/march.png"),
  margin: require("../../../assets/words/m/margin.png"),
  marine: require("../../../assets/words/m/marine.png"),
  mark: require("../../../assets/words/m/mark.png"),
  marked: require("../../../assets/words/m/marked.png"),
  markedly: require("../../../assets/words/m/markedly.png"),
  marry: require("../../../assets/words/m/marry.png"),
  mars: require("../../../assets/words/m/mars.png"),
  marvel: require("../../../assets/words/m/marvel.png"),
  mask: require("../../../assets/words/m/mask.png"),
  mass: require("../../../assets/words/m/mass.png"),
  "mass communication": require("../../../assets/words/m/mass-communication.png"),
  massive: require("../../../assets/words/m/massive.png"),
  master: require("../../../assets/words/m/master.png"),
  masterpiece: require("../../../assets/words/m/masterpiece.png"),
  mastery: require("../../../assets/words/m/mastery.png"),
  match: require("../../../assets/words/m/match.png"),
  material: require("../../../assets/words/m/material.png"),
  math: require("../../../assets/words/m/math.png"),
  mathematics: require("../../../assets/words/m/mathematics.png"),
  matter: require("../../../assets/words/m/matter.png"),
  mature: require("../../../assets/words/m/mature.png"),
  maturity: require("../../../assets/words/m/maturity.png"),
  maximum: require("../../../assets/words/m/maximum.png"),
  maybe: require("../../../assets/words/m/maybe.png"),
  mayor: require("../../../assets/words/m/mayor.png"),
  mean: require("../../../assets/words/m/mean.png"),
  meaning: require("../../../assets/words/m/meaning.png"),
  meaningful: require("../../../assets/words/m/meaningful.png"),
  means: require("../../../assets/words/m/means.png"),
  meanwhile: require("../../../assets/words/m/meanwhile.png"),
  measure: require("../../../assets/words/m/measure.png"),
  meat: require("../../../assets/words/m/meat.png"),
  mechanic: require("../../../assets/words/m/mechanic.png"),
  mechanical: require("../../../assets/words/m/mechanical.png"),
  mediation: require("../../../assets/words/m/mediation.png"),
  medical: require("../../../assets/words/m/medical.png"),
  medicine: require("../../../assets/words/m/medicine.png"),
  medieval: require("../../../assets/words/m/medieval.png"),
  meditation: require("../../../assets/words/m/meditation.png"),
  medium: require("../../../assets/words/m/medium.png"),
  melt: require("../../../assets/words/m/melt.png"),
  memorize: require("../../../assets/words/m/memorize.png"),
  memory: require("../../../assets/words/m/memory.png"),
  mental: require("../../../assets/words/m/mental.png"),
  mention: require("../../../assets/words/m/mention.png"),
  merchandise: require("../../../assets/words/m/merchandise.png"),
  merchant: require("../../../assets/words/m/merchant.png"),
  mercy: require("../../../assets/words/m/mercy.png"),
  mere: require("../../../assets/words/m/mere.png"),
  merger: require("../../../assets/words/m/merger.png"),
  merry: require("../../../assets/words/m/merry.png"),
  metal: require("../../../assets/words/m/metal.png"),
  metaphor: require("../../../assets/words/m/metaphor.png"),
  method: require("../../../assets/words/m/method.png"),
  microscope: require("../../../assets/words/m/microscope.png"),
  might: require("../../../assets/words/m/might.png"),
  migrate: require("../../../assets/words/m/migrate.png"),
  mild: require("../../../assets/words/m/mild.png"),
  mile: require("../../../assets/words/m/mile.png"),
  military: require("../../../assets/words/m/military.png"),
  million: require("../../../assets/words/m/million.png"),
  mind: require("../../../assets/words/m/mind.png"),
  mine: require("../../../assets/words/m/mine.png"),
  mineral: require("../../../assets/words/m/mineral.png"),
  minimize: require("../../../assets/words/m/minimize.png"),
  minimum: require("../../../assets/words/m/minimum.png"),
  minister: require("../../../assets/words/m/minister.png"),
  minority: require("../../../assets/words/m/minority.png"),
  minute: require("../../../assets/words/m/minute.png"),
  miracle: require("../../../assets/words/m/miracle.png"),
  miserable: require("../../../assets/words/m/miserable.png"),
  miss: require("../../../assets/words/m/miss.png"),
  missionary: require("../../../assets/words/m/missionary.png"),
  mistake: require("../../../assets/words/m/mistake.png"),
  misunderstanding: require("../../../assets/words/m/misunderstanding.png"),
  mixture: require("../../../assets/words/m/mixture.png"),
  mobile: require("../../../assets/words/m/mobile.png"),
  moderate: require("../../../assets/words/m/moderate.png"),
  modern: require("../../../assets/words/m/modern.png"),
  modest: require("../../../assets/words/m/modest.png"),
  modify: require("../../../assets/words/m/modify.png"),
  moisture: require("../../../assets/words/m/moisture.png"),
  moment: require("../../../assets/words/m/moment.png"),
  monitor: require("../../../assets/words/m/monitor.png"),
  monk: require("../../../assets/words/m/monk.png"),
  monotonous: require("../../../assets/words/m/monotonous.png"),
  monument: require("../../../assets/words/m/monument.png"),
  mop: require("../../../assets/words/m/mop.png"),
  moral: require("../../../assets/words/m/moral.png"),
  moreover: require("../../../assets/words/m/moreover.png"),
  "most of all": require("../../../assets/words/m/most-of-all.png"),
  mostly: require("../../../assets/words/m/mostly.png"),
  motivate: require("../../../assets/words/m/motivate.png"),
  mount: require("../../../assets/words/m/mount.png"),
  mouse: require("../../../assets/words/m/mouse.png"),
  "move on": require("../../../assets/words/m/move-on.png"),
  movement: require("../../../assets/words/m/movement.png"),
  multiple: require("../../../assets/words/m/multiple.png"),
  murder: require("../../../assets/words/m/murder.png"),
  muscle: require("../../../assets/words/m/muscle.png"),
  museum: require("../../../assets/words/m/museum.png"),
  musician: require("../../../assets/words/m/musician.png"),
  mutual: require("../../../assets/words/m/mutual.png"),
  mystery: require("../../../assets/words/m/mystery.png"),
  myth: require("../../../assets/words/m/myth.png"),
};
