import { ImageSourcePropType } from "react-native";

// "m" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_M: Record<string, ImageSourcePropType> = {
  machine: require("../../../assets/words/m/machine.png"),
  magazine: require("../../../assets/words/m/magazine.png"),
  mail: require("../../../assets/words/m/mail.png"),
  main: require("../../../assets/words/m/main.png"),
  mammal: require("../../../assets/words/m/mammal.png"),
  mankind: require("../../../assets/words/m/mankind.png"),
  marble: require("../../../assets/words/m/marble.png"),
  march: require("../../../assets/words/m/march.png"),
  marine: require("../../../assets/words/m/marine.png"),
  marry: require("../../../assets/words/m/marry.png"),
  mars: require("../../../assets/words/m/mars.png"),
  "mass communication": require("../../../assets/words/m/mass-communication.png"),
  master: require("../../../assets/words/m/master.png"),
  match: require("../../../assets/words/m/match.png"),
  material: require("../../../assets/words/m/material.png"),
  math: require("../../../assets/words/m/math.png"),
  matter: require("../../../assets/words/m/matter.png"),
  maybe: require("../../../assets/words/m/maybe.png"),
  mayor: require("../../../assets/words/m/mayor.png"),
  meanwhile: require("../../../assets/words/m/meanwhile.png"),
  meat: require("../../../assets/words/m/meat.png"),
  mechanic: require("../../../assets/words/m/mechanic.png"),
  melt: require("../../../assets/words/m/melt.png"),
  memory: require("../../../assets/words/m/memory.png"),
  mental: require("../../../assets/words/m/mental.png"),
  mention: require("../../../assets/words/m/mention.png"),
  merchant: require("../../../assets/words/m/merchant.png"),
  merry: require("../../../assets/words/m/merry.png"),
  metal: require("../../../assets/words/m/metal.png"),
  method: require("../../../assets/words/m/method.png"),
  might: require("../../../assets/words/m/might.png"),
  mild: require("../../../assets/words/m/mild.png"),
  mile: require("../../../assets/words/m/mile.png"),
  military: require("../../../assets/words/m/military.png"),
  million: require("../../../assets/words/m/million.png"),
  mind: require("../../../assets/words/m/mind.png"),
  minute: require("../../../assets/words/m/minute.png"),
  miss: require("../../../assets/words/m/miss.png"),
  mistake: require("../../../assets/words/m/mistake.png"),
  modern: require("../../../assets/words/m/modern.png"),
  moment: require("../../../assets/words/m/moment.png"),
  monk: require("../../../assets/words/m/monk.png"),
  monument: require("../../../assets/words/m/monument.png"),
  mostly: require("../../../assets/words/m/mostly.png"),
  mouse: require("../../../assets/words/m/mouse.png"),
  multiple: require("../../../assets/words/m/multiple.png"),
  museum: require("../../../assets/words/m/museum.png"),
  musician: require("../../../assets/words/m/musician.png"),
  mystery: require("../../../assets/words/m/mystery.png"),
};
