import { ImageSourcePropType } from "react-native";

// "n" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_N: Record<string, ImageSourcePropType> = {
  nail: require("../../../assets/words/n/nail.png"),
  naked: require("../../../assets/words/n/naked.png"),
  narrative: require("../../../assets/words/n/narrative.png"),
  narrator: require("../../../assets/words/n/narrator.png"),
  narrow: require("../../../assets/words/n/narrow.png"),
  nasty: require("../../../assets/words/n/nasty.png"),
  natal: require("../../../assets/words/n/natal.png"),
  nation: require("../../../assets/words/n/nation.png"),
  native: require("../../../assets/words/n/native.png"),
  natural: require("../../../assets/words/n/natural.png"),
  nature: require("../../../assets/words/n/nature.png"),
  navigate: require("../../../assets/words/n/navigate.png"),
  navy: require("../../../assets/words/n/navy.png"),
  nearly: require("../../../assets/words/n/nearly.png"),
  neat: require("../../../assets/words/n/neat.png"),
  necessary: require("../../../assets/words/n/necessary.png"),
  necessity: require("../../../assets/words/n/necessity.png"),
  need: require("../../../assets/words/n/need.png"),
  needle: require("../../../assets/words/n/needle.png"),
  "needless to say": require("../../../assets/words/n/needless-to-say.png"),
  negative: require("../../../assets/words/n/negative.png"),
  neglect: require("../../../assets/words/n/neglect.png"),
  negotiate: require("../../../assets/words/n/negotiate.png"),
  negotiation: require("../../../assets/words/n/negotiation.png"),
  neighbor: require("../../../assets/words/n/neighbor.png"),
  neighboring: require("../../../assets/words/n/neighboring.png"),
  neither: require("../../../assets/words/n/neither.png"),
  nephew: require("../../../assets/words/n/nephew.png"),
  nervous: require("../../../assets/words/n/nervous.png"),
  nest: require("../../../assets/words/n/nest.png"),
  net: require("../../../assets/words/n/net.png"),
  network: require("../../../assets/words/n/network.png"),
  neutral: require("../../../assets/words/n/neutral.png"),
  nevertheless: require("../../../assets/words/n/nevertheless.png"),
  nickname: require("../../../assets/words/n/nickname.png"),
  niece: require("../../../assets/words/n/niece.png"),
  "no longer": require("../../../assets/words/n/no-longer.png"),
  "no smoking section": require("../../../assets/words/n/no-smoking-section.png"),
  noble: require("../../../assets/words/n/noble.png"),
  nod: require("../../../assets/words/n/nod.png"),
  noise: require("../../../assets/words/n/noise.png"),
  none: require("../../../assets/words/n/none.png"),
  norm: require("../../../assets/words/n/norm.png"),
  normal: require("../../../assets/words/n/normal.png"),
  northern: require("../../../assets/words/n/northern.png"),
  notable: require("../../../assets/words/n/notable.png"),
  notice: require("../../../assets/words/n/notice.png"),
  notion: require("../../../assets/words/n/notion.png"),
  nourish: require("../../../assets/words/n/nourish.png"),
  novel: require("../../../assets/words/n/novel.png"),
  "now that": require("../../../assets/words/n/now-that.png"),
  nuclear: require("../../../assets/words/n/nuclear.png"),
  numerous: require("../../../assets/words/n/numerous.png"),
  nurse: require("../../../assets/words/n/nurse.png"),
  nurture: require("../../../assets/words/n/nurture.png"),
  nutrition: require("../../../assets/words/n/nutrition.png"),
};
