import { ImageSourcePropType } from "react-native";

// "n" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_N: Record<string, ImageSourcePropType> = {
  nail: require("../../../assets/words/n/nail.png"),
  naked: require("../../../assets/words/n/naked.png"),
  name: require("../../../assets/words/n/name.png"),
  narrative: require("../../../assets/words/n/narrative.png"),
  narrator: require("../../../assets/words/n/narrator.png"),
  narrow: require("../../../assets/words/n/narrow.png"),
  nasty: require("../../../assets/words/n/nasty.png"),
  natal: require("../../../assets/words/n/natal.png"),
  nation: require("../../../assets/words/n/nation.png"),
  nationality: require("../../../assets/words/n/nationality.png"),
  native: require("../../../assets/words/n/native.png"),
  natural: require("../../../assets/words/n/natural.png"),
  naturally: require("../../../assets/words/n/naturally.png"),
  nature: require("../../../assets/words/n/nature.png"),
  naughty: require("../../../assets/words/n/naughty.png"),
  navigate: require("../../../assets/words/n/navigate.png"),
  navy: require("../../../assets/words/n/navy.png"),
  near: require("../../../assets/words/n/near.png"),
  nearby: require("../../../assets/words/n/nearby.png"),
  nearly: require("../../../assets/words/n/nearly.png"),
  neat: require("../../../assets/words/n/neat.png"),
  necessary: require("../../../assets/words/n/necessary.png"),
  necessity: require("../../../assets/words/n/necessity.png"),
  neck: require("../../../assets/words/n/neck.png"),
  necktie: require("../../../assets/words/n/necktie.png"),
  nectar: require("../../../assets/words/n/nectar.png"),
  need: require("../../../assets/words/n/need.png"),
  needle: require("../../../assets/words/n/needle.png"),
  "needless to say": require("../../../assets/words/n/needless-to-say.png"),
  negative: require("../../../assets/words/n/negative.png"),
  neglect: require("../../../assets/words/n/neglect.png"),
  negotiate: require("../../../assets/words/n/negotiate.png"),
  negotiation: require("../../../assets/words/n/negotiation.png"),
  neighbor: require("../../../assets/words/n/neighbor.png"),
  neighborhood: require("../../../assets/words/n/neighborhood.png"),
  neighboring: require("../../../assets/words/n/neighboring.png"),
  neither: require("../../../assets/words/n/neither.png"),
  nephew: require("../../../assets/words/n/nephew.png"),
  nerve: require("../../../assets/words/n/nerve.png"),
  nervous: require("../../../assets/words/n/nervous.png"),
  nest: require("../../../assets/words/n/nest.png"),
  net: require("../../../assets/words/n/net.png"),
  network: require("../../../assets/words/n/network.png"),
  neutral: require("../../../assets/words/n/neutral.png"),
  nevertheless: require("../../../assets/words/n/nevertheless.png"),
  new: require("../../../assets/words/n/new.png"),
  news: require("../../../assets/words/n/news.png"),
  newsletter: require("../../../assets/words/n/newsletter.png"),
  newspaper: require("../../../assets/words/n/newspaper.png"),
  "next door": require("../../../assets/words/n/next-door.png"),
  "next time": require("../../../assets/words/n/next-time.png"),
  "next week": require("../../../assets/words/n/next-week.png"),
  "next year": require("../../../assets/words/n/next-year.png"),
  niche: require("../../../assets/words/n/niche.png"),
  nickel: require("../../../assets/words/n/nickel.png"),
  nickname: require("../../../assets/words/n/nickname.png"),
  niece: require("../../../assets/words/n/niece.png"),
  night: require("../../../assets/words/n/night.png"),
  nightly: require("../../../assets/words/n/nightly.png"),
  "no longer": require("../../../assets/words/n/no-longer.png"),
  "no smoking section": require("../../../assets/words/n/no-smoking-section.png"),
  noble: require("../../../assets/words/n/noble.png"),
  nod: require("../../../assets/words/n/nod.png"),
  noise: require("../../../assets/words/n/noise.png"),
  nomadic: require("../../../assets/words/n/nomadic.png"),
  nominate: require("../../../assets/words/n/nominate.png"),
  "non-committal": require("../../../assets/words/n/non-committal.png"),
  none: require("../../../assets/words/n/none.png"),
  nonetheless: require("../../../assets/words/n/nonetheless.png"),
  noon: require("../../../assets/words/n/noon.png"),
  norm: require("../../../assets/words/n/norm.png"),
  normal: require("../../../assets/words/n/normal.png"),
  normally: require("../../../assets/words/n/normally.png"),
  northern: require("../../../assets/words/n/northern.png"),
  nose: require("../../../assets/words/n/nose.png"),
  "not at all": require("../../../assets/words/n/not-at-all.png"),
  "not much": require("../../../assets/words/n/not-much.png"),
  notable: require("../../../assets/words/n/notable.png"),
  notably: require("../../../assets/words/n/notably.png"),
  notation: require("../../../assets/words/n/notation.png"),
  note: require("../../../assets/words/n/note.png"),
  noted: require("../../../assets/words/n/noted.png"),
  noteworthy: require("../../../assets/words/n/noteworthy.png"),
  notice: require("../../../assets/words/n/notice.png"),
  noticeable: require("../../../assets/words/n/noticeable.png"),
  notification: require("../../../assets/words/n/notification.png"),
  notify: require("../../../assets/words/n/notify.png"),
  notion: require("../../../assets/words/n/notion.png"),
  notwithstanding: require("../../../assets/words/n/notwithstanding.png"),
  nourish: require("../../../assets/words/n/nourish.png"),
  novel: require("../../../assets/words/n/novel.png"),
  novelty: require("../../../assets/words/n/novelty.png"),
  now: require("../../../assets/words/n/now.png"),
  "now that": require("../../../assets/words/n/now-that.png"),
  nowadays: require("../../../assets/words/n/nowadays.png"),
  nuclear: require("../../../assets/words/n/nuclear.png"),
  nuisance: require("../../../assets/words/n/nuisance.png"),
  numerous: require("../../../assets/words/n/numerous.png"),
  nurse: require("../../../assets/words/n/nurse.png"),
  nurture: require("../../../assets/words/n/nurture.png"),
  nutrition: require("../../../assets/words/n/nutrition.png"),
};
