import { ImageSourcePropType } from "react-native";

// "n" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_N: Record<string, ImageSourcePropType> = {
  nail: require("../../../assets/words/n/nail.png"),
  narrow: require("../../../assets/words/n/narrow.png"),
  nasty: require("../../../assets/words/n/nasty.png"),
  nation: require("../../../assets/words/n/nation.png"),
  native: require("../../../assets/words/n/native.png"),
  nature: require("../../../assets/words/n/nature.png"),
  navy: require("../../../assets/words/n/navy.png"),
  nearly: require("../../../assets/words/n/nearly.png"),
  necessary: require("../../../assets/words/n/necessary.png"),
  need: require("../../../assets/words/n/need.png"),
  neglect: require("../../../assets/words/n/neglect.png"),
  neighbor: require("../../../assets/words/n/neighbor.png"),
  neither: require("../../../assets/words/n/neither.png"),
  nephew: require("../../../assets/words/n/nephew.png"),
  nervous: require("../../../assets/words/n/nervous.png"),
  nickname: require("../../../assets/words/n/nickname.png"),
  niece: require("../../../assets/words/n/niece.png"),
  "no longer": require("../../../assets/words/n/no-longer.png"),
  "no smoking section": require("../../../assets/words/n/no-smoking-section.png"),
  noble: require("../../../assets/words/n/noble.png"),
  nod: require("../../../assets/words/n/nod.png"),
  noise: require("../../../assets/words/n/noise.png"),
  none: require("../../../assets/words/n/none.png"),
  normal: require("../../../assets/words/n/normal.png"),
  notice: require("../../../assets/words/n/notice.png"),
  nuclear: require("../../../assets/words/n/nuclear.png"),
  numerous: require("../../../assets/words/n/numerous.png"),
  nurse: require("../../../assets/words/n/nurse.png"),
};
