import { ImageSourcePropType } from "react-native";

// "o" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_O: Record<string, ImageSourcePropType> = {
  oath: require("../../../assets/words/o/oath.png"),
  obedient: require("../../../assets/words/o/obedient.png"),
  obey: require("../../../assets/words/o/obey.png"),
  object: require("../../../assets/words/o/object.png"),
  objective: require("../../../assets/words/o/objective.png"),
  obliged: require("../../../assets/words/o/obliged.png"),
  obscure: require("../../../assets/words/o/obscure.png"),
  observably: require("../../../assets/words/o/observably.png"),
  observe: require("../../../assets/words/o/observe.png"),
  obsess: require("../../../assets/words/o/obsess.png"),
  obstacle: require("../../../assets/words/o/obstacle.png"),
  obstruct: require("../../../assets/words/o/obstruct.png"),
  obtain: require("../../../assets/words/o/obtain.png"),
  obtainable: require("../../../assets/words/o/obtainable.png"),
  obvious: require("../../../assets/words/o/obvious.png"),
  occasion: require("../../../assets/words/o/occasion.png"),
  occasional: require("../../../assets/words/o/occasional.png"),
  occupation: require("../../../assets/words/o/occupation.png"),
  occupy: require("../../../assets/words/o/occupy.png"),
  occur: require("../../../assets/words/o/occur.png"),
  ocean: require("../../../assets/words/o/ocean.png"),
  odd: require("../../../assets/words/o/odd.png"),
  "of high priority": require("../../../assets/words/o/of-high-priority.png"),
  "of the essence": require("../../../assets/words/o/of-the-essence.png"),
  offend: require("../../../assets/words/o/offend.png"),
  offense: require("../../../assets/words/o/offense.png"),
  offer: require("../../../assets/words/o/offer.png"),
  office: require("../../../assets/words/o/office.png"),
  officer: require("../../../assets/words/o/officer.png"),
  official: require("../../../assets/words/o/official.png"),
  offspring: require("../../../assets/words/o/offspring.png"),
  "on occasion": require("../../../assets/words/o/on-occasion.png"),
  "on one’s feet": require("../../../assets/words/o/on-one’s-feet.png"),
  "on the contrary": require("../../../assets/words/o/on-the-contrary.png"),
  "on the other hand": require("../../../assets/words/o/on-the-other-hand.png"),
  "on the whole": require("../../../assets/words/o/on-the-whole.png"),
  once: require("../../../assets/words/o/once.png"),
  "once in a while": require("../../../assets/words/o/once-in-a-while.png"),
  online: require("../../../assets/words/o/online.png"),
  operate: require("../../../assets/words/o/operate.png"),
  operator: require("../../../assets/words/o/operator.png"),
  opinion: require("../../../assets/words/o/opinion.png"),
  opponent: require("../../../assets/words/o/opponent.png"),
  opportunity: require("../../../assets/words/o/opportunity.png"),
  oppose: require("../../../assets/words/o/oppose.png"),
  opposed: require("../../../assets/words/o/opposed.png"),
  opposite: require("../../../assets/words/o/opposite.png"),
  oppressive: require("../../../assets/words/o/oppressive.png"),
  optimal: require("../../../assets/words/o/optimal.png"),
  optimistic: require("../../../assets/words/o/optimistic.png"),
  oral: require("../../../assets/words/o/oral.png"),
  orbit: require("../../../assets/words/o/orbit.png"),
  orchard: require("../../../assets/words/o/orchard.png"),
  order: require("../../../assets/words/o/order.png"),
  ordinarily: require("../../../assets/words/o/ordinarily.png"),
  ordinary: require("../../../assets/words/o/ordinary.png"),
  organ: require("../../../assets/words/o/organ.png"),
  organic: require("../../../assets/words/o/organic.png"),
  organism: require("../../../assets/words/o/organism.png"),
  organization: require("../../../assets/words/o/organization.png"),
  organize: require("../../../assets/words/o/organize.png"),
  origin: require("../../../assets/words/o/origin.png"),
  originate: require("../../../assets/words/o/originate.png"),
  ornament: require("../../../assets/words/o/ornament.png"),
  orphan: require("../../../assets/words/o/orphan.png"),
  ostrich: require("../../../assets/words/o/ostrich.png"),
  "other than": require("../../../assets/words/o/other-than.png"),
  otherwise: require("../../../assets/words/o/otherwise.png"),
  outbreak: require("../../../assets/words/o/outbreak.png"),
  outburst: require("../../../assets/words/o/outburst.png"),
  outcome: require("../../../assets/words/o/outcome.png"),
  outdated: require("../../../assets/words/o/outdated.png"),
  outdo: require("../../../assets/words/o/outdo.png"),
  outfit: require("../../../assets/words/o/outfit.png"),
  outlet: require("../../../assets/words/o/outlet.png"),
  outline: require("../../../assets/words/o/outline.png"),
  output: require("../../../assets/words/o/output.png"),
  outspoken: require("../../../assets/words/o/outspoken.png"),
  outstanding: require("../../../assets/words/o/outstanding.png"),
  oval: require("../../../assets/words/o/oval.png"),
  "over and over": require("../../../assets/words/o/over-and-over.png"),
  overall: require("../../../assets/words/o/overall.png"),
  overcome: require("../../../assets/words/o/overcome.png"),
  overdue: require("../../../assets/words/o/overdue.png"),
  overestimate: require("../../../assets/words/o/overestimate.png"),
  overflow: require("../../../assets/words/o/overflow.png"),
  overhear: require("../../../assets/words/o/overhear.png"),
  overlap: require("../../../assets/words/o/overlap.png"),
  overlook: require("../../../assets/words/o/overlook.png"),
  overnight: require("../../../assets/words/o/overnight.png"),
  overseas: require("../../../assets/words/o/overseas.png"),
  oversee: require("../../../assets/words/o/oversee.png"),
  overstate: require("../../../assets/words/o/overstate.png"),
  overtake: require("../../../assets/words/o/overtake.png"),
  overwhelm: require("../../../assets/words/o/overwhelm.png"),
  overwhelming: require("../../../assets/words/o/overwhelming.png"),
  overwhelmingly: require("../../../assets/words/o/overwhelmingly.png"),
  owe: require("../../../assets/words/o/owe.png"),
  "owing to": require("../../../assets/words/o/owing-to.png"),
  owl: require("../../../assets/words/o/owl.png"),
  own: require("../../../assets/words/o/own.png"),
  ownership: require("../../../assets/words/o/ownership.png"),
  oxygen: require("../../../assets/words/o/oxygen.png"),
};
