import { ImageSourcePropType } from "react-native";

// "o" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_O: Record<string, ImageSourcePropType> = {
  oath: require("../../../assets/words/o/oath.png"),
  obey: require("../../../assets/words/o/obey.png"),
  object: require("../../../assets/words/o/object.png"),
  obsess: require("../../../assets/words/o/obsess.png"),
  obstacle: require("../../../assets/words/o/obstacle.png"),
  obtain: require("../../../assets/words/o/obtain.png"),
  obvious: require("../../../assets/words/o/obvious.png"),
  occur: require("../../../assets/words/o/occur.png"),
  ocean: require("../../../assets/words/o/ocean.png"),
  offer: require("../../../assets/words/o/offer.png"),
  office: require("../../../assets/words/o/office.png"),
  officer: require("../../../assets/words/o/officer.png"),
  official: require("../../../assets/words/o/official.png"),
  once: require("../../../assets/words/o/once.png"),
  online: require("../../../assets/words/o/online.png"),
  operator: require("../../../assets/words/o/operator.png"),
  opinion: require("../../../assets/words/o/opinion.png"),
  opportunity: require("../../../assets/words/o/opportunity.png"),
  orbit: require("../../../assets/words/o/orbit.png"),
  order: require("../../../assets/words/o/order.png"),
  organism: require("../../../assets/words/o/organism.png"),
  origin: require("../../../assets/words/o/origin.png"),
  orphan: require("../../../assets/words/o/orphan.png"),
  ostrich: require("../../../assets/words/o/ostrich.png"),
  otherwise: require("../../../assets/words/o/otherwise.png"),
  outstanding: require("../../../assets/words/o/outstanding.png"),
  overcome: require("../../../assets/words/o/overcome.png"),
  overestimate: require("../../../assets/words/o/overestimate.png"),
  overhear: require("../../../assets/words/o/overhear.png"),
  overlook: require("../../../assets/words/o/overlook.png"),
  overseas: require("../../../assets/words/o/overseas.png"),
  owe: require("../../../assets/words/o/owe.png"),
  owl: require("../../../assets/words/o/owl.png"),
  own: require("../../../assets/words/o/own.png"),
  oxygen: require("../../../assets/words/o/oxygen.png"),
};
