import { ImageSourcePropType } from "react-native";

// "r" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_R: Record<string, ImageSourcePropType> = {
  race: require("../../../assets/words/r/race.png"),
  raise: require("../../../assets/words/r/raise.png"),
  rapidly: require("../../../assets/words/r/rapidly.png"),
  rate: require("../../../assets/words/r/rate.png"),
  rather: require("../../../assets/words/r/rather.png"),
  reach: require("../../../assets/words/r/reach.png"),
  rear: require("../../../assets/words/r/rear.png"),
  reason: require("../../../assets/words/r/reason.png"),
  receive: require("../../../assets/words/r/receive.png"),
  recently: require("../../../assets/words/r/recently.png"),
  record: require("../../../assets/words/r/record.png"),
  refrigerator: require("../../../assets/words/r/refrigerator.png"),
  refuse: require("../../../assets/words/r/refuse.png"),
  regular: require("../../../assets/words/r/regular.png"),
  rein: require("../../../assets/words/r/rein.png"),
  relative: require("../../../assets/words/r/relative.png"),
  relay: require("../../../assets/words/r/relay.png"),
  religious: require("../../../assets/words/r/religious.png"),
  rely: require("../../../assets/words/r/rely.png"),
  remain: require("../../../assets/words/r/remain.png"),
  remember: require("../../../assets/words/r/remember.png"),
  remind: require("../../../assets/words/r/remind.png"),
  remove: require("../../../assets/words/r/remove.png"),
  repeat: require("../../../assets/words/r/repeat.png"),
  replace: require("../../../assets/words/r/replace.png"),
  reply: require("../../../assets/words/r/reply.png"),
  report: require("../../../assets/words/r/report.png"),
  republic: require("../../../assets/words/r/republic.png"),
  resource: require("../../../assets/words/r/resource.png"),
  resources: require("../../../assets/words/r/resources.png"),
  respect: require("../../../assets/words/r/respect.png"),
  restaurant: require("../../../assets/words/r/restaurant.png"),
  return: require("../../../assets/words/r/return.png"),
  review: require("../../../assets/words/r/review.png"),
  revival: require("../../../assets/words/r/revival.png"),
  revolution: require("../../../assets/words/r/revolution.png"),
  rid: require("../../../assets/words/r/rid.png"),
  riddle: require("../../../assets/words/r/riddle.png"),
  ripe: require("../../../assets/words/r/ripe.png"),
  roar: require("../../../assets/words/r/roar.png"),
  robber: require("../../../assets/words/r/robber.png"),
  roll: require("../../../assets/words/r/roll.png"),
  rope: require("../../../assets/words/r/rope.png"),
  route: require("../../../assets/words/r/route.png"),
  routine: require("../../../assets/words/r/routine.png"),
  row: require("../../../assets/words/r/row.png"),
  rub: require("../../../assets/words/r/rub.png"),
  rudely: require("../../../assets/words/r/rudely.png"),
  ruin: require("../../../assets/words/r/ruin.png"),
  rule: require("../../../assets/words/r/rule.png"),
};
