import { ImageSourcePropType } from "react-native";

// "t" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_T: Record<string, ImageSourcePropType> = {
  tail: require("../../../assets/words/t/tail.png"),
  "take advantage of": require("../../../assets/words/t/take-advantage-of.png"),
  "take part in": require("../../../assets/words/t/take-part-in.png"),
  "take ~ for granted": require("../../../assets/words/t/take-~-for-granted.png"),
  tale: require("../../../assets/words/t/tale.png"),
  talent: require("../../../assets/words/t/talent.png"),
  target: require("../../../assets/words/t/target.png"),
  task: require("../../../assets/words/t/task.png"),
  taste: require("../../../assets/words/t/taste.png"),
  tax: require("../../../assets/words/t/tax.png"),
  tear: require("../../../assets/words/t/tear.png"),
  tease: require("../../../assets/words/t/tease.png"),
  technique: require("../../../assets/words/t/technique.png"),
  technology: require("../../../assets/words/t/technology.png"),
  teenager: require("../../../assets/words/t/teenager.png"),
  telephone: require("../../../assets/words/t/telephone.png"),
  temperature: require("../../../assets/words/t/temperature.png"),
  temple: require("../../../assets/words/t/temple.png"),
  temporary: require("../../../assets/words/t/temporary.png"),
  tend: require("../../../assets/words/t/tend.png"),
  tension: require("../../../assets/words/t/tension.png"),
  term: require("../../../assets/words/t/term.png"),
  terrible: require("../../../assets/words/t/terrible.png"),
  territory: require("../../../assets/words/t/territory.png"),
  theater: require("../../../assets/words/t/theater.png"),
  theme: require("../../../assets/words/t/theme.png"),
  theory: require("../../../assets/words/t/theory.png"),
  therapy: require("../../../assets/words/t/therapy.png"),
  thermometer: require("../../../assets/words/t/thermometer.png"),
  thief: require("../../../assets/words/t/thief.png"),
  thin: require("../../../assets/words/t/thin.png"),
  thirsty: require("../../../assets/words/t/thirsty.png"),
  thorn: require("../../../assets/words/t/thorn.png"),
  though: require("../../../assets/words/t/though.png"),
  thread: require("../../../assets/words/t/thread.png"),
  threat: require("../../../assets/words/t/threat.png"),
  thrive: require("../../../assets/words/t/thrive.png"),
  throat: require("../../../assets/words/t/throat.png"),
  throw: require("../../../assets/words/t/throw.png"),
  thumb: require("../../../assets/words/t/thumb.png"),
  ticket: require("../../../assets/words/t/ticket.png"),
  tidy: require("../../../assets/words/t/tidy.png"),
  tie: require("../../../assets/words/t/tie.png"),
  tightly: require("../../../assets/words/t/tightly.png"),
  tiny: require("../../../assets/words/t/tiny.png"),
  tip: require("../../../assets/words/t/tip.png"),
  tissue: require("../../../assets/words/t/tissue.png"),
  title: require("../../../assets/words/t/title.png"),
  together: require("../../../assets/words/t/together.png"),
  tomb: require("../../../assets/words/t/tomb.png"),
  tongue: require("../../../assets/words/t/tongue.png"),
  tool: require("../../../assets/words/t/tool.png"),
  tooth: require("../../../assets/words/t/tooth.png"),
  torch: require("../../../assets/words/t/torch.png"),
  total: require("../../../assets/words/t/total.png"),
  touch: require("../../../assets/words/t/touch.png"),
  tough: require("../../../assets/words/t/tough.png"),
  tourist: require("../../../assets/words/t/tourist.png"),
  tournament: require("../../../assets/words/t/tournament.png"),
  toward: require("../../../assets/words/t/toward.png"),
  towel: require("../../../assets/words/t/towel.png"),
  tower: require("../../../assets/words/t/tower.png"),
  town: require("../../../assets/words/t/town.png"),
  trace: require("../../../assets/words/t/trace.png"),
  track: require("../../../assets/words/t/track.png"),
  trade: require("../../../assets/words/t/trade.png"),
  tradition: require("../../../assets/words/t/tradition.png"),
  traffic: require("../../../assets/words/t/traffic.png"),
  tragedy: require("../../../assets/words/t/tragedy.png"),
  transfer: require("../../../assets/words/t/transfer.png"),
  transform: require("../../../assets/words/t/transform.png"),
  translate: require("../../../assets/words/t/translate.png"),
  translation: require("../../../assets/words/t/translation.png"),
  transport: require("../../../assets/words/t/transport.png"),
  transportation: require("../../../assets/words/t/transportation.png"),
  travel: require("../../../assets/words/t/travel.png"),
  tray: require("../../../assets/words/t/tray.png"),
  treasure: require("../../../assets/words/t/treasure.png"),
  treat: require("../../../assets/words/t/treat.png"),
  treatment: require("../../../assets/words/t/treatment.png"),
  tremendous: require("../../../assets/words/t/tremendous.png"),
  trend: require("../../../assets/words/t/trend.png"),
  trial: require("../../../assets/words/t/trial.png"),
  tribe: require("../../../assets/words/t/tribe.png"),
  trick: require("../../../assets/words/t/trick.png"),
  trigger: require("../../../assets/words/t/trigger.png"),
  trim: require("../../../assets/words/t/trim.png"),
  trip: require("../../../assets/words/t/trip.png"),
  triumph: require("../../../assets/words/t/triumph.png"),
  tropical: require("../../../assets/words/t/tropical.png"),
  trouble: require("../../../assets/words/t/trouble.png"),
  trousers: require("../../../assets/words/t/trousers.png"),
  true: require("../../../assets/words/t/true.png"),
  trumpet: require("../../../assets/words/t/trumpet.png"),
  trust: require("../../../assets/words/t/trust.png"),
  tune: require("../../../assets/words/t/tune.png"),
  turkey: require("../../../assets/words/t/turkey.png"),
  turn: require("../../../assets/words/t/turn.png"),
  "turn in": require("../../../assets/words/t/turn-in.png"),
  "turn out": require("../../../assets/words/t/turn-out.png"),
  "turn over": require("../../../assets/words/t/turn-over.png"),
  turtle: require("../../../assets/words/t/turtle.png"),
  twice: require("../../../assets/words/t/twice.png"),
  twin: require("../../../assets/words/t/twin.png"),
  twist: require("../../../assets/words/t/twist.png"),
  type: require("../../../assets/words/t/type.png"),
  typical: require("../../../assets/words/t/typical.png"),
};
