import { ImageSourcePropType } from "react-native";

// "u" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_U: Record<string, ImageSourcePropType> = {
  ultimate: require("../../../assets/words/u/ultimate.png"),
  ultimately: require("../../../assets/words/u/ultimately.png"),
  umbrella: require("../../../assets/words/u/umbrella.png"),
  unambiguous: require("../../../assets/words/u/unambiguous.png"),
  unavoidable: require("../../../assets/words/u/unavoidable.png"),
  unavoidably: require("../../../assets/words/u/unavoidably.png"),
  unbalanced: require("../../../assets/words/u/unbalanced.png"),
  unbearable: require("../../../assets/words/u/unbearable.png"),
  unbearably: require("../../../assets/words/u/unbearably.png"),
  unbelievable: require("../../../assets/words/u/unbelievable.png"),
  unbroken: require("../../../assets/words/u/unbroken.png"),
  uncertain: require("../../../assets/words/u/uncertain.png"),
  unconsciously: require("../../../assets/words/u/unconsciously.png"),
  unconventional: require("../../../assets/words/u/unconventional.png"),
  unconvincing: require("../../../assets/words/u/unconvincing.png"),
  uncover: require("../../../assets/words/u/uncover.png"),
  undergo: require("../../../assets/words/u/undergo.png"),
  underground: require("../../../assets/words/u/underground.png"),
  underlying: require("../../../assets/words/u/underlying.png"),
  underscore: require("../../../assets/words/u/underscore.png"),
  understand: require("../../../assets/words/u/understand.png"),
  undertake: require("../../../assets/words/u/undertake.png"),
  underwater: require("../../../assets/words/u/underwater.png"),
  undoubtedly: require("../../../assets/words/u/undoubtedly.png"),
  unemployment: require("../../../assets/words/u/unemployment.png"),
  unexpected: require("../../../assets/words/u/unexpected.png"),
  unexpectedly: require("../../../assets/words/u/unexpectedly.png"),
  unfair: require("../../../assets/words/u/unfair.png"),
  unforgettable: require("../../../assets/words/u/unforgettable.png"),
  unfortunately: require("../../../assets/words/u/unfortunately.png"),
  unification: require("../../../assets/words/u/unification.png"),
  uniform: require("../../../assets/words/u/uniform.png"),
  unify: require("../../../assets/words/u/unify.png"),
  unintentional: require("../../../assets/words/u/unintentional.png"),
  union: require("../../../assets/words/u/union.png"),
  unique: require("../../../assets/words/u/unique.png"),
  unite: require("../../../assets/words/u/unite.png"),
  unity: require("../../../assets/words/u/unity.png"),
  universal: require("../../../assets/words/u/universal.png"),
  universe: require("../../../assets/words/u/universe.png"),
  university: require("../../../assets/words/u/university.png"),
  unknown: require("../../../assets/words/u/unknown.png"),
  unless: require("../../../assets/words/u/unless.png"),
  unlike: require("../../../assets/words/u/unlike.png"),
  unlikely: require("../../../assets/words/u/unlikely.png"),
  unprecedented: require("../../../assets/words/u/unprecedented.png"),
  unpredictable: require("../../../assets/words/u/unpredictable.png"),
  unusual: require("../../../assets/words/u/unusual.png"),
  unwanted: require("../../../assets/words/u/unwanted.png"),
  "up close": require("../../../assets/words/u/up-close.png"),
  upcoming: require("../../../assets/words/u/upcoming.png"),
  uphold: require("../../../assets/words/u/uphold.png"),
  upset: require("../../../assets/words/u/upset.png"),
  "upside down": require("../../../assets/words/u/upside-down.png"),
  urban: require("../../../assets/words/u/urban.png"),
  urge: require("../../../assets/words/u/urge.png"),
  urgent: require("../../../assets/words/u/urgent.png"),
  useful: require("../../../assets/words/u/useful.png"),
  useless: require("../../../assets/words/u/useless.png"),
  usual: require("../../../assets/words/u/usual.png"),
  usually: require("../../../assets/words/u/usually.png"),
  utilitarian: require("../../../assets/words/u/utilitarian.png"),
  utility: require("../../../assets/words/u/utility.png"),
  utilize: require("../../../assets/words/u/utilize.png"),
  utmost: require("../../../assets/words/u/utmost.png"),
};
