import { ImageSourcePropType } from "react-native";

// "u" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_U: Record<string, ImageSourcePropType> = {
  ultimate: require("../../../assets/words/u/ultimate.png"),
  umbrella: require("../../../assets/words/u/umbrella.png"),
  underground: require("../../../assets/words/u/underground.png"),
  understand: require("../../../assets/words/u/understand.png"),
  underwater: require("../../../assets/words/u/underwater.png"),
  unexpected: require("../../../assets/words/u/unexpected.png"),
  unfair: require("../../../assets/words/u/unfair.png"),
  unfortunately: require("../../../assets/words/u/unfortunately.png"),
  unification: require("../../../assets/words/u/unification.png"),
  uniform: require("../../../assets/words/u/uniform.png"),
  unify: require("../../../assets/words/u/unify.png"),
  union: require("../../../assets/words/u/union.png"),
  unite: require("../../../assets/words/u/unite.png"),
  unity: require("../../../assets/words/u/unity.png"),
  universal: require("../../../assets/words/u/universal.png"),
  universe: require("../../../assets/words/u/universe.png"),
  university: require("../../../assets/words/u/university.png"),
  unless: require("../../../assets/words/u/unless.png"),
  unlike: require("../../../assets/words/u/unlike.png"),
  "up close": require("../../../assets/words/u/up-close.png"),
  upset: require("../../../assets/words/u/upset.png"),
  "upside down": require("../../../assets/words/u/upside-down.png"),
  useless: require("../../../assets/words/u/useless.png"),
  usually: require("../../../assets/words/u/usually.png"),
  utilize: require("../../../assets/words/u/utilize.png"),
};
