import { ImageSourcePropType } from "react-native";

// "u" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_U: Record<string, ImageSourcePropType> = {
  ultimate: require("../../../assets/words/u/ultimate.png"),
  umbrella: require("../../../assets/words/u/umbrella.png"),
  unconsciously: require("../../../assets/words/u/unconsciously.png"),
  uncover: require("../../../assets/words/u/uncover.png"),
  undergo: require("../../../assets/words/u/undergo.png"),
  underground: require("../../../assets/words/u/underground.png"),
  understand: require("../../../assets/words/u/understand.png"),
  underwater: require("../../../assets/words/u/underwater.png"),
  unemployment: require("../../../assets/words/u/unemployment.png"),
  unexpected: require("../../../assets/words/u/unexpected.png"),
  unfair: require("../../../assets/words/u/unfair.png"),
  unfortunately: require("../../../assets/words/u/unfortunately.png"),
  unification: require("../../../assets/words/u/unification.png"),
  uniform: require("../../../assets/words/u/uniform.png"),
  unify: require("../../../assets/words/u/unify.png"),
  union: require("../../../assets/words/u/union.png"),
  unique: require("../../../assets/words/u/unique.png"),
  unite: require("../../../assets/words/u/unite.png"),
  unity: require("../../../assets/words/u/unity.png"),
  universal: require("../../../assets/words/u/universal.png"),
  universe: require("../../../assets/words/u/universe.png"),
  university: require("../../../assets/words/u/university.png"),
  unknown: require("../../../assets/words/u/unknown.png"),
  unless: require("../../../assets/words/u/unless.png"),
  unlike: require("../../../assets/words/u/unlike.png"),
  unlikely: require("../../../assets/words/u/unlikely.png"),
  unprecedented: require("../../../assets/words/u/unprecedented.png"),
  unusual: require("../../../assets/words/u/unusual.png"),
  "up close": require("../../../assets/words/u/up-close.png"),
  uphold: require("../../../assets/words/u/uphold.png"),
  upset: require("../../../assets/words/u/upset.png"),
  "upside down": require("../../../assets/words/u/upside-down.png"),
  urban: require("../../../assets/words/u/urban.png"),
  urge: require("../../../assets/words/u/urge.png"),
  urgent: require("../../../assets/words/u/urgent.png"),
  useful: require("../../../assets/words/u/useful.png"),
  useless: require("../../../assets/words/u/useless.png"),
  usual: require("../../../assets/words/u/usual.png"),
  usually: require("../../../assets/words/u/usually.png"),
  utilize: require("../../../assets/words/u/utilize.png"),
};
