import { ImageSourcePropType } from "react-native";

// "v" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_V: Record<string, ImageSourcePropType> = {
  vacant: require("../../../assets/words/v/vacant.png"),
  vacation: require("../../../assets/words/v/vacation.png"),
  vacuum: require("../../../assets/words/v/vacuum.png"),
  vague: require("../../../assets/words/v/vague.png"),
  vain: require("../../../assets/words/v/vain.png"),
  valid: require("../../../assets/words/v/valid.png"),
  valley: require("../../../assets/words/v/valley.png"),
  valuable: require("../../../assets/words/v/valuable.png"),
  value: require("../../../assets/words/v/value.png"),
  vanish: require("../../../assets/words/v/vanish.png"),
  vapor: require("../../../assets/words/v/vapor.png"),
  variety: require("../../../assets/words/v/variety.png"),
  various: require("../../../assets/words/v/various.png"),
  vary: require("../../../assets/words/v/vary.png"),
  vast: require("../../../assets/words/v/vast.png"),
  vegetable: require("../../../assets/words/v/vegetable.png"),
  vegetarian: require("../../../assets/words/v/vegetarian.png"),
  vehicle: require("../../../assets/words/v/vehicle.png"),
  venture: require("../../../assets/words/v/venture.png"),
  verbal: require("../../../assets/words/v/verbal.png"),
  verify: require("../../../assets/words/v/verify.png"),
  versatile: require("../../../assets/words/v/versatile.png"),
  version: require("../../../assets/words/v/version.png"),
  vertical: require("../../../assets/words/v/vertical.png"),
  vessel: require("../../../assets/words/v/vessel.png"),
  via: require("../../../assets/words/v/via.png"),
  vibrate: require("../../../assets/words/v/vibrate.png"),
  vibration: require("../../../assets/words/v/vibration.png"),
  vice: require("../../../assets/words/v/vice.png"),
  victim: require("../../../assets/words/v/victim.png"),
  victory: require("../../../assets/words/v/victory.png"),
  view: require("../../../assets/words/v/view.png"),
  village: require("../../../assets/words/v/village.png"),
  violate: require("../../../assets/words/v/violate.png"),
  violence: require("../../../assets/words/v/violence.png"),
  violent: require("../../../assets/words/v/violent.png"),
  virtual: require("../../../assets/words/v/virtual.png"),
  virtue: require("../../../assets/words/v/virtue.png"),
  vision: require("../../../assets/words/v/vision.png"),
  visual: require("../../../assets/words/v/visual.png"),
  vital: require("../../../assets/words/v/vital.png"),
  vivid: require("../../../assets/words/v/vivid.png"),
  vocation: require("../../../assets/words/v/vocation.png"),
  voice: require("../../../assets/words/v/voice.png"),
  volcano: require("../../../assets/words/v/volcano.png"),
  volume: require("../../../assets/words/v/volume.png"),
  voluntary: require("../../../assets/words/v/voluntary.png"),
  volunteer: require("../../../assets/words/v/volunteer.png"),
  vomit: require("../../../assets/words/v/vomit.png"),
  vote: require("../../../assets/words/v/vote.png"),
  voucher: require("../../../assets/words/v/voucher.png"),
  voyage: require("../../../assets/words/v/voyage.png"),
  vulnerable: require("../../../assets/words/v/vulnerable.png"),
};
