import { ImageSourcePropType } from "react-native";

// "v" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_V: Record<string, ImageSourcePropType> = {
  vacation: require("../../../assets/words/v/vacation.png"),
  vacuum: require("../../../assets/words/v/vacuum.png"),
  vain: require("../../../assets/words/v/vain.png"),
  valid: require("../../../assets/words/v/valid.png"),
  valley: require("../../../assets/words/v/valley.png"),
  valuable: require("../../../assets/words/v/valuable.png"),
  value: require("../../../assets/words/v/value.png"),
  various: require("../../../assets/words/v/various.png"),
  vary: require("../../../assets/words/v/vary.png"),
  vast: require("../../../assets/words/v/vast.png"),
  vegetable: require("../../../assets/words/v/vegetable.png"),
  vehicle: require("../../../assets/words/v/vehicle.png"),
  version: require("../../../assets/words/v/version.png"),
  vessel: require("../../../assets/words/v/vessel.png"),
  via: require("../../../assets/words/v/via.png"),
  vice: require("../../../assets/words/v/vice.png"),
  victim: require("../../../assets/words/v/victim.png"),
  victory: require("../../../assets/words/v/victory.png"),
  view: require("../../../assets/words/v/view.png"),
  village: require("../../../assets/words/v/village.png"),
  violate: require("../../../assets/words/v/violate.png"),
  violent: require("../../../assets/words/v/violent.png"),
  virtual: require("../../../assets/words/v/virtual.png"),
  virtue: require("../../../assets/words/v/virtue.png"),
  vision: require("../../../assets/words/v/vision.png"),
  visual: require("../../../assets/words/v/visual.png"),
  vital: require("../../../assets/words/v/vital.png"),
  vivid: require("../../../assets/words/v/vivid.png"),
  vocation: require("../../../assets/words/v/vocation.png"),
  voice: require("../../../assets/words/v/voice.png"),
  volcano: require("../../../assets/words/v/volcano.png"),
  volume: require("../../../assets/words/v/volume.png"),
  volunteer: require("../../../assets/words/v/volunteer.png"),
  vote: require("../../../assets/words/v/vote.png"),
  voyage: require("../../../assets/words/v/voyage.png"),
};
