import { ImageSourcePropType } from "react-native";

// "w" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_W: Record<string, ImageSourcePropType> = {
  wagon: require("../../../assets/words/w/wagon.png"),
  wake: require("../../../assets/words/w/wake.png"),
  war: require("../../../assets/words/w/war.png"),
  warn: require("../../../assets/words/w/warn.png"),
  waste: require("../../../assets/words/w/waste.png"),
  watch: require("../../../assets/words/w/watch.png"),
  weak: require("../../../assets/words/w/weak.png"),
  wealth: require("../../../assets/words/w/wealth.png"),
  wear: require("../../../assets/words/w/wear.png"),
  weather: require("../../../assets/words/w/weather.png"),
  wedding: require("../../../assets/words/w/wedding.png"),
  weight: require("../../../assets/words/w/weight.png"),
  whether: require("../../../assets/words/w/whether.png"),
  while: require("../../../assets/words/w/while.png"),
  whisker: require("../../../assets/words/w/whisker.png"),
  whisper: require("../../../assets/words/w/whisper.png"),
  whole: require("../../../assets/words/w/whole.png"),
  wide: require("../../../assets/words/w/wide.png"),
  wild: require("../../../assets/words/w/wild.png"),
  win: require("../../../assets/words/w/win.png"),
  wink: require("../../../assets/words/w/wink.png"),
  wish: require("../../../assets/words/w/wish.png"),
  without: require("../../../assets/words/w/without.png"),
  witness: require("../../../assets/words/w/witness.png"),
  wolf: require("../../../assets/words/w/wolf.png"),
  wonderful: require("../../../assets/words/w/wonderful.png"),
  wood: require("../../../assets/words/w/wood.png"),
  wool: require("../../../assets/words/w/wool.png"),
  word: require("../../../assets/words/w/word.png"),
  worry: require("../../../assets/words/w/worry.png"),
  worth: require("../../../assets/words/w/worth.png"),
  wound: require("../../../assets/words/w/wound.png"),
  wrap: require("../../../assets/words/w/wrap.png"),
  wrong: require("../../../assets/words/w/wrong.png"),
};
