import { ImageSourcePropType } from "react-native";

// "w" 로 시작하는 단어 그림. scripts/sync_word_images.py 가 만든다 (손으로 고치지 않는다)
export const IMAGES_W: Record<string, ImageSourcePropType> = {
  wage: require("../../../assets/words/w/wage.png"),
  wagon: require("../../../assets/words/w/wagon.png"),
  waist: require("../../../assets/words/w/waist.png"),
  wake: require("../../../assets/words/w/wake.png"),
  wallet: require("../../../assets/words/w/wallet.png"),
  wander: require("../../../assets/words/w/wander.png"),
  war: require("../../../assets/words/w/war.png"),
  warmth: require("../../../assets/words/w/warmth.png"),
  warn: require("../../../assets/words/w/warn.png"),
  warranty: require("../../../assets/words/w/warranty.png"),
  waste: require("../../../assets/words/w/waste.png"),
  watch: require("../../../assets/words/w/watch.png"),
  waterproof: require("../../../assets/words/w/waterproof.png"),
  wavy: require("../../../assets/words/w/wavy.png"),
  weak: require("../../../assets/words/w/weak.png"),
  weaken: require("../../../assets/words/w/weaken.png"),
  wealth: require("../../../assets/words/w/wealth.png"),
  weapon: require("../../../assets/words/w/weapon.png"),
  wear: require("../../../assets/words/w/wear.png"),
  weather: require("../../../assets/words/w/weather.png"),
  weave: require("../../../assets/words/w/weave.png"),
  wedding: require("../../../assets/words/w/wedding.png"),
  weed: require("../../../assets/words/w/weed.png"),
  weekly: require("../../../assets/words/w/weekly.png"),
  weigh: require("../../../assets/words/w/weigh.png"),
  weight: require("../../../assets/words/w/weight.png"),
  weird: require("../../../assets/words/w/weird.png"),
  welfare: require("../../../assets/words/w/welfare.png"),
  wet: require("../../../assets/words/w/wet.png"),
  wetland: require("../../../assets/words/w/wetland.png"),
  wheat: require("../../../assets/words/w/wheat.png"),
  "when it comes to": require("../../../assets/words/w/when-it-comes-to.png"),
  whether: require("../../../assets/words/w/whether.png"),
  while: require("../../../assets/words/w/while.png"),
  whisker: require("../../../assets/words/w/whisker.png"),
  whisper: require("../../../assets/words/w/whisper.png"),
  whistle: require("../../../assets/words/w/whistle.png"),
  whole: require("../../../assets/words/w/whole.png"),
  wide: require("../../../assets/words/w/wide.png"),
  widespread: require("../../../assets/words/w/widespread.png"),
  wild: require("../../../assets/words/w/wild.png"),
  willing: require("../../../assets/words/w/willing.png"),
  win: require("../../../assets/words/w/win.png"),
  wing: require("../../../assets/words/w/wing.png"),
  wink: require("../../../assets/words/w/wink.png"),
  wipe: require("../../../assets/words/w/wipe.png"),
  wireless: require("../../../assets/words/w/wireless.png"),
  wisdom: require("../../../assets/words/w/wisdom.png"),
  wise: require("../../../assets/words/w/wise.png"),
  wish: require("../../../assets/words/w/wish.png"),
  withdraw: require("../../../assets/words/w/withdraw.png"),
  without: require("../../../assets/words/w/without.png"),
  witness: require("../../../assets/words/w/witness.png"),
  wolf: require("../../../assets/words/w/wolf.png"),
  wonder: require("../../../assets/words/w/wonder.png"),
  wonderful: require("../../../assets/words/w/wonderful.png"),
  wood: require("../../../assets/words/w/wood.png"),
  wool: require("../../../assets/words/w/wool.png"),
  word: require("../../../assets/words/w/word.png"),
  "work out": require("../../../assets/words/w/work-out.png"),
  workout: require("../../../assets/words/w/workout.png"),
  worry: require("../../../assets/words/w/worry.png"),
  worse: require("../../../assets/words/w/worse.png"),
  worship: require("../../../assets/words/w/worship.png"),
  worth: require("../../../assets/words/w/worth.png"),
  wound: require("../../../assets/words/w/wound.png"),
  wrap: require("../../../assets/words/w/wrap.png"),
  wreck: require("../../../assets/words/w/wreck.png"),
  wrinkle: require("../../../assets/words/w/wrinkle.png"),
  wrist: require("../../../assets/words/w/wrist.png"),
  wrong: require("../../../assets/words/w/wrong.png"),
};
