import { ImageSourcePropType } from "react-native";

/**
 * 단어별 로컬 연상 이미지 레지스트리.
 * assets/words/<단어>.png 로 이미지를 넣고 여기에 등록하면
 * 원격 URL 대신 로컬 이미지가 우선 사용된다.
 */
export const WORD_IMAGES: Record<string, ImageSourcePropType> = {
  // 중학교 1학년 1Unit (20개 단어)
  beyond: require("../../assets/words/beyond.png"),
  either: require("../../assets/words/either.png"),
  neither: require("../../assets/words/neither.png"),
  behind: require("../../assets/words/behind.png"),
  bound: require("../../assets/words/bound.png"),
  below: require("../../assets/words/below.png"),
  without: require("../../assets/words/without.png"),
  belong: require("../../assets/words/belong.png"),
  replace: require("../../assets/words/replace.png"),
  along: require("../../assets/words/along.png"),
  except: require("../../assets/words/except.png"),
  become: require("../../assets/words/become.png"),
  since: require("../../assets/words/since.png"),
  pretend: require("../../assets/words/pretend.png"),
  whether: require("../../assets/words/whether.png"),
  toward: require("../../assets/words/toward.png"),
  while: require("../../assets/words/while.png"),
  unless: require("../../assets/words/unless.png"),
  deserve: require("../../assets/words/deserve.png"),
  teenager: require("../../assets/words/teenager.png"),

  // 단어 ID 매핑 (m1-1 ~ m1-20)
  "m1-1": require("../../assets/words/beyond.png"),
  "m1-2": require("../../assets/words/either.png"),
  "m1-3": require("../../assets/words/neither.png"),
  "m1-4": require("../../assets/words/behind.png"),
  "m1-5": require("../../assets/words/bound.png"),
  "m1-6": require("../../assets/words/below.png"),
  "m1-7": require("../../assets/words/without.png"),
  "m1-8": require("../../assets/words/belong.png"),
  "m1-9": require("../../assets/words/replace.png"),
  "m1-10": require("../../assets/words/along.png"),
  "m1-11": require("../../assets/words/except.png"),
  "m1-12": require("../../assets/words/become.png"),
  "m1-13": require("../../assets/words/since.png"),
  "m1-14": require("../../assets/words/pretend.png"),
  "m1-15": require("../../assets/words/whether.png"),
  "m1-16": require("../../assets/words/toward.png"),
  "m1-17": require("../../assets/words/while.png"),
  "m1-18": require("../../assets/words/unless.png"),
  "m1-19": require("../../assets/words/deserve.png"),
  "m1-20": require("../../assets/words/teenager.png"),

  // 중학교 2학년 1Unit (20개 단어)
  "culture": require("../../assets/words/culture.png"),
  "experience": require("../../assets/words/experience.png"),
  "education": require("../../assets/words/education.png"),
  "symbol": require("../../assets/words/symbol.png"),
  "effect": require("../../assets/words/effect.png"),
  "liberty": require("../../assets/words/liberty.png"),
  "affair": require("../../assets/words/affair.png"),
  "comfort": require("../../assets/words/comfort.png"),
  "tradition": require("../../assets/words/tradition.png"),
  "subject": require("../../assets/words/subject.png"),
  "object": require("../../assets/words/object.png"),
  "source": require("../../assets/words/source.png"),
  "revolution": require("../../assets/words/revolution.png"),
  "pollution": require("../../assets/words/pollution.png"),
  "system": require("../../assets/words/system.png"),
  "triumph": require("../../assets/words/triumph.png"),
  "respect": require("../../assets/words/respect.png"),
  "communication": require("../../assets/words/communication.png"),
  "mass communication": require("../../assets/words/mass-communication.png"),
  "foundation": require("../../assets/words/foundation.png"),

  // 단어 ID 매핑 (m2-1 ~ m2-20)
  "m2-1": require("../../assets/words/culture.png"),
  "m2-2": require("../../assets/words/experience.png"),
  "m2-3": require("../../assets/words/education.png"),
  "m2-4": require("../../assets/words/symbol.png"),
  "m2-5": require("../../assets/words/effect.png"),
  "m2-6": require("../../assets/words/liberty.png"),
  "m2-7": require("../../assets/words/affair.png"),
  "m2-8": require("../../assets/words/comfort.png"),
  "m2-9": require("../../assets/words/tradition.png"),
  "m2-10": require("../../assets/words/subject.png"),
  "m2-11": require("../../assets/words/object.png"),
  "m2-12": require("../../assets/words/source.png"),
  "m2-13": require("../../assets/words/revolution.png"),
  "m2-14": require("../../assets/words/pollution.png"),
  "m2-15": require("../../assets/words/system.png"),
  "m2-16": require("../../assets/words/triumph.png"),
  "m2-17": require("../../assets/words/respect.png"),
  "m2-18": require("../../assets/words/communication.png"),
  "m2-19": require("../../assets/words/mass-communication.png"),
  "m2-20": require("../../assets/words/foundation.png"),

  // 중학교 2학년 4Unit (m2-61 ~ m2-73 완료분)
  ruin: require("../../assets/words/ruin.png"),
  monument: require("../../assets/words/monument.png"),
  information: require("../../assets/words/information.png"),
  appetite: require("../../assets/words/appetite.png"),
  stethoscope: require("../../assets/words/stethoscope.png"),
  mystery: require("../../assets/words/mystery.png"),
  thermometer: require("../../assets/words/thermometer.png"),
  burden: require("../../assets/words/burden.png"),
  series: require("../../assets/words/series.png"),
  oath: require("../../assets/words/oath.png"),
  appointment: require("../../assets/words/appointment.png"),
  clue: require("../../assets/words/clue.png"),
  debt: require("../../assets/words/debt.png"),

  // 단어 ID 매핑 (m2-61 ~ m2-73)
  "m2-61": require("../../assets/words/ruin.png"),
  "m2-62": require("../../assets/words/monument.png"),
  "m2-63": require("../../assets/words/information.png"),
  "m2-64": require("../../assets/words/appetite.png"),
  "m2-65": require("../../assets/words/stethoscope.png"),
  "m2-66": require("../../assets/words/mystery.png"),
  "m2-67": require("../../assets/words/thermometer.png"),
  "m2-68": require("../../assets/words/burden.png"),
  "m2-69": require("../../assets/words/series.png"),
  "m2-70": require("../../assets/words/oath.png"),
  "m2-71": require("../../assets/words/appointment.png"),
  "m2-72": require("../../assets/words/clue.png"),
  "m2-73": require("../../assets/words/debt.png"),

  // 기타 단어
  innocent: require("../../assets/words/innocent.png"),
};
