import { ImageSourcePropType } from "react-native";

/**
 * 단어별 로컬 연상 이미지 레지스트리.
 * assets/words/<단어>.png 로 이미지를 넣고 여기에 등록하면
 * 원격 URL 대신 로컬 이미지가 우선 사용된다.
 */
export const WORD_IMAGES: Record<string, ImageSourcePropType> = {
  // 중학교 1학년 1Unit (20개 단어)
  beyond: require("../../assets/words/beyond.png"),
  either: require("../../assets/words/either.png"),
  neither: require("../../assets/words/neither.png"),
  behind: require("../../assets/words/behind.png"),
  bound: require("../../assets/words/bound.png"),
  below: require("../../assets/words/below.png"),
  without: require("../../assets/words/without.png"),
  belong: require("../../assets/words/belong.png"),
  replace: require("../../assets/words/replace.png"),
  along: require("../../assets/words/along.png"),
  except: require("../../assets/words/except.png"),
  become: require("../../assets/words/become.png"),
  since: require("../../assets/words/since.png"),
  pretend: require("../../assets/words/pretend.png"),
  whether: require("../../assets/words/whether.png"),
  toward: require("../../assets/words/toward.png"),
  while: require("../../assets/words/while.png"),
  unless: require("../../assets/words/unless.png"),
  deserve: require("../../assets/words/deserve.png"),
  teenager: require("../../assets/words/teenager.png"),

  // 단어 ID 매핑 (m1-1 ~ m1-20)
  "m1-1": require("../../assets/words/beyond.png"),
  "m1-2": require("../../assets/words/either.png"),
  "m1-3": require("../../assets/words/neither.png"),
  "m1-4": require("../../assets/words/behind.png"),
  "m1-5": require("../../assets/words/bound.png"),
  "m1-6": require("../../assets/words/below.png"),
  "m1-7": require("../../assets/words/without.png"),
  "m1-8": require("../../assets/words/belong.png"),
  "m1-9": require("../../assets/words/replace.png"),
  "m1-10": require("../../assets/words/along.png"),
  "m1-11": require("../../assets/words/except.png"),
  "m1-12": require("../../assets/words/become.png"),
  "m1-13": require("../../assets/words/since.png"),
  "m1-14": require("../../assets/words/pretend.png"),
  "m1-15": require("../../assets/words/whether.png"),
  "m1-16": require("../../assets/words/toward.png"),
  "m1-17": require("../../assets/words/while.png"),
  "m1-18": require("../../assets/words/unless.png"),
  "m1-19": require("../../assets/words/deserve.png"),
  "m1-20": require("../../assets/words/teenager.png"),

  // 중학교 2학년 1Unit (20개 단어)
  "culture": require("../../assets/words/culture.png"),
  "experience": require("../../assets/words/experience.png"),
  "education": require("../../assets/words/education.png"),
  "symbol": require("../../assets/words/symbol.png"),
  "effect": require("../../assets/words/effect.png"),
  "liberty": require("../../assets/words/liberty.png"),
  "affair": require("../../assets/words/affair.png"),
  "comfort": require("../../assets/words/comfort.png"),
  "tradition": require("../../assets/words/tradition.png"),
  "subject": require("../../assets/words/subject.png"),
  "object": require("../../assets/words/object.png"),
  "source": require("../../assets/words/source.png"),
  "revolution": require("../../assets/words/revolution.png"),
  "pollution": require("../../assets/words/pollution.png"),
  "system": require("../../assets/words/system.png"),
  "triumph": require("../../assets/words/triumph.png"),
  "respect": require("../../assets/words/respect.png"),
  "communication": require("../../assets/words/communication.png"),
  "mass communication": require("../../assets/words/mass-communication.png"),
  "foundation": require("../../assets/words/foundation.png"),

  // 단어 ID 매핑 (m2-1 ~ m2-20)
  "m2-1": require("../../assets/words/culture.png"),
  "m2-2": require("../../assets/words/experience.png"),
  "m2-3": require("../../assets/words/education.png"),
  "m2-4": require("../../assets/words/symbol.png"),
  "m2-5": require("../../assets/words/effect.png"),
  "m2-6": require("../../assets/words/liberty.png"),
  "m2-7": require("../../assets/words/affair.png"),
  "m2-8": require("../../assets/words/comfort.png"),
  "m2-9": require("../../assets/words/tradition.png"),
  "m2-10": require("../../assets/words/subject.png"),
  "m2-11": require("../../assets/words/object.png"),
  "m2-12": require("../../assets/words/source.png"),
  "m2-13": require("../../assets/words/revolution.png"),
  "m2-14": require("../../assets/words/pollution.png"),
  "m2-15": require("../../assets/words/system.png"),
  "m2-16": require("../../assets/words/triumph.png"),
  "m2-17": require("../../assets/words/respect.png"),
  "m2-18": require("../../assets/words/communication.png"),
  "m2-19": require("../../assets/words/mass-communication.png"),
  "m2-20": require("../../assets/words/foundation.png"),

  // 중학교 2학년 4Unit (m2-61 ~ m2-73 완료분)
  ruin: require("../../assets/words/ruin.png"),
  monument: require("../../assets/words/monument.png"),
  information: require("../../assets/words/information.png"),
  appetite: require("../../assets/words/appetite.png"),
  stethoscope: require("../../assets/words/stethoscope.png"),
  mystery: require("../../assets/words/mystery.png"),
  thermometer: require("../../assets/words/thermometer.png"),
  burden: require("../../assets/words/burden.png"),
  series: require("../../assets/words/series.png"),
  oath: require("../../assets/words/oath.png"),
  appointment: require("../../assets/words/appointment.png"),
  clue: require("../../assets/words/clue.png"),
  debt: require("../../assets/words/debt.png"),

  // 단어 ID 매핑 (m2-61 ~ m2-73)
  "m2-61": require("../../assets/words/ruin.png"),
  "m2-62": require("../../assets/words/monument.png"),
  "m2-63": require("../../assets/words/information.png"),
  "m2-64": require("../../assets/words/appetite.png"),
  "m2-65": require("../../assets/words/stethoscope.png"),
  "m2-66": require("../../assets/words/mystery.png"),
  "m2-67": require("../../assets/words/thermometer.png"),
  "m2-68": require("../../assets/words/burden.png"),
  "m2-69": require("../../assets/words/series.png"),
  "m2-70": require("../../assets/words/oath.png"),
  "m2-71": require("../../assets/words/appointment.png"),
  "m2-72": require("../../assets/words/clue.png"),
  "m2-73": require("../../assets/words/debt.png"),

  // 중학교 2학년 5Unit (20개 단어)
  sophomore: require("../../assets/words/sophomore.png"),
  temperature: require("../../assets/words/temperature.png"),
  limit: require("../../assets/words/limit.png"),
  statue: require("../../assets/words/statue.png"),
  furniture: require("../../assets/words/furniture.png"),
  parade: require("../../assets/words/parade.png"),
  public: require("../../assets/words/public.png"),
  pilgrim: require("../../assets/words/pilgrim.png"),
  greeting: require("../../assets/words/greeting.png"),
  language: require("../../assets/words/language.png"),
  opinion: require("../../assets/words/opinion.png"),
  athlete: require("../../assets/words/athlete.png"),
  supply: require("../../assets/words/supply.png"),
  surface: require("../../assets/words/surface.png"),
  electricity: require("../../assets/words/electricity.png"),
  order: require("../../assets/words/order.png"),
  spirit: require("../../assets/words/spirit.png"),
  purpose: require("../../assets/words/purpose.png"),
  promise: require("../../assets/words/promise.png"),
  project: require("../../assets/words/project.png"),

  // 단어 ID 매핑 (m2-81 ~ m2-100)
  "m2-81": require("../../assets/words/sophomore.png"),
  "m2-82": require("../../assets/words/temperature.png"),
  "m2-83": require("../../assets/words/limit.png"),
  "m2-84": require("../../assets/words/statue.png"),
  "m2-85": require("../../assets/words/furniture.png"),
  "m2-86": require("../../assets/words/parade.png"),
  "m2-87": require("../../assets/words/public.png"),
  "m2-88": require("../../assets/words/pilgrim.png"),
  "m2-89": require("../../assets/words/greeting.png"),
  "m2-90": require("../../assets/words/language.png"),
  "m2-91": require("../../assets/words/opinion.png"),
  "m2-92": require("../../assets/words/athlete.png"),
  "m2-93": require("../../assets/words/supply.png"),
  "m2-94": require("../../assets/words/surface.png"),
  "m2-95": require("../../assets/words/electricity.png"),
  "m2-96": require("../../assets/words/order.png"),
  "m2-97": require("../../assets/words/spirit.png"),
  "m2-98": require("../../assets/words/purpose.png"),
  "m2-99": require("../../assets/words/promise.png"),
  "m2-100": require("../../assets/words/project.png"),

  // 중학교 2학년 6Unit (20개 단어)
  government: require("../../assets/words/government.png"),
  exercise: require("../../assets/words/exercise.png"),
  comparison: require("../../assets/words/comparison.png"),
  interest: require("../../assets/words/interest.png"),
  funeral: require("../../assets/words/funeral.png"),
  senior: require("../../assets/words/senior.png"),
  junior: require("../../assets/words/junior.png"),
  democracy: require("../../assets/words/democracy.png"),
  general: require("../../assets/words/general.png"),
  admiral: require("../../assets/words/admiral.png"),
  edge: require("../../assets/words/edge.png"),
  biology: require("../../assets/words/biology.png"),
  danger: require("../../assets/words/danger.png"),
  advice: require("../../assets/words/advice.png"),
  practice: require("../../assets/words/practice.png"),
  mammal: require("../../assets/words/mammal.png"),
  grade: require("../../assets/words/grade.png"),
  score: require("../../assets/words/score.png"),
  pause: require("../../assets/words/pause.png"),
  pronunciation: require("../../assets/words/pronunciation.png"),

  // 단어 ID 매핑 (m2-101 ~ m2-120)
  "m2-101": require("../../assets/words/government.png"),
  "m2-102": require("../../assets/words/exercise.png"),
  "m2-103": require("../../assets/words/comparison.png"),
  "m2-104": require("../../assets/words/interest.png"),
  "m2-105": require("../../assets/words/funeral.png"),
  "m2-106": require("../../assets/words/senior.png"),
  "m2-107": require("../../assets/words/junior.png"),
  "m2-108": require("../../assets/words/democracy.png"),
  "m2-109": require("../../assets/words/general.png"),
  "m2-110": require("../../assets/words/admiral.png"),
  "m2-111": require("../../assets/words/edge.png"),
  "m2-112": require("../../assets/words/biology.png"),
  "m2-113": require("../../assets/words/danger.png"),
  "m2-114": require("../../assets/words/advice.png"),
  "m2-115": require("../../assets/words/practice.png"),
  "m2-116": require("../../assets/words/mammal.png"),
  "m2-117": require("../../assets/words/grade.png"),
  "m2-118": require("../../assets/words/score.png"),
  "m2-119": require("../../assets/words/pause.png"),
  "m2-120": require("../../assets/words/pronunciation.png"),

  // 중학교 2학년 7Unit (20개 단어)
  stress: require("../../assets/words/stress.png"),
  contest: require("../../assets/words/contest.png"),
  horizon: require("../../assets/words/horizon.png"),
  principal: require("../../assets/words/principal.png"),
  might: require("../../assets/words/might.png"),
  trouble: require("../../assets/words/trouble.png"),
  scar: require("../../assets/words/scar.png"),
  balance: require("../../assets/words/balance.png"),
  proverb: require("../../assets/words/proverb.png"),
  semester: require("../../assets/words/semester.png"),
  election: require("../../assets/words/election.png"),
  inning: require("../../assets/words/inning.png"),
  hollow: require("../../assets/words/hollow.png"),
  degree: require("../../assets/words/degree.png"),
  cemetery: require("../../assets/words/cemetery.png"),
  relay: require("../../assets/words/relay.png"),
  spot: require("../../assets/words/spot.png"),
  exchange: require("../../assets/words/exchange.png"),
  merchant: require("../../assets/words/merchant.png"),
  saying: require("../../assets/words/saying.png"),

  // 단어 ID 매핑 (m2-121 ~ m2-140)
  "m2-121": require("../../assets/words/stress.png"),
  "m2-122": require("../../assets/words/contest.png"),
  "m2-123": require("../../assets/words/horizon.png"),
  "m2-124": require("../../assets/words/principal.png"),
  "m2-125": require("../../assets/words/might.png"),
  "m2-126": require("../../assets/words/trouble.png"),
  "m2-127": require("../../assets/words/scar.png"),
  "m2-128": require("../../assets/words/balance.png"),
  "m2-129": require("../../assets/words/proverb.png"),
  "m2-130": require("../../assets/words/semester.png"),
  "m2-131": require("../../assets/words/election.png"),
  "m2-132": require("../../assets/words/inning.png"),
  "m2-133": require("../../assets/words/hollow.png"),
  "m2-134": require("../../assets/words/degree.png"),
  "m2-135": require("../../assets/words/cemetery.png"),
  "m2-136": require("../../assets/words/relay.png"),
  "m2-137": require("../../assets/words/spot.png"),
  "m2-138": require("../../assets/words/exchange.png"),
  "m2-139": require("../../assets/words/merchant.png"),
  "m2-140": require("../../assets/words/saying.png"),

  // 중학교 2학년 2Unit (20개 단어)
  "glory": require("../../assets/words/glory.png"),
  "situation": require("../../assets/words/situation.png"),
  "competition": require("../../assets/words/competition.png"),
  "prairie": require("../../assets/words/prairie.png"),
  "effort": require("../../assets/words/effort.png"),
  "section": require("../../assets/words/section.png"),
  "no smoking section": require("../../assets/words/no-smoking-section.png"),
  "rein": require("../../assets/words/rein.png"),
  "solution": require("../../assets/words/solution.png"),
  "honor": require("../../assets/words/honor.png"),
  "unity": require("../../assets/words/unity.png"),
  "population": require("../../assets/words/population.png"),
  "direction": require("../../assets/words/direction.png"),
  "dialogue": require("../../assets/words/dialogue.png"),
  "dialogue between north and south": require("../../assets/words/dialogue-between-north-and-south.png"),
  "republic": require("../../assets/words/republic.png"),
  "method": require("../../assets/words/method.png"),
  "increase": require("../../assets/words/increase.png"),
  "decrease": require("../../assets/words/decrease.png"),
  "amount": require("../../assets/words/amount.png"),

  // 단어 ID 매핑 (m2-21 ~ m2-40)
  "m2-21": require("../../assets/words/glory.png"),
  "m2-22": require("../../assets/words/situation.png"),
  "m2-23": require("../../assets/words/competition.png"),
  "m2-24": require("../../assets/words/prairie.png"),
  "m2-25": require("../../assets/words/effort.png"),
  "m2-26": require("../../assets/words/section.png"),
  "m2-27": require("../../assets/words/no-smoking-section.png"),
  "m2-28": require("../../assets/words/rein.png"),
  "m2-29": require("../../assets/words/solution.png"),
  "m2-30": require("../../assets/words/honor.png"),
  "m2-31": require("../../assets/words/unity.png"),
  "m2-32": require("../../assets/words/population.png"),
  "m2-33": require("../../assets/words/direction.png"),
  "m2-34": require("../../assets/words/dialogue.png"),
  "m2-35": require("../../assets/words/dialogue-between-north-and-south.png"),
  "m2-36": require("../../assets/words/republic.png"),
  "m2-37": require("../../assets/words/method.png"),
  "m2-38": require("../../assets/words/increase.png"),
  "m2-39": require("../../assets/words/decrease.png"),
  "m2-40": require("../../assets/words/amount.png"),

  // 중학교 2학년 3Unit (20개 단어)
  "ancestor": require("../../assets/words/ancestor.png"),
  "voyage": require("../../assets/words/voyage.png"),
  "sculpture": require("../../assets/words/sculpture.png"),
  "instrument": require("../../assets/words/instrument.png"),
  "figure": require("../../assets/words/figure.png"),
  "activity": require("../../assets/words/activity.png"),
  "cause": require("../../assets/words/cause.png"),
  "worth": require("../../assets/words/worth.png"),
  "accident": require("../../assets/words/accident.png"),
  "adventure": require("../../assets/words/adventure.png"),
  "view": require("../../assets/words/view.png"),
  "relative": require("../../assets/words/relative.png"),
  "superstition": require("../../assets/words/superstition.png"),
  "habit": require("../../assets/words/habit.png"),
  "wealth": require("../../assets/words/wealth.png"),
  "treasure": require("../../assets/words/treasure.png"),
  "universe": require("../../assets/words/universe.png"),
  "adult": require("../../assets/words/adult.png"),
  "feast": require("../../assets/words/feast.png"),
  "resources": require("../../assets/words/resources.png"),

  // 단어 ID 매핑 (m2-41 ~ m2-60)
  "m2-41": require("../../assets/words/ancestor.png"),
  "m2-42": require("../../assets/words/voyage.png"),
  "m2-43": require("../../assets/words/sculpture.png"),
  "m2-44": require("../../assets/words/instrument.png"),
  "m2-45": require("../../assets/words/figure.png"),
  "m2-46": require("../../assets/words/activity.png"),
  "m2-47": require("../../assets/words/cause.png"),
  "m2-48": require("../../assets/words/worth.png"),
  "m2-49": require("../../assets/words/accident.png"),
  "m2-50": require("../../assets/words/adventure.png"),
  "m2-51": require("../../assets/words/view.png"),
  "m2-52": require("../../assets/words/relative.png"),
  "m2-53": require("../../assets/words/superstition.png"),
  "m2-54": require("../../assets/words/habit.png"),
  "m2-55": require("../../assets/words/wealth.png"),
  "m2-56": require("../../assets/words/treasure.png"),
  "m2-57": require("../../assets/words/universe.png"),
  "m2-58": require("../../assets/words/adult.png"),
  "m2-59": require("../../assets/words/feast.png"),
  "m2-60": require("../../assets/words/resources.png"),

  // 중학교 2학년 13~15Unit 중 기존 이미지 보유 단어 (4종)
  "m2-254": require("../../assets/words/deserve.png"),
  "m2-261": require("../../assets/words/pretend.png"),
  "m2-289": require("../../assets/words/except.png"),
  "m2-296": require("../../assets/words/replace.png"),

  // 기타 단어
  innocent: require("../../assets/words/innocent.png"),

  // 중학교 2학년 48Unit (20개 단어)
  low: require("../../assets/words/low.png"),
  sincerely: require("../../assets/words/sincerely.png"),
  fortunately: require("../../assets/words/fortunately.png"),
  finally: require("../../assets/words/finally.png"),
  immediately: require("../../assets/words/immediately.png"),
  especially: require("../../assets/words/especially.png"),
  else: require("../../assets/words/else.png"),
  actually: require("../../assets/words/actually.png"),
  hardly: require("../../assets/words/hardly.png"),
  otherwise: require("../../assets/words/otherwise.png"),
  tightly: require("../../assets/words/tightly.png"),
  recently: require("../../assets/words/recently.png"),
  rapidly: require("../../assets/words/rapidly.png"),
  however: require("../../assets/words/however.png"),
  politely: require("../../assets/words/politely.png"),
  rudely: require("../../assets/words/rudely.png"),
  further: require("../../assets/words/further.png"),
  frankly: require("../../assets/words/frankly.png"),
  properly: require("../../assets/words/properly.png"),
  haste: require("../../assets/words/haste.png"),

  // 단어 ID 매핑 (m2-941 ~ m2-960)
  "m2-941": require("../../assets/words/low.png"),
  "m2-942": require("../../assets/words/sincerely.png"),
  "m2-943": require("../../assets/words/fortunately.png"),
  "m2-944": require("../../assets/words/finally.png"),
  "m2-945": require("../../assets/words/immediately.png"),
  "m2-946": require("../../assets/words/especially.png"),
  "m2-947": require("../../assets/words/else.png"),
  "m2-948": require("../../assets/words/actually.png"),
  "m2-949": require("../../assets/words/hardly.png"),
  "m2-950": require("../../assets/words/otherwise.png"),
  "m2-951": require("../../assets/words/tightly.png"),
  "m2-952": require("../../assets/words/recently.png"),
  "m2-953": require("../../assets/words/rapidly.png"),
  "m2-954": require("../../assets/words/however.png"),
  "m2-955": require("../../assets/words/politely.png"),
  "m2-956": require("../../assets/words/rudely.png"),
  "m2-957": require("../../assets/words/further.png"),
  "m2-958": require("../../assets/words/frankly.png"),
  "m2-959": require("../../assets/words/properly.png"),
  "m2-960": require("../../assets/words/haste.png"),

  // 중학교 2학년 8Unit
  refrigerator: require("../../assets/words/refrigerator.png"),
  "m2-141": require("../../assets/words/refrigerator.png"),
};
