import { ImageSourcePropType } from "react-native";

/**
 * 단어별 로컬 연상 이미지 레지스트리.
 * assets/words/<단어>.png 로 이미지를 넣고 여기에 등록하면
 * 원격 URL 대신 로컬 이미지가 우선 사용된다.
 */
export const WORD_IMAGES: Record<string, ImageSourcePropType> = {
  // 중학교 1학년 1Unit (20개 단어)
  beyond: require("../../assets/words/beyond.png"),
  either: require("../../assets/words/either.png"),
  neither: require("../../assets/words/neither.png"),
  behind: require("../../assets/words/behind.png"),
  bound: require("../../assets/words/bound.png"),
  below: require("../../assets/words/below.png"),
  without: require("../../assets/words/without.png"),
  belong: require("../../assets/words/belong.png"),
  replace: require("../../assets/words/replace.png"),
  along: require("../../assets/words/along.png"),
  except: require("../../assets/words/except.png"),
  become: require("../../assets/words/become.png"),
  since: require("../../assets/words/since.png"),
  pretend: require("../../assets/words/pretend.png"),
  whether: require("../../assets/words/whether.png"),
  toward: require("../../assets/words/toward.png"),
  while: require("../../assets/words/while.png"),
  unless: require("../../assets/words/unless.png"),
  deserve: require("../../assets/words/deserve.png"),
  teenager: require("../../assets/words/teenager.png"),

  // 단어 ID 매핑 (m1-1 ~ m1-20)
  "m1-1": require("../../assets/words/beyond.png"),
  "m1-2": require("../../assets/words/either.png"),
  "m1-3": require("../../assets/words/neither.png"),
  "m1-4": require("../../assets/words/behind.png"),
  "m1-5": require("../../assets/words/bound.png"),
  "m1-6": require("../../assets/words/below.png"),
  "m1-7": require("../../assets/words/without.png"),
  "m1-8": require("../../assets/words/belong.png"),
  "m1-9": require("../../assets/words/replace.png"),
  "m1-10": require("../../assets/words/along.png"),
  "m1-11": require("../../assets/words/except.png"),
  "m1-12": require("../../assets/words/become.png"),
  "m1-13": require("../../assets/words/since.png"),
  "m1-14": require("../../assets/words/pretend.png"),
  "m1-15": require("../../assets/words/whether.png"),
  "m1-16": require("../../assets/words/toward.png"),
  "m1-17": require("../../assets/words/while.png"),
  "m1-18": require("../../assets/words/unless.png"),
  "m1-19": require("../../assets/words/deserve.png"),
  "m1-20": require("../../assets/words/teenager.png"),

  // 중학교 2학년 1Unit (20개 단어)
  "culture": require("../../assets/words/culture.png"),
  "experience": require("../../assets/words/experience.png"),
  "education": require("../../assets/words/education.png"),
  "symbol": require("../../assets/words/symbol.png"),
  "effect": require("../../assets/words/effect.png"),
  "liberty": require("../../assets/words/liberty.png"),
  "affair": require("../../assets/words/affair.png"),
  "comfort": require("../../assets/words/comfort.png"),
  "tradition": require("../../assets/words/tradition.png"),
  "subject": require("../../assets/words/subject.png"),
  "object": require("../../assets/words/object.png"),
  "source": require("../../assets/words/source.png"),
  "revolution": require("../../assets/words/revolution.png"),
  "pollution": require("../../assets/words/pollution.png"),
  "system": require("../../assets/words/system.png"),
  "triumph": require("../../assets/words/triumph.png"),
  "respect": require("../../assets/words/respect.png"),
  "communication": require("../../assets/words/communication.png"),
  "mass communication": require("../../assets/words/mass-communication.png"),
  "foundation": require("../../assets/words/foundation.png"),

  // 단어 ID 매핑 (m2-1 ~ m2-20)
  "m2-1": require("../../assets/words/culture.png"),
  "m2-2": require("../../assets/words/experience.png"),
  "m2-3": require("../../assets/words/education.png"),
  "m2-4": require("../../assets/words/symbol.png"),
  "m2-5": require("../../assets/words/effect.png"),
  "m2-6": require("../../assets/words/liberty.png"),
  "m2-7": require("../../assets/words/affair.png"),
  "m2-8": require("../../assets/words/comfort.png"),
  "m2-9": require("../../assets/words/tradition.png"),
  "m2-10": require("../../assets/words/subject.png"),
  "m2-11": require("../../assets/words/object.png"),
  "m2-12": require("../../assets/words/source.png"),
  "m2-13": require("../../assets/words/revolution.png"),
  "m2-14": require("../../assets/words/pollution.png"),
  "m2-15": require("../../assets/words/system.png"),
  "m2-16": require("../../assets/words/triumph.png"),
  "m2-17": require("../../assets/words/respect.png"),
  "m2-18": require("../../assets/words/communication.png"),
  "m2-19": require("../../assets/words/mass-communication.png"),
  "m2-20": require("../../assets/words/foundation.png"),

  // 중학교 2학년 4Unit (m2-61 ~ m2-73 완료분)
  ruin: require("../../assets/words/ruin.png"),
  monument: require("../../assets/words/monument.png"),
  information: require("../../assets/words/information.png"),
  appetite: require("../../assets/words/appetite.png"),
  stethoscope: require("../../assets/words/stethoscope.png"),
  mystery: require("../../assets/words/mystery.png"),
  thermometer: require("../../assets/words/thermometer.png"),
  burden: require("../../assets/words/burden.png"),
  series: require("../../assets/words/series.png"),
  oath: require("../../assets/words/oath.png"),
  appointment: require("../../assets/words/appointment.png"),
  clue: require("../../assets/words/clue.png"),
  debt: require("../../assets/words/debt.png"),

  // 단어 ID 매핑 (m2-61 ~ m2-73)
  "m2-61": require("../../assets/words/ruin.png"),
  "m2-62": require("../../assets/words/monument.png"),
  "m2-63": require("../../assets/words/information.png"),
  "m2-64": require("../../assets/words/appetite.png"),
  "m2-65": require("../../assets/words/stethoscope.png"),
  "m2-66": require("../../assets/words/mystery.png"),
  "m2-67": require("../../assets/words/thermometer.png"),
  "m2-68": require("../../assets/words/burden.png"),
  "m2-69": require("../../assets/words/series.png"),
  "m2-70": require("../../assets/words/oath.png"),
  "m2-71": require("../../assets/words/appointment.png"),
  "m2-72": require("../../assets/words/clue.png"),
  "m2-73": require("../../assets/words/debt.png"),

  // 중학교 2학년 5Unit (20개 단어)
  sophomore: require("../../assets/words/sophomore.png"),
  temperature: require("../../assets/words/temperature.png"),
  limit: require("../../assets/words/limit.png"),
  statue: require("../../assets/words/statue.png"),
  furniture: require("../../assets/words/furniture.png"),
  parade: require("../../assets/words/parade.png"),
  public: require("../../assets/words/public.png"),
  pilgrim: require("../../assets/words/pilgrim.png"),
  greeting: require("../../assets/words/greeting.png"),
  language: require("../../assets/words/language.png"),
  opinion: require("../../assets/words/opinion.png"),
  athlete: require("../../assets/words/athlete.png"),
  supply: require("../../assets/words/supply.png"),
  surface: require("../../assets/words/surface.png"),
  electricity: require("../../assets/words/electricity.png"),
  order: require("../../assets/words/order.png"),
  spirit: require("../../assets/words/spirit.png"),
  purpose: require("../../assets/words/purpose.png"),
  promise: require("../../assets/words/promise.png"),
  project: require("../../assets/words/project.png"),

  // 단어 ID 매핑 (m2-81 ~ m2-100)
  "m2-81": require("../../assets/words/sophomore.png"),
  "m2-82": require("../../assets/words/temperature.png"),
  "m2-83": require("../../assets/words/limit.png"),
  "m2-84": require("../../assets/words/statue.png"),
  "m2-85": require("../../assets/words/furniture.png"),
  "m2-86": require("../../assets/words/parade.png"),
  "m2-87": require("../../assets/words/public.png"),
  "m2-88": require("../../assets/words/pilgrim.png"),
  "m2-89": require("../../assets/words/greeting.png"),
  "m2-90": require("../../assets/words/language.png"),
  "m2-91": require("../../assets/words/opinion.png"),
  "m2-92": require("../../assets/words/athlete.png"),
  "m2-93": require("../../assets/words/supply.png"),
  "m2-94": require("../../assets/words/surface.png"),
  "m2-95": require("../../assets/words/electricity.png"),
  "m2-96": require("../../assets/words/order.png"),
  "m2-97": require("../../assets/words/spirit.png"),
  "m2-98": require("../../assets/words/purpose.png"),
  "m2-99": require("../../assets/words/promise.png"),
  "m2-100": require("../../assets/words/project.png"),

  // 중학교 2학년 6Unit (20개 단어)
  government: require("../../assets/words/government.png"),
  exercise: require("../../assets/words/exercise.png"),
  comparison: require("../../assets/words/comparison.png"),
  interest: require("../../assets/words/interest.png"),
  funeral: require("../../assets/words/funeral.png"),
  senior: require("../../assets/words/senior.png"),
  junior: require("../../assets/words/junior.png"),
  democracy: require("../../assets/words/democracy.png"),
  general: require("../../assets/words/general.png"),
  admiral: require("../../assets/words/admiral.png"),
  edge: require("../../assets/words/edge.png"),
  biology: require("../../assets/words/biology.png"),
  danger: require("../../assets/words/danger.png"),
  advice: require("../../assets/words/advice.png"),
  practice: require("../../assets/words/practice.png"),
  mammal: require("../../assets/words/mammal.png"),
  grade: require("../../assets/words/grade.png"),
  score: require("../../assets/words/score.png"),
  pause: require("../../assets/words/pause.png"),
  pronunciation: require("../../assets/words/pronunciation.png"),

  // 단어 ID 매핑 (m2-101 ~ m2-120)
  "m2-101": require("../../assets/words/government.png"),
  "m2-102": require("../../assets/words/exercise.png"),
  "m2-103": require("../../assets/words/comparison.png"),
  "m2-104": require("../../assets/words/interest.png"),
  "m2-105": require("../../assets/words/funeral.png"),
  "m2-106": require("../../assets/words/senior.png"),
  "m2-107": require("../../assets/words/junior.png"),
  "m2-108": require("../../assets/words/democracy.png"),
  "m2-109": require("../../assets/words/general.png"),
  "m2-110": require("../../assets/words/admiral.png"),
  "m2-111": require("../../assets/words/edge.png"),
  "m2-112": require("../../assets/words/biology.png"),
  "m2-113": require("../../assets/words/danger.png"),
  "m2-114": require("../../assets/words/advice.png"),
  "m2-115": require("../../assets/words/practice.png"),
  "m2-116": require("../../assets/words/mammal.png"),
  "m2-117": require("../../assets/words/grade.png"),
  "m2-118": require("../../assets/words/score.png"),
  "m2-119": require("../../assets/words/pause.png"),
  "m2-120": require("../../assets/words/pronunciation.png"),

  // 중학교 2학년 7Unit (20개 단어)
  stress: require("../../assets/words/stress.png"),
  contest: require("../../assets/words/contest.png"),
  horizon: require("../../assets/words/horizon.png"),
  principal: require("../../assets/words/principal.png"),
  might: require("../../assets/words/might.png"),
  trouble: require("../../assets/words/trouble.png"),
  scar: require("../../assets/words/scar.png"),
  balance: require("../../assets/words/balance.png"),
  proverb: require("../../assets/words/proverb.png"),
  semester: require("../../assets/words/semester.png"),
  election: require("../../assets/words/election.png"),
  inning: require("../../assets/words/inning.png"),
  hollow: require("../../assets/words/hollow.png"),
  degree: require("../../assets/words/degree.png"),
  cemetery: require("../../assets/words/cemetery.png"),
  relay: require("../../assets/words/relay.png"),
  spot: require("../../assets/words/spot.png"),
  exchange: require("../../assets/words/exchange.png"),
  merchant: require("../../assets/words/merchant.png"),
  saying: require("../../assets/words/saying.png"),

  // 단어 ID 매핑 (m2-121 ~ m2-140)
  "m2-121": require("../../assets/words/stress.png"),
  "m2-122": require("../../assets/words/contest.png"),
  "m2-123": require("../../assets/words/horizon.png"),
  "m2-124": require("../../assets/words/principal.png"),
  "m2-125": require("../../assets/words/might.png"),
  "m2-126": require("../../assets/words/trouble.png"),
  "m2-127": require("../../assets/words/scar.png"),
  "m2-128": require("../../assets/words/balance.png"),
  "m2-129": require("../../assets/words/proverb.png"),
  "m2-130": require("../../assets/words/semester.png"),
  "m2-131": require("../../assets/words/election.png"),
  "m2-132": require("../../assets/words/inning.png"),
  "m2-133": require("../../assets/words/hollow.png"),
  "m2-134": require("../../assets/words/degree.png"),
  "m2-135": require("../../assets/words/cemetery.png"),
  "m2-136": require("../../assets/words/relay.png"),
  "m2-137": require("../../assets/words/spot.png"),
  "m2-138": require("../../assets/words/exchange.png"),
  "m2-139": require("../../assets/words/merchant.png"),
  "m2-140": require("../../assets/words/saying.png"),

  // 중학교 2학년 9Unit (20개 단어)
  harvest: require("../../assets/words/harvest.png"),
  tool: require("../../assets/words/tool.png"),
  sword: require("../../assets/words/sword.png"),
  magazine: require("../../assets/words/magazine.png"),
  stadium: require("../../assets/words/stadium.png"),
  care: require("../../assets/words/care.png"),
  beauty: require("../../assets/words/beauty.png"),
  museum: require("../../assets/words/museum.png"),
  sentence: require("../../assets/words/sentence.png"),
  memory: require("../../assets/words/memory.png"),
  delight: require("../../assets/words/delight.png"),
  passenger: require("../../assets/words/passenger.png"),
  skill: require("../../assets/words/skill.png"),
  journey: require("../../assets/words/journey.png"),
  ceremony: require("../../assets/words/ceremony.png"),
  hobby: require("../../assets/words/hobby.png"),
  president: require("../../assets/words/president.png"),
  address: require("../../assets/words/address.png"),
  continent: require("../../assets/words/continent.png"),
  mankind: require("../../assets/words/mankind.png"),

  // 단어 ID 매핑 (m2-161 ~ m2-180)
  "m2-161": require("../../assets/words/harvest.png"),
  "m2-162": require("../../assets/words/tool.png"),
  "m2-163": require("../../assets/words/sword.png"),
  "m2-164": require("../../assets/words/magazine.png"),
  "m2-165": require("../../assets/words/stadium.png"),
  "m2-166": require("../../assets/words/care.png"),
  "m2-167": require("../../assets/words/beauty.png"),
  "m2-168": require("../../assets/words/museum.png"),
  "m2-169": require("../../assets/words/sentence.png"),
  "m2-170": require("../../assets/words/memory.png"),
  "m2-171": require("../../assets/words/delight.png"),
  "m2-172": require("../../assets/words/passenger.png"),
  "m2-173": require("../../assets/words/skill.png"),
  "m2-174": require("../../assets/words/journey.png"),
  "m2-175": require("../../assets/words/ceremony.png"),
  "m2-176": require("../../assets/words/hobby.png"),
  "m2-177": require("../../assets/words/president.png"),
  "m2-178": require("../../assets/words/address.png"),
  "m2-179": require("../../assets/words/continent.png"),
  "m2-180": require("../../assets/words/mankind.png"),

  // 중학교 2학년 10Unit (20개 단어)
  patient: require("../../assets/words/patient.png"), site: require("../../assets/words/site.png"), marble: require("../../assets/words/marble.png"), stem: require("../../assets/words/stem.png"), slip: require("../../assets/words/slip.png"), torch: require("../../assets/words/torch.png"), composer: require("../../assets/words/composer.png"), invader: require("../../assets/words/invader.png"), trick: require("../../assets/words/trick.png"), flight: require("../../assets/words/flight.png"), castle: require("../../assets/words/castle.png"), envelope: require("../../assets/words/envelope.png"), pal: require("../../assets/words/pal.png"), vacation: require("../../assets/words/vacation.png"), desert: require("../../assets/words/desert.png"), event: require("../../assets/words/event.png"), theater: require("../../assets/words/theater.png"), stage: require("../../assets/words/stage.png"), error: require("../../assets/words/error.png"), area: require("../../assets/words/area.png"),
  "m2-181": require("../../assets/words/patient.png"), "m2-182": require("../../assets/words/site.png"), "m2-183": require("../../assets/words/marble.png"), "m2-184": require("../../assets/words/stem.png"), "m2-185": require("../../assets/words/slip.png"), "m2-186": require("../../assets/words/torch.png"), "m2-187": require("../../assets/words/composer.png"), "m2-188": require("../../assets/words/invader.png"), "m2-189": require("../../assets/words/trick.png"), "m2-190": require("../../assets/words/flight.png"), "m2-191": require("../../assets/words/castle.png"), "m2-192": require("../../assets/words/envelope.png"), "m2-193": require("../../assets/words/pal.png"), "m2-194": require("../../assets/words/vacation.png"), "m2-195": require("../../assets/words/desert.png"), "m2-196": require("../../assets/words/event.png"), "m2-197": require("../../assets/words/theater.png"), "m2-198": require("../../assets/words/stage.png"), "m2-199": require("../../assets/words/error.png"), "m2-200": require("../../assets/words/area.png"),

  // 중학교 2학년 11Unit (20개 단어)
  base: require("../../assets/words/base.png"), basement: require("../../assets/words/basement.png"), evil: require("../../assets/words/evil.png"), atom: require("../../assets/words/atom.png"), poet: require("../../assets/words/poet.png"), petal: require("../../assets/words/petal.png"), chance: require("../../assets/words/chance.png"), mind: require("../../assets/words/mind.png"), climate: require("../../assets/words/climate.png"), suburb: require("../../assets/words/suburb.png"), throat: require("../../assets/words/throat.png"), voice: require("../../assets/words/voice.png"), valley: require("../../assets/words/valley.png"), puritan: require("../../assets/words/puritan.png"), feather: require("../../assets/words/feather.png"), amateur: require("../../assets/words/amateur.png"), nation: require("../../assets/words/nation.png"), puzzle: require("../../assets/words/puzzle.png"), riddle: require("../../assets/words/riddle.png"), rear: require("../../assets/words/rear.png"),
  "m2-201": require("../../assets/words/base.png"), "m2-202": require("../../assets/words/basement.png"), "m2-203": require("../../assets/words/evil.png"), "m2-204": require("../../assets/words/atom.png"), "m2-205": require("../../assets/words/poet.png"), "m2-206": require("../../assets/words/petal.png"), "m2-207": require("../../assets/words/chance.png"), "m2-208": require("../../assets/words/mind.png"), "m2-209": require("../../assets/words/climate.png"), "m2-210": require("../../assets/words/suburb.png"), "m2-211": require("../../assets/words/throat.png"), "m2-212": require("../../assets/words/voice.png"), "m2-213": require("../../assets/words/valley.png"), "m2-214": require("../../assets/words/puritan.png"), "m2-215": require("../../assets/words/feather.png"), "m2-216": require("../../assets/words/amateur.png"), "m2-217": require("../../assets/words/nation.png"), "m2-218": require("../../assets/words/puzzle.png"), "m2-219": require("../../assets/words/riddle.png"), "m2-220": require("../../assets/words/rear.png"),

  // 중학교 2학년 12Unit (20개 단어)
  battle: require("../../assets/words/battle.png"), laundry: require("../../assets/words/laundry.png"), shower: require("../../assets/words/shower.png"), navy: require("../../assets/words/navy.png"), mars: require("../../assets/words/mars.png"), gallery: require("../../assets/words/gallery.png"), guest: require("../../assets/words/guest.png"), folk: require("../../assets/words/folk.png"), problem: require("../../assets/words/problem.png"), jewel: require("../../assets/words/jewel.png"), garage: require("../../assets/words/garage.png"), fault: require("../../assets/words/fault.png"), lantern: require("../../assets/words/lantern.png"), import: require("../../assets/words/import.png"), angle: require("../../assets/words/angle.png"), match: require("../../assets/words/match.png"), stripe: require("../../assets/words/stripe.png"), pulse: require("../../assets/words/pulse.png"), powder: require("../../assets/words/powder.png"), flood: require("../../assets/words/flood.png"),
  "m2-221": require("../../assets/words/battle.png"), "m2-222": require("../../assets/words/laundry.png"), "m2-223": require("../../assets/words/shower.png"), "m2-224": require("../../assets/words/navy.png"), "m2-225": require("../../assets/words/mars.png"), "m2-226": require("../../assets/words/gallery.png"), "m2-227": require("../../assets/words/guest.png"), "m2-228": require("../../assets/words/folk.png"), "m2-229": require("../../assets/words/problem.png"), "m2-230": require("../../assets/words/jewel.png"), "m2-231": require("../../assets/words/garage.png"), "m2-232": require("../../assets/words/fault.png"), "m2-233": require("../../assets/words/lantern.png"), "m2-234": require("../../assets/words/import.png"), "m2-235": require("../../assets/words/angle.png"), "m2-236": require("../../assets/words/match.png"), "m2-237": require("../../assets/words/stripe.png"), "m2-238": require("../../assets/words/pulse.png"), "m2-239": require("../../assets/words/powder.png"), "m2-240": require("../../assets/words/flood.png"),

  // 중학교 2학년 2Unit (20개 단어)
  "glory": require("../../assets/words/glory.png"),
  "situation": require("../../assets/words/situation.png"),
  "competition": require("../../assets/words/competition.png"),
  "prairie": require("../../assets/words/prairie.png"),
  "effort": require("../../assets/words/effort.png"),
  "section": require("../../assets/words/section.png"),
  "no smoking section": require("../../assets/words/no-smoking-section.png"),
  "rein": require("../../assets/words/rein.png"),
  "solution": require("../../assets/words/solution.png"),
  "honor": require("../../assets/words/honor.png"),
  "unity": require("../../assets/words/unity.png"),
  "population": require("../../assets/words/population.png"),
  "direction": require("../../assets/words/direction.png"),
  "dialogue": require("../../assets/words/dialogue.png"),
  "dialogue between north and south": require("../../assets/words/dialogue-between-north-and-south.png"),
  "republic": require("../../assets/words/republic.png"),
  "method": require("../../assets/words/method.png"),
  "increase": require("../../assets/words/increase.png"),
  "decrease": require("../../assets/words/decrease.png"),
  "amount": require("../../assets/words/amount.png"),

  // 단어 ID 매핑 (m2-21 ~ m2-40)
  "m2-21": require("../../assets/words/glory.png"),
  "m2-22": require("../../assets/words/situation.png"),
  "m2-23": require("../../assets/words/competition.png"),
  "m2-24": require("../../assets/words/prairie.png"),
  "m2-25": require("../../assets/words/effort.png"),
  "m2-26": require("../../assets/words/section.png"),
  "m2-27": require("../../assets/words/no-smoking-section.png"),
  "m2-28": require("../../assets/words/rein.png"),
  "m2-29": require("../../assets/words/solution.png"),
  "m2-30": require("../../assets/words/honor.png"),
  "m2-31": require("../../assets/words/unity.png"),
  "m2-32": require("../../assets/words/population.png"),
  "m2-33": require("../../assets/words/direction.png"),
  "m2-34": require("../../assets/words/dialogue.png"),
  "m2-35": require("../../assets/words/dialogue-between-north-and-south.png"),
  "m2-36": require("../../assets/words/republic.png"),
  "m2-37": require("../../assets/words/method.png"),
  "m2-38": require("../../assets/words/increase.png"),
  "m2-39": require("../../assets/words/decrease.png"),
  "m2-40": require("../../assets/words/amount.png"),

  // 중학교 2학년 3Unit (20개 단어)
  "ancestor": require("../../assets/words/ancestor.png"),
  "voyage": require("../../assets/words/voyage.png"),
  "sculpture": require("../../assets/words/sculpture.png"),
  "instrument": require("../../assets/words/instrument.png"),
  "figure": require("../../assets/words/figure.png"),
  "activity": require("../../assets/words/activity.png"),
  "cause": require("../../assets/words/cause.png"),
  "worth": require("../../assets/words/worth.png"),
  "accident": require("../../assets/words/accident.png"),
  "adventure": require("../../assets/words/adventure.png"),
  "view": require("../../assets/words/view.png"),
  "relative": require("../../assets/words/relative.png"),
  "superstition": require("../../assets/words/superstition.png"),
  "habit": require("../../assets/words/habit.png"),
  "wealth": require("../../assets/words/wealth.png"),
  "treasure": require("../../assets/words/treasure.png"),
  "universe": require("../../assets/words/universe.png"),
  "adult": require("../../assets/words/adult.png"),
  "feast": require("../../assets/words/feast.png"),
  "resources": require("../../assets/words/resources.png"),

  // 단어 ID 매핑 (m2-41 ~ m2-60)
  "m2-41": require("../../assets/words/ancestor.png"),
  "m2-42": require("../../assets/words/voyage.png"),
  "m2-43": require("../../assets/words/sculpture.png"),
  "m2-44": require("../../assets/words/instrument.png"),
  "m2-45": require("../../assets/words/figure.png"),
  "m2-46": require("../../assets/words/activity.png"),
  "m2-47": require("../../assets/words/cause.png"),
  "m2-48": require("../../assets/words/worth.png"),
  "m2-49": require("../../assets/words/accident.png"),
  "m2-50": require("../../assets/words/adventure.png"),
  "m2-51": require("../../assets/words/view.png"),
  "m2-52": require("../../assets/words/relative.png"),
  "m2-53": require("../../assets/words/superstition.png"),
  "m2-54": require("../../assets/words/habit.png"),
  "m2-55": require("../../assets/words/wealth.png"),
  "m2-56": require("../../assets/words/treasure.png"),
  "m2-57": require("../../assets/words/universe.png"),
  "m2-58": require("../../assets/words/adult.png"),
  "m2-59": require("../../assets/words/feast.png"),
  "m2-60": require("../../assets/words/resources.png"),

  // 중학교 2학년 13~15Unit 중 기존 이미지 보유 단어 (4종)
  "m2-254": require("../../assets/words/deserve.png"),
  "m2-241": require("../../assets/words/bush.png"), "m2-242": require("../../assets/words/branch.png"), "m2-243": require("../../assets/words/hero.png"), "m2-244": require("../../assets/words/heaven.png"), "m2-245": require("../../assets/words/exit.png"), "m2-246": require("../../assets/words/beast.png"), "m2-247": require("../../assets/words/century.png"), "m2-248": require("../../assets/words/coeducation.png"), "m2-249": require("../../assets/words/twin.png"), "m2-250": require("../../assets/words/wound.png"), "m2-251": require("../../assets/words/metal.png"), "m2-252": require("../../assets/words/insect.png"), "m2-253": require("../../assets/words/track.png"), "m2-255": require("../../assets/words/survive.png"), "m2-256": require("../../assets/words/create.png"), "m2-257": require("../../assets/words/describe.png"), "m2-258": require("../../assets/words/select.png"), "m2-259": require("../../assets/words/hesitate.png"), "m2-260": require("../../assets/words/declare.png"),
  "m2-261": require("../../assets/words/pretend.png"),
  "m2-262": require("../../assets/words/struggle.png"), "m2-263": require("../../assets/words/explore.png"), "m2-264": require("../../assets/words/astonish.png"), "m2-265": require("../../assets/words/disappoint.png"), "m2-266": require("../../assets/words/attract.png"), "m2-267": require("../../assets/words/celebrate.png"), "m2-268": require("../../assets/words/explode.png"), "m2-269": require("../../assets/words/include.png"), "m2-270": require("../../assets/words/protect.png"), "m2-271": require("../../assets/words/introduce.png"), "m2-272": require("../../assets/words/produce.png"), "m2-273": require("../../assets/words/chase.png"), "m2-274": require("../../assets/words/scratch.png"), "m2-275": require("../../assets/words/crash.png"), "m2-276": require("../../assets/words/stare.png"), "m2-277": require("../../assets/words/gaze.png"), "m2-278": require("../../assets/words/scare.png"), "m2-279": require("../../assets/words/grab.png"), "m2-280": require("../../assets/words/guard.png"),
  "m2-289": require("../../assets/words/except.png"),
  "m2-296": require("../../assets/words/replace.png"),

  // 기타 단어
  innocent: require("../../assets/words/innocent.png"),

  // 중학교 2학년 48Unit (20개 단어)
  low: require("../../assets/words/low.png"),
  sincerely: require("../../assets/words/sincerely.png"),
  fortunately: require("../../assets/words/fortunately.png"),
  finally: require("../../assets/words/finally.png"),
  immediately: require("../../assets/words/immediately.png"),
  especially: require("../../assets/words/especially.png"),
  else: require("../../assets/words/else.png"),
  actually: require("../../assets/words/actually.png"),
  hardly: require("../../assets/words/hardly.png"),
  otherwise: require("../../assets/words/otherwise.png"),
  tightly: require("../../assets/words/tightly.png"),
  recently: require("../../assets/words/recently.png"),
  rapidly: require("../../assets/words/rapidly.png"),
  however: require("../../assets/words/however.png"),
  politely: require("../../assets/words/politely.png"),
  rudely: require("../../assets/words/rudely.png"),
  further: require("../../assets/words/further.png"),
  frankly: require("../../assets/words/frankly.png"),
  properly: require("../../assets/words/properly.png"),
  haste: require("../../assets/words/haste.png"),

  // 단어 ID 매핑 (m2-941 ~ m2-960)
  "m2-941": require("../../assets/words/low.png"),
  "m2-942": require("../../assets/words/sincerely.png"),
  "m2-943": require("../../assets/words/fortunately.png"),
  "m2-944": require("../../assets/words/finally.png"),
  "m2-945": require("../../assets/words/immediately.png"),
  "m2-946": require("../../assets/words/especially.png"),
  "m2-947": require("../../assets/words/else.png"),
  "m2-948": require("../../assets/words/actually.png"),
  "m2-949": require("../../assets/words/hardly.png"),
  "m2-950": require("../../assets/words/otherwise.png"),
  "m2-951": require("../../assets/words/tightly.png"),
  "m2-952": require("../../assets/words/recently.png"),
  "m2-953": require("../../assets/words/rapidly.png"),
  "m2-954": require("../../assets/words/however.png"),
  "m2-955": require("../../assets/words/politely.png"),
  "m2-956": require("../../assets/words/rudely.png"),
  "m2-957": require("../../assets/words/further.png"),
  "m2-958": require("../../assets/words/frankly.png"),
  "m2-959": require("../../assets/words/properly.png"),
  "m2-960": require("../../assets/words/haste.png"),

  // 중학교 2학년 8Unit (20개 단어)
  refrigerator: require("../../assets/words/refrigerator.png"),
  crack: require("../../assets/words/crack.png"),
  judge: require("../../assets/words/judge.png"),
  slave: require("../../assets/words/slave.png"),
  settler: require("../../assets/words/settler.png"),
  fare: require("../../assets/words/fare.png"),
  gesture: require("../../assets/words/gesture.png"),
  planet: require("../../assets/words/planet.png"),
  type: require("../../assets/words/type.png"),
  secretary: require("../../assets/words/secretary.png"),
  devil: require("../../assets/words/devil.png"),
  scholar: require("../../assets/words/scholar.png"),
  pardon: require("../../assets/words/pardon.png"),
  kindergarten: require("../../assets/words/kindergarten.png"),
  detective: require("../../assets/words/detective.png"),
  license: require("../../assets/words/license.png"),
  palace: require("../../assets/words/palace.png"),
  spade: require("../../assets/words/spade.png"),
  square: require("../../assets/words/square.png"),
  "fountain-pen": require("../../assets/words/fountain-pen.png"),

  // 중학교 2학년 8Unit ID 매핑 (m2-141 ~ m2-160)
  "m2-141": require("../../assets/words/refrigerator.png"),
  "m2-142": require("../../assets/words/crack.png"),
  "m2-143": require("../../assets/words/judge.png"),
  "m2-144": require("../../assets/words/slave.png"),
  "m2-145": require("../../assets/words/settler.png"),
  "m2-146": require("../../assets/words/fare.png"),
  "m2-147": require("../../assets/words/gesture.png"),
  "m2-148": require("../../assets/words/planet.png"),
  "m2-149": require("../../assets/words/type.png"),
  "m2-150": require("../../assets/words/secretary.png"),
  "m2-151": require("../../assets/words/devil.png"),
  "m2-152": require("../../assets/words/scholar.png"),
  "m2-153": require("../../assets/words/pardon.png"),
  "m2-154": require("../../assets/words/kindergarten.png"),
  "m2-155": require("../../assets/words/detective.png"),
  "m2-156": require("../../assets/words/license.png"),
  "m2-157": require("../../assets/words/palace.png"),
  "m2-158": require("../../assets/words/spade.png"),
  "m2-159": require("../../assets/words/square.png"),
  "m2-160": require("../../assets/words/fountain-pen.png"),

  // 중학교 1학년 11Unit 공통 매핑
  "m1-208": require("../../assets/words/refrigerator.png"),

  // 중학교 2학년 50Unit (20개 단어)
  neither: require("../../assets/words/neither.png"),
  besides: require("../../assets/words/besides.png"),
  anyway: require("../../assets/words/anyway.png"),
  sometime: require("../../assets/words/sometime.png"),
  forward: require("../../assets/words/forward.png"),
  since: require("../../assets/words/since.png"),
  once: require("../../assets/words/once.png"),
  twice: require("../../assets/words/twice.png"),
  indeed: require("../../assets/words/indeed.png"),
  seldom: require("../../assets/words/seldom.png"),
  "upside-down": require("../../assets/words/upside-down.png"),
  whether: require("../../assets/words/whether.png"),
  unless: require("../../assets/words/unless.png"),
  though: require("../../assets/words/though.png"),
  while: require("../../assets/words/while.png"),
  usually: require("../../assets/words/usually.png"),
  safely: require("../../assets/words/safely.png"),
  along: require("../../assets/words/along.png"),
  without: require("../../assets/words/without.png"),
  behind: require("../../assets/words/behind.png"),

  // 중학교 2학년 50Unit ID 매핑 (m2-981 ~ m2-1000)
  "m2-981": require("../../assets/words/neither.png"),
  "m2-982": require("../../assets/words/besides.png"),
  "m2-983": require("../../assets/words/anyway.png"),
  "m2-984": require("../../assets/words/sometime.png"),
  "m2-985": require("../../assets/words/forward.png"),
  "m2-986": require("../../assets/words/since.png"),
  "m2-987": require("../../assets/words/once.png"),
  "m2-988": require("../../assets/words/twice.png"),
  "m2-989": require("../../assets/words/indeed.png"),
  "m2-990": require("../../assets/words/seldom.png"),
  "m2-991": require("../../assets/words/upside-down.png"),
  "m2-992": require("../../assets/words/whether.png"),
  "m2-993": require("../../assets/words/unless.png"),
  "m2-994": require("../../assets/words/though.png"),
  "m2-995": require("../../assets/words/while.png"),
  "m2-996": require("../../assets/words/usually.png"),
  "m2-997": require("../../assets/words/safely.png"),
  "m2-998": require("../../assets/words/along.png"),
  "m2-999": require("../../assets/words/without.png"),
  "m2-1000": require("../../assets/words/behind.png"),

  // 중학교 2학년 51Unit 잔여 단어 ID 매핑 (m2-1001 ~ m2-1003)
  "m2-1001": require("../../assets/words/beyond.png"),
  "m2-1002": require("../../assets/words/below.png"),
  "m2-1003": require("../../assets/words/toward.png"),

  // 중학교 2학년 15Unit 매핑
  "discuss": require("../../assets/words/discuss.png"),
  "m2-281": require("../../assets/words/discuss.png"),
  "shrug": require("../../assets/words/shrug.png"),
  "m2-282": require("../../assets/words/shrug.png"),
  "sniff": require("../../assets/words/sniff.png"),
  "m2-283": require("../../assets/words/sniff.png"),
  "scream": require("../../assets/words/scream.png"),
  "m2-284": require("../../assets/words/scream.png"),
  "rid": require("../../assets/words/rid.png"),
  "m2-285": require("../../assets/words/rid.png"),
  "surround": require("../../assets/words/surround.png"),
  "m2-286": require("../../assets/words/surround.png"),
  "cleave": require("../../assets/words/cleave.png"),
  "m2-287": require("../../assets/words/cleave.png"),
  "carve": require("../../assets/words/carve.png"),
  "m2-288": require("../../assets/words/carve.png"),
  "invent": require("../../assets/words/invent.png"),
  "m2-290": require("../../assets/words/invent.png"),
  "search": require("../../assets/words/search.png"),
  "m2-291": require("../../assets/words/search.png"),
  "abuse": require("../../assets/words/abuse.png"),
  "m2-292": require("../../assets/words/abuse.png"),
  "owe": require("../../assets/words/owe.png"),
  "m2-293": require("../../assets/words/owe.png"),
  "bless": require("../../assets/words/bless.png"),
  "m2-294": require("../../assets/words/bless.png"),
  "graduate": require("../../assets/words/graduate.png"),
  "m2-295": require("../../assets/words/graduate.png"),
  "collect": require("../../assets/words/collect.png"),
  "m2-297": require("../../assets/words/collect.png"),
  "upset": require("../../assets/words/upset.png"),
  "m2-298": require("../../assets/words/upset.png"),
  "arrest": require("../../assets/words/arrest.png"),
  "m2-299": require("../../assets/words/arrest.png"),
  "prove": require("../../assets/words/prove.png"),
  "m2-300": require("../../assets/words/prove.png"),
};
